In [3]:
import os
import sys
sys.path.append("../") # go to parent dir
%load_ext autoreload
%autoreload 2

In [4]:
from ultralytics import YOLO

# Load the train and test datasets

In [5]:
from functions.loading_functions import *
train_df = get_dataset("train")
test_df = get_dataset("test")

# Loading the pretrained model found here(https://huggingface.co/foduucom/plant-leaf-detection-and-classification)

In [ ]:
from ultralytics import YOLO

model = YOLO("plant-leaf-detection-and-classification/best.pt")

In [ ]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image
import shutil
import yaml
import torch

# Step 1: Process the original dataset and convert to YOLO format
def process_dataset(df, output_dir='yolo_dataset'):
    """
    Convert the original dataset format to YOLO format.
    
    Args:
        df: pandas DataFrame with columns ['Image_ID', 'class', 'confidence', 'ymin', 'xmin', 'ymax', 'xmax', 'class_id', 'ImagePath']
        output_dir: directory to save the YOLO format dataset
    """
    # Create necessary directories
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, 'images'), exist_ok=True)
    os.makedirs(os.path.join(output_dir, 'labels'), exist_ok=True)
    
    # Get unique classes and create class mapping
    classes = df['class'].unique().tolist()
    class_to_id = {class_name: i for i, class_name in enumerate(classes)}
    
    # Save the class mapping to a file
    with open(os.path.join(output_dir, 'classes.txt'), 'w') as f:
        for class_name in classes:
            f.write(f"{class_name}\n")
    
    # Process each image
    processed_images = set()
    for _, row in df.iterrows():
        img_path = row['ImagePath']
        img_id = row['Image_ID']
        
        # Skip if we've already processed this image
        if img_id in processed_images:
            continue
        
        # Copy the image to the YOLO dataset
        dst_img_path = os.path.join(output_dir, 'images', img_id)
        shutil.copy(img_path, dst_img_path)
        
        # Create a label file for this image
        label_filename = img_id.split(".")[0]+".txt"
        label_path = os.path.join(output_dir, 'labels', label_filename)
        
        # Get all annotations for this image
        img_annotations = df[df['Image_ID'] == img_id].copy()
        
        # Open the image to get dimensions
        with Image.open(img_path) as img:
            img_width, img_height = img.size
        
        # Write annotations in YOLO format
        with open(label_path, 'w') as f:
            for _, ann in img_annotations.iterrows():
                # Convert bbox coordinates to YOLO format (normalized center x, center y, width, height)
                x_min, y_min = ann['xmin'], ann['ymin']
                x_max, y_max = ann['xmax'], ann['ymax']
                
                # Normalize coordinates
                x_center = ((x_min + x_max) / 2) / img_width
                y_center = ((y_min + y_max) / 2) / img_height
                width = (x_max - x_min) / img_width
                height = (y_max - y_min) / img_height
                
                # Get class ID
                class_id = class_to_id[ann['class']]
                
                # In case they are none
                # Write in YOLO format: class_id x_center y_center width height
                f.write(f"{class_id} {x_center} {y_center} {width} {height}\n")
        
        processed_images.add(img_id)
    
    print(f"Processed {len(processed_images)} images with {len(df)} annotations.")
    return classes

def split_dataset(output_dir='yolo_dataset', train_ratio=0.8, val_ratio=0.2):
    """
    Split the dataset into train and validation sets (no test set).

    Args:
        output_dir: directory containing the YOLO format dataset
        train_ratio: ratio of training data
        val_ratio: ratio of validation data
    """
    # Get all image filenames
    image_dir = os.path.join(output_dir, 'images')
    all_images = [f for f in os.listdir(image_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]

    # Create train and val directories
    for split in ['train', 'val']:
        for subdir in ['images', 'labels']:
            os.makedirs(os.path.join(output_dir, split, subdir), exist_ok=True)

    # Split the dataset into train and validation
    train_images, val_images = train_test_split(all_images, train_size=train_ratio, random_state=42)

    # Move files to respective directories
    for split, images in [('train', train_images), ('val', val_images)]:
        for img_file in images:
            # Get corresponding label file
            label_file = os.path.splitext(img_file)[0] + '.txt'

            # Move image
            src_img = os.path.join(output_dir, 'images', img_file)
            dst_img = os.path.join(output_dir, split, 'images', img_file)
            shutil.copy(src_img, dst_img)

            # Move label
            src_label = os.path.join(output_dir, 'labels', label_file)
            dst_label = os.path.join(output_dir, split, 'labels', label_file)
            if os.path.exists(src_label):  # Some images might not have annotations
                shutil.copy(src_label, dst_label)

    print(f"Dataset split: {len(train_images)} train, {len(val_images)} validation images.")

def create_yaml_config(classes, output_dir='yolo_dataset'):
    """
    Create a YAML configuration file for YOLOv5.
    
    Args:
        classes: list of class names
        output_dir: directory containing the YOLO format dataset
    """
    config = {
        'path': os.path.abspath(output_dir),
        'train': 'train/images',
        'val': 'val/images',
        'test': 'test/images',
        'nc': len(classes),
        'names': classes
    }
    
    with open(os.path.join(output_dir, 'dataset.yaml'), 'w') as f:
        yaml.dump(config, f, default_flow_style=False)
    
    print(f"Created YAML configuration file at {os.path.join(output_dir, 'dataset.yaml')}")

def train_yolov11(dataset_yaml, model_name_path: str, model_size='s', epochs=100, batch_size=16, image_size=640):
    """
    Train a YOLOv11 model with focus on mAP50 metric.
    
    Args:
        dataset_yaml: path to the YAML configuration file
        model_name_path: path to the base model
        model_size: YOLOv11 model size ('n', 's', 'm', 'l', 'x')
        epochs: number of training epochs
        batch_size: batch size
        image_size: input image size
    """
    # Install Ultralytics package (which includes YOLOv11)
    os.system('pip install ultralytics')
    
    import ultralytics
    from ultralytics import YOLO
    
    # Print Ultralytics version for reference
    print(f"Ultralytics version: {ultralytics.__version__}")
    
    # Load the base model
    model = YOLO(model_name_path)
    
    # Train the model using the dataset YAML config
    # Set metrics to focus on mAP50
    results = model.train(
        data=dataset_yaml,
        epochs=epochs,
        batch=batch_size,
        device=[0],  # List all GPU indices to use
        imgsz=image_size,
        patience=50,  # Early stopping patience
        cache=True,
        project='yolov11_plant_detection',
        name=f'yolov11{model_size}_map50_focused',
        save=True,    # Save best model
        pretrained=True,
        verbose=True,
    )
    
    # Return the path to the best model based on mAP50
    best_model_path = results.best
    print(f"Best model (based on mAP50) saved to: {best_model_path}")
    return best_model_path


def run_inference(model_path, test_image_dir, output_dir='predictions', conf_threshold=0.25, iou_threshold=0.45):
    """
    Run inference on test images using YOLOv11 with focus on mAP50.
    
    Args:
        model_path: path to the trained YOLOv11 model
        test_image_dir: directory containing test images
        output_dir: directory to save prediction results
        conf_threshold: confidence threshold for detections
        iou_threshold: IoU threshold for NMS (affects mAP50 calculation)
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Load model using Ultralytics YOLO
    from ultralytics import YOLO
    model = YOLO(model_path)
    
    # Run inference with specified IoU threshold
    results = model.predict(
        source=test_image_dir,
        conf=conf_threshold,
        iou=iou_threshold,  # Set IoU threshold for NMS
        save=True,
        save_txt=True,
        save_conf=True,
        project=output_dir,
        name='detect_map50',
        verbose=True
    )
    
    # Export results to a CSV file
    predictions = []
    
    for result in results:
        img_name = os.path.basename(result.path)
        boxes = result.boxes
        
        if len(boxes) > 0:
            # Extract coordinates, confidence, and class
            for box in boxes:
                x1, y1, x2, y2 = box.xyxy[0].tolist()  # xyxy format (top-left, bottom-right)
                conf = box.conf.item()
                cls = int(box.cls.item())
                class_name = model.names[cls]
                
                predictions.append({
                    'image_name': img_name,
                    'class': class_name,
                    'confidence': conf,
                    'xmin': x1,
                    'ymin': y1,
                    'xmax': x2,
                    'ymax': y2
                })
    
    # Create DataFrame and save
    if predictions:
        pred_df = pd.DataFrame(predictions)
        pred_df.to_csv(os.path.join(output_dir, 'predictions.csv'), index=False)
    
    print(f"Inference complete. Results saved to {output_dir}")


def evaluate_model_map50(model_path, val_data_path, conf_threshold=0.25, iou_threshold=0.5):
    """
    Evaluate model specifically for mAP50 on validation data.
    
    Args:
        model_path: path to the trained YOLOv11 model
        val_data_path: path to validation data (folder or YAML)
        conf_threshold: confidence threshold for detections
        iou_threshold: IoU threshold for evaluation (set to 0.5 for mAP50)
    """
    from ultralytics import YOLO
    model = YOLO(model_path)
    
    # Run validation with focus on mAP50
    metrics = model.val(
        data=val_data_path,
        conf=conf_threshold,
        iou=iou_threshold,  # Set to 0.5 for mAP50
        verbose=True
    )
    
    # Extract mAP50 value
    map50 = metrics.box.map50
    print(f"\nModel mAP50: {map50:.4f}\n")
    
    # Return detailed metrics
    return metrics

# Step 4: Aggregate image-level predictions for multi-label evaluation
def aggregate_predictions(predictions_csv, output_csv='image_level_predictions.csv'):
    """
    Aggregate bounding box predictions to image-level class predictions.
    
    Args:
        predictions_csv: path to CSV file with bounding box predictions
        output_csv: path to save image-level predictions
    """
    # Load predictions
    pred_df = pd.read_csv(predictions_csv)
    
    # Group by image and aggregate classes
    image_level = pred_df.groupby('image_name')['class'].apply(lambda x: list(set(x))).reset_index()
    image_level.rename(columns={'class': 'predicted_classes'}, inplace=True)
    
    # Save to CSV
    image_level.to_csv(output_csv, index=False)
    
    print(f"Aggregated predictions saved to {output_csv}")

In [ ]:
import os
import pandas as pd
import numpy as np
import yaml
from pathlib import Path
from collections import Counter
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image
import shutil
import yaml
import torch

# Step 1: Process the original dataset and convert to YOLO format
def process_dataset(df, output_dir='yolo_dataset'):
    """
    Convert the original dataset format to YOLO format.
    
    Args:
        df: pandas DataFrame with columns ['Image_ID', 'class', 'confidence', 'ymin', 'xmin', 'ymax', 'xmax', 'class_id', 'ImagePath']
        output_dir: directory to save the YOLO format dataset
    """
    # Create necessary directories
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, 'images'), exist_ok=True)
    os.makedirs(os.path.join(output_dir, 'labels'), exist_ok=True)
    
    # Get unique classes and create class mapping
    classes = df['class'].unique().tolist()
    class_to_id = {class_name: i for i, class_name in enumerate(classes)}
    
    # Save the class mapping to a file
    with open(os.path.join(output_dir, 'classes.txt'), 'w') as f:
        for class_name in classes:
            f.write(f"{class_name}\n")
    
    # Process each image
    processed_images = set()
    for _, row in df.iterrows():
        img_path = row['ImagePath']
        img_id = row['Image_ID']
        
        # Skip if we've already processed this image
        if img_id in processed_images:
            continue
        
        # Copy the image to the YOLO dataset
        dst_img_path = os.path.join(output_dir, 'images', img_id)
        shutil.copy(img_path, dst_img_path)
        
        # Create a label file for this image
        label_filename = img_id.split(".")[0]+".txt"
        label_path = os.path.join(output_dir, 'labels', label_filename)
        
        # Get all annotations for this image
        img_annotations = df[df['Image_ID'] == img_id].copy()
        
        # Open the image to get dimensions
        with Image.open(img_path) as img:
            img_width, img_height = img.size
        
        # Write annotations in YOLO format
        with open(label_path, 'w') as f:
            for _, ann in img_annotations.iterrows():
                # Convert bbox coordinates to YOLO format (normalized center x, center y, width, height)
                x_min, y_min = ann['xmin'], ann['ymin']
                x_max, y_max = ann['xmax'], ann['ymax']
                
                # Normalize coordinates
                x_center = ((x_min + x_max) / 2) / img_width
                y_center = ((y_min + y_max) / 2) / img_height
                width = (x_max - x_min) / img_width
                height = (y_max - y_min) / img_height
                
                # Get class ID
                class_id = class_to_id[ann['class']]
                
                # In case they are none
                # Write in YOLO format: class_id x_center y_center width height
                f.write(f"{class_id} {x_center} {y_center} {width} {height}\n")
        
        processed_images.add(img_id)
    
    print(f"Processed {len(processed_images)} images with {len(df)} annotations.")
    return classes

def split_dataset(output_dir='yolo_dataset', train_ratio=0.8, val_ratio=0.2):
    """
    Split the dataset into train and validation sets (no test set).

    Args:
        output_dir: directory containing the YOLO format dataset
        train_ratio: ratio of training data
        val_ratio: ratio of validation data
    """
    # Get all image filenames
    image_dir = os.path.join(output_dir, 'images')
    all_images = [f for f in os.listdir(image_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]

    # Create train and val directories
    for split in ['train', 'val']:
        for subdir in ['images', 'labels']:
            os.makedirs(os.path.join(output_dir, split, subdir), exist_ok=True)

    # Split the dataset into train and validation
    train_images, val_images = train_test_split(all_images, train_size=train_ratio, random_state=42)

    # Move files to respective directories
    for split, images in [('train', train_images), ('val', val_images)]:
        for img_file in images:
            # Get corresponding label file
            label_file = os.path.splitext(img_file)[0] + '.txt'

            # Move image
            src_img = os.path.join(output_dir, 'images', img_file)
            dst_img = os.path.join(output_dir, split, 'images', img_file)
            shutil.copy(src_img, dst_img)

            # Move label
            src_label = os.path.join(output_dir, 'labels', label_file)
            dst_label = os.path.join(output_dir, split, 'labels', label_file)
            if os.path.exists(src_label):  # Some images might not have annotations
                shutil.copy(src_label, dst_label)

    print(f"Dataset split: {len(train_images)} train, {len(val_images)} validation images.")

def create_yaml_config(classes, output_dir='yolo_dataset'):
    """
    Create a YAML configuration file for YOLOv5.
    
    Args:
        classes: list of class names
        output_dir: directory containing the YOLO format dataset
    """
    config = {
        'path': os.path.abspath(output_dir),
        'train': 'train/images',
        'val': 'val/images',
        'test': 'test/images',
        'nc': len(classes),
        'names': classes
    }
    
    with open(os.path.join(output_dir, 'dataset.yaml'), 'w') as f:
        yaml.dump(config, f, default_flow_style=False)
    
    print(f"Created YAML configuration file at {os.path.join(output_dir, 'dataset.yaml')}")


def run_inference(model_path, test_image_dir, output_dir='predictions', conf_threshold=0.25, iou_threshold=0.45):
    """
    Run inference on test images using YOLOv11 with focus on mAP50.
    
    Args:
        model_path: path to the trained YOLOv11 model
        test_image_dir: directory containing test images
        output_dir: directory to save prediction results
        conf_threshold: confidence threshold for detections
        iou_threshold: IoU threshold for NMS (affects mAP50 calculation)
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Load model using Ultralytics YOLO
    from ultralytics import YOLO
    model = YOLO(model_path)
    
    # Run inference with specified IoU threshold
    results = model.predict(
        source=test_image_dir,
        conf=conf_threshold,
        iou=iou_threshold,  # Set IoU threshold for NMS
        save=True,
        save_txt=True,
        save_conf=True,
        project=output_dir,
        name='detect_map50',
        verbose=True
    )
    
    # Export results to a CSV file
    predictions = []
    
    for result in results:
        img_name = os.path.basename(result.path)
        boxes = result.boxes
        
        if len(boxes) > 0:
            # Extract coordinates, confidence, and class
            for box in boxes:
                x1, y1, x2, y2 = box.xyxy[0].tolist()  # xyxy format (top-left, bottom-right)
                conf = box.conf.item()
                cls = int(box.cls.item())
                class_name = model.names[cls]
                
                predictions.append({
                    'image_name': img_name,
                    'class': class_name,
                    'confidence': conf,
                    'xmin': x1,
                    'ymin': y1,
                    'xmax': x2,
                    'ymax': y2
                })
    
    # Create DataFrame and save
    if predictions:
        pred_df = pd.DataFrame(predictions)
        pred_df.to_csv(os.path.join(output_dir, 'predictions.csv'), index=False)
    
    print(f"Inference complete. Results saved to {output_dir}")

# Step 4: Aggregate image-level predictions for multi-label evaluation
def aggregate_predictions(predictions_csv, output_csv='image_level_predictions.csv'):
    """
    Aggregate bounding box predictions to image-level class predictions.
    
    Args:
        predictions_csv: path to CSV file with bounding box predictions
        output_csv: path to save image-level predictions
    """
    # Load predictions
    pred_df = pd.read_csv(predictions_csv)
    
    # Group by image and aggregate classes
    image_level = pred_df.groupby('image_name')['class'].apply(lambda x: list(set(x))).reset_index()
    image_level.rename(columns={'class': 'predicted_classes'}, inplace=True)
    
    # Save to CSV
    image_level.to_csv(output_csv, index=False)
    
    print(f"Aggregated predictions saved to {output_csv}")

def calculate_class_weights(dataset_yaml, method='inverse'):
    """
    Calculate class weights based on the distribution of classes in the dataset.
    Useful for analysis, but weights will need manual implementation in YOLO.
    
    Args:
        dataset_yaml: Path to the YAML dataset configuration file
        method: Method to calculate weights ('inverse' or 'effective')
    
    Returns:
        Dictionary mapping class indices to weights
    """
    # Load dataset configuration
    with open(dataset_yaml, 'r') as f:
        data_config = yaml.safe_load(f)
    
    # Get paths
    dataset_path = Path(data_config['path'])
    train_labels_path = dataset_path / 'train' / 'labels'
    
    # Count occurrences of each class
    class_counts = Counter()
    
    # Process all label files
    for label_file in train_labels_path.glob('*.txt'):
        with open(label_file, 'r') as f:
            for line in f:
                if line.strip():
                    class_id = int(line.strip().split()[0])
                    class_counts[class_id] += 1
    
    # Get total number of instances and classes
    total_instances = sum(class_counts.values())
    num_classes = len(data_config['names'])
    
    # Ensure all classes have a count (even if zero)
    for class_id in range(num_classes):
        if class_id not in class_counts:
            class_counts[class_id] = 0
    
    # Calculate weights based on method
    class_weights = {}
    
    if method == 'inverse':
        # Inverse frequency weighting
        for class_id in range(num_classes):
            count = class_counts[class_id]
            if count > 0:
                class_weights[class_id] = total_instances / (num_classes * count)
            else:
                class_weights[class_id] = 1.0  # Default weight for classes with no instances
    
    elif method == 'effective':
        # Effective number of samples weighting
        beta = 0.9999
        for class_id in range(num_classes):
            count = class_counts[class_id]
            if count > 0:
                # Formula: (1 - beta) / (1 - beta^n)
                effective_num = (1.0 - np.power(beta, count)) / (1.0 - beta)
                class_weights[class_id] = 1.0 / effective_num
            else:
                class_weights[class_id] = 1.0
    
    # Normalize weights to have mean of 1
    weight_sum = sum(class_weights.values())
    for class_id in class_weights:
        class_weights[class_id] = class_weights[class_id] * num_classes / weight_sum
    
    print(f"Calculated class weights: {class_weights}")
    
    # Also print the class names with their weights
    class_names = data_config['names']
    print("\nClass weights by name:")
    for class_id, weight in class_weights.items():
        if class_id < len(class_names):
            print(f"  {class_names[class_id]}: {weight:.4f}")
    
    return class_weights

def create_weighted_dataset(dataset_yaml, output_yaml=None, class_weight_method='inverse'):
    """
    Create a weighted dataset by duplicating underrepresented classes in the dataset.
    
    Args:
        dataset_yaml: Path to the original YAML dataset configuration
        output_yaml: Path to save the new YAML configuration (default: adds "_weighted" to original name)
        class_weight_method: Method to calculate class weights ('inverse' or 'effective')
    
    Returns:
        Path to the new weighted dataset YAML file
    """
    # Calculate class weights
    class_weights = calculate_class_weights(dataset_yaml, method=class_weight_method)
    
    # If no output path specified, create one
    if output_yaml is None:
        output_yaml = dataset_yaml.replace('.yaml', '_weighted.yaml')
    
    # Load the original dataset config
    with open(dataset_yaml, 'r') as f:
        data_config = yaml.safe_load(f)
    
    # Save the class weights for reference
    data_config['class_weights'] = {str(k): float(v) for k, v in class_weights.items()}
    
    # Write the updated config
    with open(output_yaml, 'w') as f:
        yaml.dump(data_config, f, default_flow_style=False)
    
    print(f"Created weighted dataset configuration at {output_yaml}")
    print("Note: The class weights are saved for reference only.")
    print("You'll need to use a custom YOLOv11 loss implementation or adjust the cls parameter.")
    
    return output_yaml

def train_yolov11(dataset_yaml, model_name_path, model_size='s', epochs=100, 
                 batch_size=16, image_size=640, cls_gain=0.5, patience=50, 
                 warmup_epochs=3.0, initial_lr=0.01):
    """
    Train a YOLOv11 model with focus on mAP50 metric.
    
    Args:
        dataset_yaml: Path to the YAML configuration file
        model_name_path: Path to the base model
        model_size: YOLOv11 model size ('n', 's', 'm', 'l', 'x')
        epochs: Number of training epochs
        batch_size: Batch size
        image_size: Input image size
        cls_gain: Classification loss weight
        patience: Early stopping patience
        warmup_epochs: Number of warmup epochs
        initial_lr: Initial learning rate
    """
    # Install Ultralytics package (which includes YOLOv11)
    os.system('pip install ultralytics')
    
    import ultralytics
    from ultralytics import YOLO
    
    # Print Ultralytics version for reference
    print(f"Ultralytics version: {ultralytics.__version__}")
    
    # Load the base model
    model = YOLO(model_name_path)
    
    # Calculate class weights for analysis (even though we can't directly use them)
    _ = calculate_class_weights(dataset_yaml)
    print("\nNote: Class weights are displayed for reference only.")
    print("YOLOv11 doesn't directly support per-class weights in the training API.")
    print("Consider these alternatives:")
    print("1. Adjust your dataset by oversampling minority classes")
    print("2. Use a higher cls value (e.g., 1.0) to emphasize classification accuracy")
    print("3. Modify the YOLO source code to support class weights\n")
    
    # Train the model with standard parameters
    results = model.train(
        data=dataset_yaml,
        epochs=epochs,
        batch=batch_size,
        device=[0],  # List all GPU indices to use
        imgsz=image_size,
        patience=patience,  # Early stopping patience
        cache=True,
        project='yolov11_plant_detection',
        name=f'yolov11{model_size}_map50_focused',
        save=True,    # Save best model
        pretrained=True,
        verbose=True,
        val=True,     # Enable validation
        save_period=10,  # Save checkpoints every 10 epochs
        # Learning rate settings
        lr0=initial_lr,  # Initial learning rate
        lrf=0.01,  # Final learning rate as a fraction of initial rate
        warmup_epochs=warmup_epochs,
        # Loss function weights - using a potentially higher cls value
        box=7.5,     # Box loss gain
        cls=cls_gain,  # Single value for classification loss
        # Other relevant parameters
        cos_lr=True,  # Use cosine learning rate scheduler
        close_mosaic=10,  # Disable mosaic in last 10 epochs
        amp=True,  # Use mixed precision training
        plots=True  # Generate and save plots
    )
    
    print(f"Training completed. Best model saved based on mAP50.")
    return model


def oversample_minority_classes(dataset_yaml, output_dir=None, threshold_factor=0.5):
    """
    Create a new dataset with oversampled minority classes.
    
    Args:
        dataset_yaml: Path to the YAML dataset configuration
        output_dir: Directory to save the new dataset (default: adds "_balanced" to original dir)
        threshold_factor: Classes with frequency below (max_freq * threshold_factor) will be oversampled
    
    Returns:
        Path to the new dataset YAML file
    """
    print("Creating balanced dataset by oversampling minority classes...")
    
    # Load dataset configuration
    with open(dataset_yaml, 'r') as f:
        data_config = yaml.safe_load(f)
    
    # Get paths
    dataset_path = Path(data_config['path'])
    
    # Create output directory if not specified
    if output_dir is None:
        output_dir = str(dataset_path) + "_balanced"
    output_dir = Path(output_dir)
    
    # Create necessary directories
    for split in ['train', 'val']:
        for subdir in ['images', 'labels']:
            os.makedirs(output_dir / split / subdir, exist_ok=True)
    
    # Copy validation data as is
    import shutil
    val_img_dir = dataset_path / 'val' / 'images'
    val_lbl_dir = dataset_path / 'val' / 'labels'
    
    for img_file in val_img_dir.glob('*'):
        shutil.copy(img_file, output_dir / 'val' / 'images')
    
    for lbl_file in val_lbl_dir.glob('*'):
        shutil.copy(lbl_file, output_dir / 'val' / 'labels')
    
    print("Copied validation data")
    
    # Count occurrences of each class in training set
    class_counts = Counter()
    train_labels_path = dataset_path / 'train' / 'labels'
    
    # Get all training files
    train_files = []
    for label_file in train_labels_path.glob('*.txt'):
        base_name = label_file.stem
        img_extensions = ['.jpg', '.jpeg', '.png', '.bmp']
        
        # Find corresponding image file
        img_file = None
        for ext in img_extensions:
            potential_img = dataset_path / 'train' / 'images' / (base_name + ext)
            if potential_img.exists():
                img_file = potential_img
                break
        
        if img_file:
            # Read labels to get classes
            with open(label_file, 'r') as f:
                lines = f.readlines()
                file_classes = [int(line.strip().split()[0]) for line in lines if line.strip()]
                
                # Count classes
                for cls in file_classes:
                    class_counts[cls] += 1
                
                # Store file info
                train_files.append({
                    'label_file': label_file,
                    'img_file': img_file,
                    'classes': file_classes
                })
    
    # Determine which classes need oversampling
    max_count = max(class_counts.values()) if class_counts else 0
    threshold = max_count * threshold_factor
    
    minority_classes = {cls: count for cls, count in class_counts.items() if count < threshold}
    
    print(f"Class distribution: {dict(class_counts)}")
    print(f"Identified minority classes: {minority_classes}")
    
    # Copy all original files first
    for file_info in train_files:
        shutil.copy(file_info['img_file'], output_dir / 'train' / 'images')
        shutil.copy(file_info['label_file'], output_dir / 'train' / 'labels')
    
    # Oversample files with minority classes
    duplicated = 0
    for file_info in train_files:
        # Check if file contains any minority class
        if any(cls in minority_classes for cls in file_info['classes']):
            # Calculate duplication factor based on class frequency
            # Files with rarer classes get duplicated more times
            rarest_class = min(
                (cls for cls in file_info['classes'] if cls in minority_classes),
                key=lambda c: minority_classes[c],
                default=None
            )
            
            if rarest_class is not None:
                duplication_factor = int(max_count / minority_classes[rarest_class]) - 1
                duplication_factor = min(duplication_factor, 5)  # Cap at 5x duplication
                
                for i in range(duplication_factor):
                    # Create new filenames for duplicates
                    new_base = f"{file_info['label_file'].stem}_dup{i+1}"
                    new_img = output_dir / 'train' / 'images' / f"{new_base}{file_info['img_file'].suffix}"
                    new_lbl = output_dir / 'train' / 'labels' / f"{new_base}.txt"
                    
                    # Copy files with new names
                    shutil.copy(file_info['img_file'], new_img)
                    shutil.copy(file_info['label_file'], new_lbl)
                    duplicated += 1
    
    print(f"Created {duplicated} duplicate files to balance the dataset")
    
    # Create new YAML file
    new_yaml_path = output_dir / "dataset_balanced.yaml"
    new_config = data_config.copy()
    new_config['path'] = str(output_dir)
    
    with open(new_yaml_path, 'w') as f:
        yaml.dump(new_config, f, default_flow_style=False)
    
    print(f"Created balanced dataset configuration at {new_yaml_path}")
    return str(new_yaml_path)

In [17]:
# Process dataset
classes = process_dataset(train_df)

Processed 5529 images with 9792 annotations.

In [18]:
split_dataset()

Dataset split: 4197 train, 1050 validation images.

In [22]:
create_yaml_config(classes)

Created YAML configuration file at yolo_dataset/dataset.yaml

In [34]:
pretrained_yolo_path = "plant-leaf-detection-and-classification/best.pt"
# Train model with class weights
model = train_yolov11(
    dataset_yaml='yolo_dataset/dataset.yaml',
    model_name_path=pretrained_yolo_path,
    model_size='s',
        epochs=100,
        batch_size=16,
        image_size=640,
        cls_gain=1.0,  # Increase classification weight
        patience=50,
        warmup_epochs=3.0,
        initial_lr=0.01
    )

Requirement already satisfied: ultralytics in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (8.0.43)
Requirement already satisfied: matplotlib>=3.2.2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (3.10.1)
Requirement already satisfied: numpy>=1.18.5 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (1.26.4)
Requirement already satisfied: opencv-python>=4.6.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (4.10.0.84)
Requirement already satisfied: Pillow>=7.1.2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (11.1.0)
Requirement already satisfied: PyYAML>=5.3.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (1.15.2)
Requirement already satisfied: torch>=1.7.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.6.0+cu118)
Requirement already satisfied: torchvision>=0.8.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (0.21.0+cu118)
Requirement already satisfied: tqdm>=4.64.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (4.67.1)
Requirement already satisfied: tensorboard>=2.4.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.19.0)
Requirement already satisfied: pandas>=1.1.4 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.2.3)
Requirement already satisfied: seaborn>=0.11.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (0.13.2)
Requirement already satisfied: psutil in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (7.0.0)
Requirement already satisfied: thop>=0.1.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (0.1.1.post2209072238)
Requirement already satisfied: wheel>=0.38.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (0.45.1)
Requirement already satisfied: sentry-sdk in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.24.1)
Requirement already satisfied: contourpy>=1.0.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.2.2->ultralytics) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (2025.1.31)
Requirement already satisfied: absl-py>=0.4 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (2.2.0)
Requirement already satisfied: grpcio>=1.48.2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (1.71.0)
Requirement already satisfied: markdown>=2.6.8 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (3.7)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (3.20.1)
Requirement already satisfied: setuptools>=41.0.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (75.8.2)
Requirement already satisfied: six>1.9 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (1.17.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from tensorboard>=2.4.1->ultralytics) (3.1.3)
Requirement already satisfied: filelock in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (4.12.2)
Requirement already satisfied: networkx in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (3.3)
Requirement already satisfied: jinja2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (3.1.4)
Requirement already satisfied: fsspec in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (11.8.86)
Requirement already satisfied: triton==3.2.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.7.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from sympy==1.13.1->torch>=1.7.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard>=2.4.1->ultralytics) (2.1.5)
Ultralytics version: 8.3.94
Calculated class weights: {0: 0.7751539894355594, 1: 1.3052705302174301, 2: 0.9195754803470106}

Class weights by name:
  healthy: 0.7752
  anthracnose: 1.3053
  cssvd: 0.9196

Note: Class weights are displayed for reference only.
YOLOv11 doesn't directly support per-class weights in the training API.
Consider these alternatives:
1. Adjust your dataset by oversampling minority classes
2. Use a higher cls value (e.g., 1.0) to emphasize classification accuracy
3. Modify the YOLO source code to support class weights

New https://pypi.org/project/ultralytics/8.3.96 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=plant-leaf-detection-and-classification/best.pt, data=yolo_dataset/dataset.yaml, epochs=100, time=None, patience=50, batch=16, imgsz=640, save=True, save_period=10, cache=True, device=[0], workers=8, project=yolov11_plant_detection, name=yolov11s_map50_focused, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=1.0, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_plant_detection/yolov11s_map50_focused
Overriding model.yaml nc=46 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
Model summary: 129 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/labels.cache... 4197 images, 0 backgrounds, 686 corrupt: 100%|██████████| 4197/4197 [00:00<?, ?it/s]

train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AJD939.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_CxIwDu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_E1fISS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FTVHZk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FViv94.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1895]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FVssBB.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Fk8aG8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1905      1.0218]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FliLbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2589      1.6944]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_Fm1oY7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FqB8FS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/train/images/ID_FtYRqz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      2.1906]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (3.1GB RAM): 100%|██████████| 3511/3511 [00:18<00:00, 190.54it/s]
val: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/labels.cache... 1050 images, 0 backgrounds, 195 corrupt: 100%|██████████| 1050/1050 [00:00<?, ?it/s]

val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_AclybJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0985      1.2153]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_BsWVWD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1969      2.0294]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_FWv6k7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_GA4ocU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1171]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_GONPQx.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0785]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_GWhiLp.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_GZeZQ7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1696]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_GkZMVQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.8572]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_HIFZij.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1217]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_HQpL3y.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0294]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_HS970U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.4939      1.0742]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_IRVs9J.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_IRWSPd.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_IUz3r9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2824]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_IjpumM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_IwPsnt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2923]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_JHsmyN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1121      1.6861]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_JltOLk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2834      1.1822]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KDq13B.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2144      2.0156]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KTP6kp.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2061]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KZwJAM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2612]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KbaWjL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1322        2.18]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KkyQ36.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1244      2.1956]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KoUDAP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0119      1.2586]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KqcXSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1134      1.1291]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_KxHwli.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_L0K6CF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0976]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_LA1RfJ.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_LFYoyL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_LLSZyI.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2784]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_LkJ8Zz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0245]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_MIeJvr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1101      1.0147      1.1377]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_MhuKki.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Mmotno.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1119]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_N9A9JN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1496]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_NGvzWH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0832]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_NPQOoz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.089]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_NRkeOG.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0589]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Na6hR0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_NbU1Pn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1591]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_NfmKR2.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.228]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Ng5Pt8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3006      1.1004]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Nk9IfK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1862]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_NuyEeD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0397      1.2612]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_OIGzbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2004]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_OZ1lc7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0673      1.1413]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_OtEC7c.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_OwFJgN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_P2qCLW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2576]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_PDbzh1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.167]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_PIg9if.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2163       1.042]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_POD5HU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_POyDGg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_PQm2Ft.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0428]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_PVckAY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1088]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_PqV4gW.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Q938mO.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2161]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_QZGiws.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1227]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_QopCWu.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1433      1.8344]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Rfm919.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.289]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_S3A64w.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0642]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_SJKaao.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2408      1.4717]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_SSGiW2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.9108]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_SVzl5X.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Sb77iH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2477]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_SnC6Z6.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_SuY5t1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2561]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_T7RQCl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.155      2.1344]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_T9Sifn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2356      1.9733]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_T9n3Yk.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_TLVeAC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0949]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_ULx8cJ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2339]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_UjMeQ0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.254]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Uoy7f2.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_UrKjY8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3075       1.525]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_VwIYf0.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_WILdJN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3317      1.0202]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_WIuXLH.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_WKcQeb.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0126]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_WR3TUM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2209      1.0165]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_WU9wED.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2579]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Wapq8b.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3108]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_WgGnAX.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056      1.1534]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_XozOJV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3079]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_YG32gk.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_YVZEp0.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1647]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_YVrqE6.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0927]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_YxpGmG.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2731]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_Z3epYc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset/val/images/ID_ZFUKX5.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1253      1.2404]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.7GB RAM): 100%|██████████| 855/855 [00:04<00:00, 191.49it/s]

Plotting labels to yolov11_plant_detection/yolov11s_map50_focused/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_plant_detection/yolov11s_map50_focused
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      1/100      18.2G      1.238      3.412      1.642         36        640: 100%|██████████| 220/220 [00:24<00:00,  8.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.72it/s]

                   all        855       1509       0.57      0.473      0.453      0.249

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      2/100      18.2G       1.13      2.341      1.474         29        640: 100%|██████████| 220/220 [00:22<00:00,  9.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.68it/s]

                   all        855       1509      0.559      0.453      0.457      0.247

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      3/100      18.2G      1.087      2.198      1.439         42        640: 100%|██████████| 220/220 [00:21<00:00, 10.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.73it/s]

                   all        855       1509      0.599      0.455      0.472      0.253

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      4/100      18.2G      1.036      2.067      1.406         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.75it/s]

                   all        855       1509      0.535       0.49      0.473      0.258

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      5/100      18.2G     0.9796      1.893      1.356         27        640: 100%|██████████| 220/220 [00:21<00:00, 10.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.70it/s]

                   all        855       1509      0.605      0.488      0.506      0.278

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      6/100      18.2G     0.9017       1.74      1.305         32        640: 100%|██████████| 220/220 [00:21<00:00, 10.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.82it/s]

                   all        855       1509      0.546      0.436      0.442      0.239

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      7/100      18.2G     0.8554      1.615      1.271         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.59it/s]

                   all        855       1509        0.6      0.518      0.516        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      8/100      18.2G     0.8138      1.526      1.246         35        640: 100%|██████████| 220/220 [00:21<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.68it/s]

                   all        855       1509      0.631      0.503      0.537      0.303

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      9/100      18.2G      0.788      1.457      1.223         27        640: 100%|██████████| 220/220 [00:21<00:00, 10.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.65it/s]

                   all        855       1509      0.577      0.503        0.5      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     10/100      18.2G     0.7629      1.426       1.21         25        640: 100%|██████████| 220/220 [00:21<00:00, 10.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.34it/s]

                   all        855       1509      0.564      0.537      0.524      0.297

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     11/100      18.2G     0.7391      1.376      1.195         31        640: 100%|██████████| 220/220 [00:21<00:00, 10.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.22it/s]

                   all        855       1509      0.591      0.509      0.529        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     12/100      18.2G     0.7123      1.328      1.178         32        640: 100%|██████████| 220/220 [00:21<00:00, 10.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.44it/s]

                   all        855       1509      0.603       0.54      0.542      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     13/100      18.2G     0.6987      1.266      1.165         31        640: 100%|██████████| 220/220 [00:21<00:00, 10.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.72it/s]

                   all        855       1509      0.645      0.525      0.546      0.312

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     14/100      18.2G     0.6836      1.231      1.152         35        640: 100%|██████████| 220/220 [00:21<00:00, 10.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.63it/s]

                   all        855       1509      0.636      0.552      0.551      0.306

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     15/100      18.2G      0.662      1.193      1.143         29        640: 100%|██████████| 220/220 [00:21<00:00, 10.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.39it/s]

                   all        855       1509      0.634      0.547      0.561      0.325

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     16/100      18.2G     0.6438      1.174      1.128         36        640: 100%|██████████| 220/220 [00:21<00:00, 10.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.64it/s]

                   all        855       1509      0.609      0.531      0.529      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     17/100      18.2G     0.6258      1.152       1.12         34        640: 100%|██████████| 220/220 [00:21<00:00, 10.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.56it/s]

                   all        855       1509      0.645      0.555      0.575      0.329

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     18/100      18.2G     0.6243      1.159      1.126         28        640: 100%|██████████| 220/220 [00:21<00:00, 10.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.56it/s]

                   all        855       1509      0.645      0.548      0.576      0.333

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     19/100      18.2G     0.6142      1.112      1.116         30        640: 100%|██████████| 220/220 [00:21<00:00, 10.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.65it/s]

                   all        855       1509      0.694      0.583      0.597      0.351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     20/100      18.2G     0.6056      1.097      1.112         28        640: 100%|██████████| 220/220 [00:21<00:00, 10.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.60it/s]

                   all        855       1509       0.65      0.565      0.588      0.341

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     21/100      18.2G     0.5873       1.08      1.095         15        640: 100%|██████████| 220/220 [00:21<00:00, 10.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.72it/s]

                   all        855       1509       0.66      0.582       0.61      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     22/100      18.2G     0.5773      1.053      1.095         42        640: 100%|██████████| 220/220 [00:21<00:00, 10.06it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.55it/s]

                   all        855       1509      0.708      0.536      0.585      0.344

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     23/100      18.2G     0.5728      1.039      1.091         30        640: 100%|██████████| 220/220 [00:21<00:00, 10.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.72it/s]

                   all        855       1509      0.635      0.535      0.564      0.329

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     24/100      18.2G      0.566      1.012      1.088         37        640: 100%|██████████| 220/220 [00:21<00:00, 10.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.60it/s]

                   all        855       1509      0.682      0.572        0.6      0.351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     25/100      18.2G     0.5566      1.003      1.073         31        640: 100%|██████████| 220/220 [00:21<00:00, 10.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.49it/s]

                   all        855       1509      0.677      0.562      0.593      0.349

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     26/100      18.2G     0.5434     0.9904       1.07         17        640: 100%|██████████| 220/220 [00:21<00:00, 10.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.62it/s]

                   all        855       1509      0.702      0.558      0.619      0.365

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     27/100      18.2G     0.5437     0.9913      1.072         32        640: 100%|██████████| 220/220 [00:21<00:00, 10.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.53it/s]

                   all        855       1509      0.653      0.578      0.609      0.363

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     28/100      18.2G     0.5242     0.9459       1.06         35        640: 100%|██████████| 220/220 [00:21<00:00, 10.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.51it/s]

                   all        855       1509      0.658      0.568        0.6      0.348

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     29/100      18.2G     0.5226     0.9329      1.063         21        640: 100%|██████████| 220/220 [00:21<00:00, 10.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.58it/s]

                   all        855       1509      0.667      0.591      0.608       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     30/100      18.2G     0.5147     0.9301      1.057         34        640: 100%|██████████| 220/220 [00:21<00:00, 10.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.40it/s]

                   all        855       1509      0.659      0.573      0.597      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     31/100      18.2G     0.5099     0.9348      1.055         36        640: 100%|██████████| 220/220 [00:21<00:00, 10.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.32it/s]

                   all        855       1509      0.641      0.578      0.607      0.351

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     32/100      18.2G     0.5009     0.9031      1.049         22        640: 100%|██████████| 220/220 [00:21<00:00, 10.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.32it/s]

                   all        855       1509      0.662        0.6      0.621      0.367

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     33/100      18.2G     0.4985     0.8891      1.048         29        640: 100%|██████████| 220/220 [00:22<00:00,  9.96it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.44it/s]

                   all        855       1509      0.652      0.596      0.608      0.369

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     34/100      18.2G       0.49     0.8778      1.045         32        640: 100%|██████████| 220/220 [00:21<00:00, 10.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.06it/s]

                   all        855       1509      0.674      0.579      0.609      0.368

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     35/100      18.2G     0.4897     0.8902      1.041         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.12it/s]

                   all        855       1509      0.724      0.583      0.642      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     36/100      18.2G     0.4789     0.8668       1.04         32        640: 100%|██████████| 220/220 [00:21<00:00, 10.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.18it/s]

                   all        855       1509      0.653      0.607      0.627      0.369

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     37/100      18.2G      0.474     0.8603      1.036         28        640: 100%|██████████| 220/220 [00:22<00:00,  9.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.58it/s]

                   all        855       1509      0.718      0.577      0.634      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     38/100      18.2G      0.466     0.8356      1.032         27        640: 100%|██████████| 220/220 [00:21<00:00, 10.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.41it/s]

                   all        855       1509       0.68      0.608      0.638      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     39/100      18.2G     0.4739     0.8427      1.036         31        640: 100%|██████████| 220/220 [00:22<00:00, 10.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.76it/s]

                   all        855       1509      0.668      0.602       0.63      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     40/100      18.2G     0.4645     0.8359      1.031         22        640: 100%|██████████| 220/220 [00:22<00:00,  9.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.93it/s]

                   all        855       1509       0.69        0.6      0.634      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     41/100      18.2G     0.4563     0.8258      1.026         30        640: 100%|██████████| 220/220 [00:22<00:00,  9.85it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.11it/s]

                   all        855       1509      0.693      0.596      0.642      0.388

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     42/100      18.2G     0.4592     0.8282      1.026         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.41it/s]

                   all        855       1509      0.709      0.616      0.647      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     43/100      18.2G     0.4465     0.8093      1.019         29        640: 100%|██████████| 220/220 [00:21<00:00, 10.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.22it/s]

                   all        855       1509      0.707      0.612      0.654      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     44/100      18.2G     0.4437     0.7996      1.015         33        640: 100%|██████████| 220/220 [00:21<00:00, 10.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.22it/s]

                   all        855       1509      0.653       0.62      0.621      0.367

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     45/100      18.2G     0.4365     0.7841      1.016         22        640: 100%|██████████| 220/220 [00:21<00:00, 10.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.26it/s]

                   all        855       1509      0.708      0.614      0.653      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     46/100      18.2G     0.4358     0.7681      1.013         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.62it/s]

                   all        855       1509      0.745      0.572      0.655      0.391

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     47/100      18.2G     0.4372     0.7721      1.015         34        640: 100%|██████████| 220/220 [00:21<00:00, 10.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.38it/s]

                   all        855       1509      0.706      0.625      0.646      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     48/100      18.2G     0.4266     0.7574      1.011         25        640: 100%|██████████| 220/220 [00:21<00:00, 10.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.36it/s]

                   all        855       1509      0.707       0.59      0.644      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     49/100      18.2G     0.4199     0.7463      1.006         31        640: 100%|██████████| 220/220 [00:22<00:00,  9.81it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.30it/s]

                   all        855       1509      0.722      0.599      0.656      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     50/100      18.2G     0.4208     0.7467      1.009         31        640: 100%|██████████| 220/220 [00:22<00:00,  9.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.33it/s]

                   all        855       1509      0.656      0.619      0.642      0.377

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     51/100      18.2G     0.4142     0.7274          1         19        640: 100%|██████████| 220/220 [00:22<00:00,  9.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.23it/s]

                   all        855       1509      0.732      0.596      0.657      0.403

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     52/100      18.2G     0.4082     0.7254          1         28        640: 100%|██████████| 220/220 [00:22<00:00,  9.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.04it/s]

                   all        855       1509      0.666      0.621      0.621      0.378

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     53/100      18.2G     0.4072     0.7326     0.9997         26        640: 100%|██████████| 220/220 [00:22<00:00,  9.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.44it/s]

                   all        855       1509      0.702      0.629      0.662      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     54/100      18.2G     0.4003     0.7228     0.9974         25        640: 100%|██████████| 220/220 [00:22<00:00,  9.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.27it/s]

                   all        855       1509      0.709      0.624      0.662      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     55/100      18.2G     0.3969     0.7028      0.997         30        640: 100%|██████████| 220/220 [00:22<00:00, 10.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.44it/s]

                   all        855       1509       0.71      0.603      0.654      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     56/100      18.2G     0.3964     0.6973     0.9953         37        640: 100%|██████████| 220/220 [00:22<00:00,  9.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.50it/s]

                   all        855       1509      0.711      0.593      0.642      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     57/100      18.2G     0.3935     0.7079     0.9929         34        640: 100%|██████████| 220/220 [00:21<00:00, 10.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.56it/s]

                   all        855       1509      0.672      0.602       0.63      0.389

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     58/100      18.2G      0.383     0.6767     0.9873         38        640: 100%|██████████| 220/220 [00:21<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.32it/s]

                   all        855       1509      0.691      0.615       0.64      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     59/100      18.2G      0.386     0.6817     0.9882         40        640: 100%|██████████| 220/220 [00:21<00:00, 10.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.28it/s]

                   all        855       1509      0.705      0.607      0.641      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     60/100      18.2G     0.3764     0.6728     0.9881         30        640: 100%|██████████| 220/220 [00:22<00:00,  9.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.88it/s]

                   all        855       1509      0.694      0.606      0.634       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     61/100      18.2G     0.3725     0.6644     0.9831         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.37it/s]

                   all        855       1509      0.686      0.632      0.653      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     62/100      18.2G     0.3751     0.6624     0.9866         36        640: 100%|██████████| 220/220 [00:22<00:00,  9.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.54it/s]

                   all        855       1509       0.71      0.628      0.665      0.414

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     63/100      18.2G     0.3747     0.6597     0.9834         23        640: 100%|██████████| 220/220 [00:22<00:00,  9.94it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.78it/s]

                   all        855       1509      0.714      0.608      0.651      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     64/100      18.2G      0.367     0.6488     0.9815         40        640: 100%|██████████| 220/220 [00:22<00:00,  9.82it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.38it/s]

                   all        855       1509       0.68      0.629      0.657      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     65/100      18.2G     0.3581     0.6226     0.9744         28        640: 100%|██████████| 220/220 [00:22<00:00,  9.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.23it/s]

                   all        855       1509      0.706      0.612       0.65      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     66/100      18.2G     0.3663     0.6288      0.984         37        640: 100%|██████████| 220/220 [00:22<00:00,  9.95it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.76it/s]

                   all        855       1509      0.716      0.618       0.66      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     67/100      18.2G     0.3625     0.6359     0.9793         34        640: 100%|██████████| 220/220 [00:22<00:00,  9.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.46it/s]

                   all        855       1509      0.677       0.63      0.639       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     68/100      18.2G     0.3498     0.6133      0.972         42        640: 100%|██████████| 220/220 [00:22<00:00,  9.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.34it/s]

                   all        855       1509      0.687      0.601      0.632      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     69/100      18.2G     0.3501     0.6062     0.9752         26        640: 100%|██████████| 220/220 [00:22<00:00,  9.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.37it/s]

                   all        855       1509      0.702      0.609      0.635      0.397

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     70/100      18.2G      0.344     0.5968     0.9677         20        640: 100%|██████████| 220/220 [00:22<00:00, 10.00it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.78it/s]

                   all        855       1509      0.724      0.606      0.645      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     71/100      18.2G     0.3452     0.5957     0.9698         35        640: 100%|██████████| 220/220 [00:21<00:00, 10.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.66it/s]

                   all        855       1509      0.679      0.621      0.637      0.392

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     72/100      18.2G     0.3466     0.5995     0.9692         31        640: 100%|██████████| 220/220 [00:21<00:00, 10.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.79it/s]

                   all        855       1509      0.689      0.621      0.649      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     73/100      18.2G     0.3407     0.6017      0.971         25        640: 100%|██████████| 220/220 [00:21<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.81it/s]

                   all        855       1509      0.683      0.645      0.663      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     74/100      18.2G     0.3373     0.5842     0.9679         30        640: 100%|██████████| 220/220 [00:21<00:00, 10.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.66it/s]

                   all        855       1509      0.695      0.639      0.662      0.414

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     75/100      18.2G     0.3371     0.5843     0.9674         33        640: 100%|██████████| 220/220 [00:22<00:00,  9.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.86it/s]

                   all        855       1509      0.716      0.611      0.644        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     76/100      18.2G     0.3282     0.5737     0.9618         29        640: 100%|██████████| 220/220 [00:21<00:00, 10.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.92it/s]

                   all        855       1509      0.711      0.628      0.656      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     77/100      18.2G     0.3262     0.5668     0.9623         36        640: 100%|██████████| 220/220 [00:22<00:00,  9.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.71it/s]

                   all        855       1509      0.691      0.635      0.657       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     78/100      18.2G     0.3308     0.5739     0.9682         26        640: 100%|██████████| 220/220 [00:21<00:00, 10.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.81it/s]

                   all        855       1509      0.702      0.645      0.656      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     79/100      18.2G     0.3282     0.5693     0.9643         25        640: 100%|██████████| 220/220 [00:21<00:00, 10.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.57it/s]

                   all        855       1509      0.671      0.635      0.645      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     80/100      18.2G     0.3192     0.5495     0.9557         42        640: 100%|██████████| 220/220 [00:22<00:00,  9.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.94it/s]

                   all        855       1509      0.707      0.617      0.651      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     81/100      18.2G     0.3146     0.5401     0.9543         27        640: 100%|██████████| 220/220 [00:21<00:00, 10.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.92it/s]

                   all        855       1509      0.736      0.604      0.658      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     82/100      18.2G     0.3255     0.5582     0.9591         25        640: 100%|██████████| 220/220 [00:21<00:00, 10.02it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.62it/s]

                   all        855       1509      0.704      0.628      0.651      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     83/100      18.2G     0.3176     0.5464     0.9579         37        640: 100%|██████████| 220/220 [00:22<00:00,  9.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.83it/s]

                   all        855       1509      0.689      0.648      0.652      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     84/100      18.2G     0.3141     0.5412     0.9566         28        640: 100%|██████████| 220/220 [00:21<00:00, 10.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.89it/s]

                   all        855       1509      0.698      0.633      0.653      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     85/100      18.2G     0.3151     0.5473     0.9594         33        640: 100%|██████████| 220/220 [00:22<00:00,  9.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.75it/s]

                   all        855       1509      0.702      0.633      0.654      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     86/100      18.2G     0.3155     0.5428     0.9596         28        640: 100%|██████████| 220/220 [00:22<00:00,  9.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.75it/s]

                   all        855       1509      0.704      0.629      0.652      0.404

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     87/100      18.2G     0.3114     0.5262     0.9555         27        640: 100%|██████████| 220/220 [00:21<00:00, 10.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.83it/s]

                   all        855       1509        0.7      0.636      0.654      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     88/100      18.2G      0.315     0.5418     0.9558         27        640: 100%|██████████| 220/220 [00:21<00:00, 10.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.72it/s]

                   all        855       1509      0.704      0.621      0.651      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     89/100      18.2G     0.3092     0.5364     0.9538         21        640: 100%|██████████| 220/220 [00:21<00:00, 10.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.72it/s]

                   all        855       1509      0.684      0.643      0.657      0.409

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     90/100      18.2G     0.3094     0.5324     0.9532         31        640: 100%|██████████| 220/220 [00:22<00:00,  9.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.72it/s]

                   all        855       1509       0.71      0.627      0.656      0.411
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     91/100      18.2G      1.093      1.799       1.59         11        640: 100%|██████████| 220/220 [00:21<00:00, 10.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.87it/s]

                   all        855       1509      0.656       0.62      0.613      0.373

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     92/100      18.2G      1.046      1.634      1.502         21        640: 100%|██████████| 220/220 [00:21<00:00, 10.13it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.55it/s]

                   all        855       1509      0.701      0.629      0.649      0.399

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     93/100      18.2G      1.037       1.59      1.482          8        640: 100%|██████████| 220/220 [00:21<00:00, 10.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.09it/s]

                   all        855       1509      0.707      0.641      0.659      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     94/100      18.2G       1.02      1.578       1.47         12        640: 100%|██████████| 220/220 [00:21<00:00, 10.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.85it/s]

                   all        855       1509      0.702      0.633      0.658       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     95/100      18.2G      1.013      1.532      1.461         11        640: 100%|██████████| 220/220 [00:21<00:00, 10.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.76it/s]

                   all        855       1509      0.715      0.635      0.664      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     96/100      18.2G     0.9941      1.512      1.457         13        640: 100%|██████████| 220/220 [00:21<00:00, 10.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.66it/s]

                   all        855       1509      0.707      0.641      0.664      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     97/100      18.2G     0.9965      1.528      1.444         12        640: 100%|██████████| 220/220 [00:21<00:00, 10.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.81it/s]

                   all        855       1509       0.71      0.642      0.665      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     98/100      18.2G     0.9933      1.502      1.439         16        640: 100%|██████████| 220/220 [00:21<00:00, 10.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.75it/s]

                   all        855       1509      0.713      0.638      0.667      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

     99/100      18.2G     0.9936      1.498       1.45         12        640: 100%|██████████| 220/220 [00:21<00:00, 10.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.33it/s]

                   all        855       1509      0.713      0.641      0.667      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

    100/100      18.2G     0.9908      1.496      1.445          9        640: 100%|██████████| 220/220 [00:21<00:00, 10.07it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  8.44it/s]

                   all        855       1509      0.721      0.634      0.668      0.419

100 epochs completed in 0.713 hours.
Optimizer stripped from yolov11_plant_detection/yolov11s_map50_focused/weights/last.pt, 22.5MB
Optimizer stripped from yolov11_plant_detection/yolov11s_map50_focused/weights/best.pt, 22.5MB

Validating yolov11_plant_detection/yolov11s_map50_focused/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
Model summary (fused): 72 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 27/27 [00:03<00:00,  7.10it/s]

                   all        855       1509       0.72      0.635      0.668      0.419
               healthy        246        619       0.68      0.614      0.643      0.393
           anthracnose        205        319      0.685      0.624       0.63      0.379
                 cssvd        405        571      0.794      0.667      0.731      0.485
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 0.7ms postprocess per image
Results saved to yolov11_plant_detection/yolov11s_map50_focused
Training completed. Best model saved based on mAP50.

In [35]:
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import MaxNLocator
from pathlib import Path

def plot_yolo_performance(results_dir, save_plots=False, output_dir='performance_plots', focus_metric='mAP50'):
    """
    Generate comprehensive performance plots for YOLOv11 training results,
    with special focus on mAP@0.5 (IoU threshold of 0.5).
    
    Args:
        results_dir: Directory containing YOLO training results
        save_plots: Whether to save plots to disk (False by default)
        output_dir: Directory to save performance plots (only used if save_plots=True)
        focus_metric: Primary metric to highlight in plots ('mAP50' by default)
    """
    # Create output directory if saving plots
    if save_plots:
        os.makedirs(output_dir, exist_ok=True)
    
    # Check if it's Ultralytics format (YOLOv8/YOLOv11) or older YOLOv5 format
    results_csv = os.path.join(results_dir, 'results.csv')
    
    if os.path.exists(results_csv):
        # Newer Ultralytics format
        df = pd.read_csv(results_csv)
        
        # Check if we have precision-recall data
        if all(col in df.columns for col in ['precision', 'recall', 'mAP50', 'mAP50-95']):
            # Create figure with multiple subplots
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            fig.suptitle('YOLO Training Performance Metrics\nPrimary Evaluation: mAP@0.5 (IoU=0.5)', fontsize=16)
            
            # Plot Loss curves
            ax = axes[0, 0]
            if 'box_loss' in df.columns and 'cls_loss' in df.columns:
                ax.plot(df['epoch'], df['box_loss'], label='Box Loss')
                ax.plot(df['epoch'], df['cls_loss'], label='Class Loss')
                if 'dfl_loss' in df.columns:  # YOLOv8/v11 specific
                    ax.plot(df['epoch'], df['dfl_loss'], label='DFL Loss')
            else:
                ax.plot(df['epoch'], df['train_loss'], label='Train Loss')
                if 'val_loss' in df.columns:
                    ax.plot(df['epoch'], df['val_loss'], label='Val Loss')
            
            ax.set_title('Training Losses')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Loss')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot Precision, Recall
            ax = axes[0, 1]
            ax.plot(df['epoch'], df['precision'], label='Precision')
            ax.plot(df['epoch'], df['recall'], label='Recall')
            ax.set_title('Precision and Recall (at IoU=0.5)')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Value')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot mAP values with mAP@0.5 highlighted
            ax = axes[1, 0]
            # Plot mAP@0.5 with thicker line and different color
            ax.plot(df['epoch'], df['mAP50'], 'r-', linewidth=3, label='mAP@0.5 (Primary Metric)')
            ax.plot(df['epoch'], df['mAP50-95'], 'b-', linewidth=1.5, label='mAP@0.5:0.95')
            ax.set_title('Mean Average Precision (mAP)')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('mAP')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Add a horizontal line at the best mAP@0.5 value
            best_map50 = df['mAP50'].max()
            best_epoch = df.loc[df['mAP50'].idxmax(), 'epoch']
            ax.axhline(y=best_map50, color='r', linestyle='--', alpha=0.5)
            ax.axvline(x=best_epoch, color='r', linestyle='--', alpha=0.5)
            ax.annotate(f'Best mAP@0.5: {best_map50:.4f} (Epoch {best_epoch:.0f})', 
                        xy=(best_epoch, best_map50),
                        xytext=(best_epoch+2, best_map50-0.02),
                        arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=8),
                        fontsize=9)
            
            # Plot learning rate if available, otherwise fitness
            ax = axes[1, 1]
            if 'lr0' in df.columns:
                ax.plot(df['epoch'], df['lr0'], label='Learning Rate')
                ax.set_title('Learning Rate Schedule')
                ax.set_xlabel('Epoch')
                ax.set_ylabel('Learning Rate')
                ax.legend()
                ax.grid(True, linestyle='--', alpha=0.6)
            else:
                # If learning rate is not available, plot fitness if available
                if 'fitness' in df.columns:
                    ax.plot(df['epoch'], df['fitness'], 'g-', label='Fitness')
                    ax.set_title('Model Fitness')
                    ax.set_xlabel('Epoch')
                    ax.set_ylabel('Fitness Value')
                    ax.legend()
                    ax.grid(True, linestyle='--', alpha=0.6)
                else:
                    # Create a special mAP@0.5 focus plot
                    ax.plot(df['epoch'], df['mAP50'], 'ro-')
                    ax.set_title('mAP@0.5 Progress (IoU=0.5)')
                    ax.set_xlabel('Epoch')
                    ax.set_ylabel('mAP@0.5')
                    best_map50 = df['mAP50'].max()
                    ax.axhline(y=best_map50, color='g', linestyle='--', alpha=0.5)
                    ax.text(df['epoch'].max()/2, best_map50*1.01, f'Best: {best_map50:.4f}', 
                            horizontalalignment='center')
                    ax.grid(True, linestyle='--', alpha=0.6)
            
            # Adjust layout
            plt.tight_layout(rect=[0, 0, 1, 0.95])  # Adjust for main title
            
            # Save or display
            if save_plots:
                plt.savefig(os.path.join(output_dir, 'training_metrics.png'), dpi=300)
                plt.close()
            else:
                plt.show()
            
            # Create a dedicated mAP@0.5 (IoU=0.5) plot
            plt.figure(figsize=(10, 6))
            plt.plot(df['epoch'], df['mAP50'], 'ro-', linewidth=2)
            plt.title('mAP@0.5 (IoU=0.5) Training Progress', fontsize=14)
            plt.xlabel('Epoch')
            plt.ylabel('mAP@0.5')
            plt.grid(True, linestyle='--', alpha=0.6)
            
            # Add rolling average to smooth the curve
            window_size = min(5, len(df))
            if window_size > 1:
                rolling_avg = df['mAP50'].rolling(window=window_size).mean()
                plt.plot(df['epoch'][window_size-1:], rolling_avg[window_size-1:], 'b-', 
                         linewidth=1.5, label=f'{window_size}-epoch Moving Average')
            
            # Add best point annotation
            plt.axhline(y=best_map50, color='g', linestyle='--', alpha=0.5)
            plt.axvline(x=best_epoch, color='g', linestyle='--', alpha=0.5)
            plt.annotate(f'Best mAP@0.5: {best_map50:.4f} (Epoch {best_epoch:.0f})', 
                        xy=(best_epoch, best_map50),
                        xytext=(best_epoch*(0.9 if best_epoch > df['epoch'].max()/2 else 1.1), 
                                best_map50*(0.95 if best_map50 > df['mAP50'].median() else 1.05)),
                        arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=5),
                        fontsize=10)
            
            plt.legend()
            plt.tight_layout()
            
            if save_plots:
                plt.savefig(os.path.join(output_dir, 'map50_progress.png'), dpi=300)
                plt.close()
            else:
                plt.show()
            
            # Create PR curve plot if we have confidence data
            pr_curve_file = Path(results_dir) / 'PR_curve.png'
            if pr_curve_file.exists():
                pr_img = plt.imread(pr_curve_file)
                plt.figure(figsize=(10, 8))
                plt.imshow(pr_img)
                plt.axis('off')
                plt.title('Precision-Recall Curve (IoU=0.5)', fontsize=14)
                plt.tight_layout()
                
                if save_plots:
                    plt.savefig(os.path.join(output_dir, 'pr_curve.png'), dpi=300)
                    plt.close()
                else:
                    plt.show()
            
            # Create F1 score vs confidence threshold plot if available
            f1_curve_file = Path(results_dir) / 'F1_curve.png'
            if f1_curve_file.exists():
                f1_img = plt.imread(f1_curve_file)
                plt.figure(figsize=(10, 8))
                plt.imshow(f1_img)
                plt.axis('off')
                plt.title('F1 Score vs Confidence Threshold (IoU=0.5)', fontsize=14)
                plt.tight_layout()
                
                if save_plots:
                    plt.savefig(os.path.join(output_dir, 'f1_curve.png'), dpi=300)
                    plt.close()
                else:
                    plt.show()
            
            # Print final metrics with highlight on mAP@0.5
            final_epoch = df.iloc[-1]
            print("\n" + "="*50)
            print("FINAL TRAINING METRICS")
            print("="*50)
            print(f"Precision (IoU=0.5): {final_epoch['precision']:.4f}")
            print(f"Recall (IoU=0.5): {final_epoch['recall']:.4f}")
            print(f"→ mAP@0.5 (IoU=0.5): {final_epoch['mAP50']:.4f} ←")
            print(f"mAP@0.5:0.95: {final_epoch['mAP50-95']:.4f}")
            print(f"Best mAP@0.5: {best_map50:.4f} (Epoch {best_epoch:.0f})")
            print("="*50)
            
            return {
                'precision': final_epoch['precision'],
                'recall': final_epoch['recall'],
                'mAP50': final_epoch['mAP50'],
                'mAP50-95': final_epoch['mAP50-95'],
                'best_mAP50': best_map50,
                'best_epoch': best_epoch
            }
        else:
            print("Warning: CSV file does not contain expected metrics columns.")
    
    # Check for older YOLOv5 format results.txt
    results_txt = os.path.join(results_dir, 'results.txt')
    if os.path.exists(results_txt):
        # Parse results.txt in YOLOv5 format
        epochs, box_loss, obj_loss, cls_loss = [], [], [], []
        precision, recall, map50, map = [], [], [], []
        
        with open(results_txt, 'r') as f:
            for line in f:
                if line.startswith('  Epoch'):
                    continue  # Skip header line
                try:
                    # Extract metrics (format may vary)
                    parts = line.strip().split()
                    if len(parts) >= 12:
                        epoch = int(parts[0])
                        epochs.append(epoch)
                        
                        # Extract losses
                        box_loss.append(float(parts[2]))
                        obj_loss.append(float(parts[3]))
                        cls_loss.append(float(parts[4]))
                        
                        # Extract precision, recall, mAP
                        precision.append(float(parts[8]))
                        recall.append(float(parts[9]))
                        map50.append(float(parts[10]))
                        map.append(float(parts[11]))
                except Exception as e:
                    print(f"Error parsing line: {line}")
                    print(f"Exception: {e}")
        
        if epochs:
            # Create figure with multiple subplots
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            fig.suptitle('YOLO Training Performance Metrics\nPrimary Evaluation: mAP@0.5 (IoU=0.5)', fontsize=16)
            
            # Plot Loss curves
            ax = axes[0, 0]
            ax.plot(epochs, box_loss, label='Box Loss')
            ax.plot(epochs, obj_loss, label='Objectness Loss')
            ax.plot(epochs, cls_loss, label='Class Loss')
            ax.set_title('Training Losses')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Loss')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot Precision, Recall
            ax = axes[0, 1]
            ax.plot(epochs, precision, label='Precision')
            ax.plot(epochs, recall, label='Recall')
            ax.set_title('Precision and Recall (at IoU=0.5)')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Value')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot mAP values with mAP@0.5 highlighted
            ax = axes[1, 0]
            # Plot mAP@0.5 with thicker line and different color
            ax.plot(epochs, map50, 'r-', linewidth=3, label='mAP@0.5 (Primary Metric)')
            ax.plot(epochs, map, 'b-', linewidth=1.5, label='mAP@0.5:0.95')
            ax.set_title('Mean Average Precision (mAP)')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('mAP')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Add a horizontal line at the best mAP@0.5 value
            best_map50 = max(map50)
            best_epoch_idx = map50.index(best_map50)
            best_epoch = epochs[best_epoch_idx]
            ax.axhline(y=best_map50, color='r', linestyle='--', alpha=0.5)
            ax.axvline(x=best_epoch, color='r', linestyle='--', alpha=0.5)
            ax.annotate(f'Best mAP@0.5: {best_map50:.4f} (Epoch {best_epoch})', 
                        xy=(best_epoch, best_map50),
                        xytext=(best_epoch+2, best_map50-0.02),
                        arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=8),
                        fontsize=9)
            
            # Plot combined loss
            ax = axes[1, 1]
            total_loss = [b + o + c for b, o, c in zip(box_loss, obj_loss, cls_loss)]
            ax.plot(epochs, total_loss, label='Total Loss')
            ax.set_title('Total Training Loss')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Loss')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Adjust layout
            plt.tight_layout(rect=[0, 0, 1, 0.95])  # Adjust for main title
            
            if save_plots:
                plt.savefig(os.path.join(output_dir, 'training_metrics.png'), dpi=300)
                plt.close()
            else:
                plt.show()
            
            # Create a dedicated mAP@0.5 (IoU=0.5) plot
            plt.figure(figsize=(10, 6))
            plt.plot(epochs, map50, 'ro-', linewidth=2)
            plt.title('mAP@0.5 (IoU=0.5) Training Progress', fontsize=14)
            plt.xlabel('Epoch')
            plt.ylabel('mAP@0.5')
            plt.grid(True, linestyle='--', alpha=0.6)
            
            # Add rolling average to smooth the curve if we have enough data points
            window_size = min(5, len(epochs))
            if window_size > 1:
                # Calculate rolling average manually
                rolling_avg = []
                for i in range(window_size-1, len(map50)):
                    avg = sum(map50[i-(window_size-1):i+1]) / window_size
                    rolling_avg.append(avg)
                
                # Plot rolling average
                plt.plot(epochs[window_size-1:], rolling_avg, 'b-', 
                         linewidth=1.5, label=f'{window_size}-epoch Moving Average')
            
            # Add best point annotation
            plt.axhline(y=best_map50, color='g', linestyle='--', alpha=0.5)
            plt.axvline(x=best_epoch, color='g', linestyle='--', alpha=0.5)
            plt.annotate(f'Best mAP@0.5: {best_map50:.4f} (Epoch {best_epoch})', 
                        xy=(best_epoch, best_map50),
                        xytext=(best_epoch*(0.9 if best_epoch > epochs[-1]/2 else 1.1), 
                                best_map50*(0.95 if best_map50 > sum(map50)/len(map50) else 1.05)),
                        arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=5),
                        fontsize=10)
            
            plt.legend()
            plt.tight_layout()
            
            if save_plots:
                plt.savefig(os.path.join(output_dir, 'map50_progress.png'), dpi=300)
                plt.close()
            else:
                plt.show()
            
            # Print final metrics with highlight on mAP@0.5
            print("\n" + "="*50)
            print("FINAL TRAINING METRICS")
            print("="*50)
            print(f"Precision (IoU=0.5): {precision[-1]:.4f}")
            print(f"Recall (IoU=0.5): {recall[-1]:.4f}")
            print(f"→ mAP@0.5 (IoU=0.5): {map50[-1]:.4f} ←")
            print(f"mAP@0.5:0.95: {map[-1]:.4f}")
            print(f"Best mAP@0.5: {best_map50:.4f} (Epoch {best_epoch})")
            print("="*50)
            
            return {
                'precision': precision[-1],
                'recall': recall[-1],
                'mAP50': map50[-1],
                'mAP50-95': map[-1],
                'best_mAP50': best_map50,
                'best_epoch': best_epoch
            }

In [36]:
os.path.join(os.getcwd(), 'yolo_results')

'/home/jason-server/Documents/amini_cocoa_contamination/yolo_results'

In [37]:
plot_yolo_performance(os.path.join(os.getcwd(), 'yolo_results'), output_dir='performance_plots')

In [38]:
test_image_dir = os.path.join(os.getcwd(), 'dataset', 'images', 'test')
model_path = os.path.join(os.getcwd(), 'yolov11_plant_detection', 'yolov11s_map50_focused', 'weights', 'best.pt') 
# Run inference on test images
run_inference(model_path, test_image_dir=test_image_dir)

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

image 1/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_A16nzu.jpg: 640x480 1 healthy, 59.7ms
image 2/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_A1Euyz.jpg: 640x480 2 anthracnoses, 7.0ms
image 3/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_A1HcV0.jpeg: 640x480 1 healthy, 1 anthracnose, 6.9ms
image 4/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_A4ZdJC.jpeg: 640x480 1 healthy, 7.3ms
image 5/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_A5SFUW.jpeg: 640x480 1 healthy, 7.6ms
image 6/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_A6Fogi.jpeg: 640x288 1 anthracnose, 70.9ms
image 7/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ABDCyn.jpeg: 640x480 1 healthy, 7.7ms
image 8/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ACg6Qf.jpeg: 640x288 1 anthracnose, 8.1ms
image 9/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AFi8A1.jpg: 640x480 5 healthys, 7.8ms
image 10/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AHlc9P.jpg: 640x480 1 healthy, 7.6ms
image 11/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AKu1Rh.jpeg: 480x640 2 cssvds, 14.8ms
image 12/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AQc6Fa.jpeg: 640x480 (no detections), 7.6ms
image 13/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ARfduS.jpg: 640x480 4 healthys, 7.3ms
image 14/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AUiVHv.jpeg: 640x480 1 healthy, 1 anthracnose, 7.5ms
image 15/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AVXfJI.jpg: 640x480 1 cssvd, 8.8ms
image 16/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AWsPwc.jpg: 640x480 2 healthys, 7.8ms
image 17/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AX61Qc.jpg: 480x640 1 cssvd, 8.0ms
image 18/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AXba1J.jpg: 640x480 1 cssvd, 7.1ms
image 19/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AZMNHM.jpeg: 640x480 1 healthy, 1 cssvd, 6.9ms
image 20/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AaL0uh.jpeg: 640x480 1 healthy, 7.6ms
image 21/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AcCl43.jpg: 640x480 2 cssvds, 7.2ms
image 22/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AhZ64h.jpeg: 480x640 2 cssvds, 7.2ms
image 23/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AopVga.jpg: 640x640 3 healthys, 7.5ms
image 24/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AqSCmf.jpeg: 640x480 1 anthracnose, 7.6ms
image 25/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AuxMUi.jpeg: 640x480 1 healthy, 7.0ms
image 26/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AvhFY7.jpg: 640x480 1 anthracnose, 6.6ms
image 27/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AwZkd2.jpg: 640x480 2 anthracnoses, 7.0ms
image 28/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AweW1B.jpg: 640x480 1 anthracnose, 7.3ms
image 29/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_AypcIr.jpeg: 640x288 1 healthy, 7.4ms
image 30/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Az60r3.jpg: 640x480 1 cssvd, 7.6ms
image 31/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_B4zGjd.jpg: 640x480 1 cssvd, 6.6ms
image 32/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_B6Bi68.jpg: 640x640 5 healthys, 7.5ms
image 33/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_B9DYFf.jpg: 640x480 2 cssvds, 7.4ms
image 34/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BAszkB.jpeg: 640x480 2 healthys, 6.8ms
image 35/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BB69K4.jpg: 640x480 2 anthracnoses, 6.7ms
image 36/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BBmctK.jpeg: 480x640 3 healthys, 7.1ms
image 37/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BKGaS6.jpeg: 640x480 5 healthys, 6.9ms
image 38/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BMHFpr.jpeg: 640x480 1 healthy, 6.7ms
image 39/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BMR78x.jpg: 640x480 2 healthys, 6.7ms
image 40/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BPRGb0.jpg: 640x480 1 cssvd, 7.1ms
image 41/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BWl0VT.jpg: 640x640 2 healthys, 7.0ms
image 42/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BWoPJE.jpg: 640x480 1 anthracnose, 6.9ms
image 43/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BaQafS.jpeg: 640x480 (no detections), 6.7ms
image 44/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BbUwow.jpg: 640x480 2 cssvds, 6.6ms
image 45/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BbuHsd.jpeg: 640x480 1 anthracnose, 7.0ms
image 46/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BcNWAl.jpeg: 640x480 1 cssvd, 7.3ms
image 47/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Be0vKo.jpg: 640x480 2 anthracnoses, 9.5ms
image 48/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BhKgBW.jpg: 640x480 2 cssvds, 7.3ms
image 49/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BhOD7h.jpg: 640x480 2 cssvds, 6.9ms
image 50/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BiL2B8.jpeg: 640x288 2 healthys, 8.5ms
image 51/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BkHj0e.jpg: 640x480 1 anthracnose, 1 cssvd, 8.6ms
image 52/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ByeZGA.jpg: 640x480 1 healthy, 2 cssvds, 8.1ms
image 53/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Byn4Lt.JPG: 640x480 3 healthys, 6.8ms
image 54/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_C0Cmx7.jpg: 640x480 2 anthracnoses, 1 cssvd, 6.6ms
image 55/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_C0Uehq.jpg: 640x480 2 cssvds, 7.1ms
image 56/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_C1vtA9.jpg: 640x480 1 cssvd, 6.7ms
image 57/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_C3AIRq.jpg: 640x480 1 cssvd, 7.0ms
image 58/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_C8BlN8.jpg: 640x480 1 cssvd, 7.0ms
image 59/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CBUJ2U.jpg: 640x480 2 cssvds, 7.0ms
image 60/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CBkuOC.jpg: 640x480 1 cssvd, 7.0ms
image 61/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CBsr8I.jpg: 640x480 1 cssvd, 6.7ms
image 62/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CE3bfu.jpeg: 640x480 1 anthracnose, 7.1ms
image 63/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CEnc58.jpeg: 640x480 (no detections), 7.0ms
image 64/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CGnAYP.jpg: 640x480 2 cssvds, 6.9ms
image 65/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CP7YI8.jpg: 640x480 1 cssvd, 7.0ms
image 66/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CRgjeZ.jpg: 640x480 1 healthy, 7.5ms
image 67/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CTHVbX.jpg: 640x480 1 cssvd, 7.1ms
image 68/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CTJaUE.jpg: 640x480 (no detections), 6.7ms
image 69/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CUByHJ.jpg: 640x640 1 healthy, 7.2ms
image 70/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CWDQS2.jpeg: 288x640 1 healthy, 1 anthracnose, 64.8ms
image 71/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Cc4hHM.jpg: 640x384 1 cssvd, 63.5ms
image 72/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CcIssk.jpg: 640x480 1 healthy, 1 anthracnose, 7.1ms
image 73/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Ccy5YA.jpeg: 640x480 2 anthracnoses, 7.2ms
image 74/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CiaBXB.jpg: 640x640 1 healthy, 7.6ms
image 75/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Cisrab.jpeg: 640x480 1 anthracnose, 7.4ms
image 76/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Cj1prl.jpg: 640x480 1 cssvd, 6.9ms
image 77/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CjxpRk.JPG: 640x480 1 anthracnose, 7.2ms
image 78/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CkzYK9.jpg: 640x480 1 anthracnose, 1 cssvd, 6.9ms
image 79/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Cm5njC.jpg: 640x480 1 cssvd, 7.0ms
image 80/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CqDi1f.jpg: 480x640 1 anthracnose, 1 cssvd, 8.1ms
image 81/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CrSUii.jpeg: 640x480 1 anthracnose, 7.5ms
image 82/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CsD8EL.jpg: 640x480 2 anthracnoses, 7.1ms
image 83/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CuBkOO.jpg: 640x640 2 healthys, 7.6ms
image 84/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Cw5fwO.jpg: 480x640 1 anthracnose, 7.4ms
image 85/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Cy2zVL.jpg: 640x480 2 cssvds, 7.1ms
image 86/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CzSEcr.jpg: 640x640 4 healthys, 9.1ms
image 87/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_D1Efw8.jpg: 640x480 2 cssvds, 7.2ms
image 88/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_D2n955.jpg: 640x480 1 cssvd, 6.9ms
image 89/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_D57TlR.jpeg: 640x480 (no detections), 6.5ms
image 90/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_D7howW.jpg: 640x480 1 cssvd, 7.4ms
image 91/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_D99Mnd.jpg: 640x480 1 healthy, 2 cssvds, 6.6ms
image 92/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DCnllR.jpg: 640x640 4 healthys, 6.9ms
image 93/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DFyyru.jpg: 640x480 1 cssvd, 7.5ms
image 94/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DHCirx.jpg: 640x480 1 anthracnose, 7.1ms
image 95/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DJdr6B.jpg: 640x480 1 cssvd, 6.6ms
image 96/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DLYLty.jpg: 640x480 2 cssvds, 7.0ms
image 97/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DQIbC9.jpeg: 640x288 1 healthy, 1 anthracnose, 7.7ms
image 98/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DWOFob.jpg: 640x480 1 anthracnose, 7.5ms
image 99/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DbrLAf.jpeg: 640x480 1 healthy, 1 cssvd, 7.2ms
image 100/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DcMUYA.jpg: 640x480 2 healthys, 7.1ms
image 101/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DdPn6R.jpg: 640x480 1 anthracnose, 6.7ms
image 102/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Dh68Pg.jpeg: 640x480 3 healthys, 6.7ms
image 103/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DitJb1.jpeg: 640x640 2 anthracnoses, 7.0ms
image 104/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DjtECY.jpeg: 640x288 (no detections), 8.2ms
image 105/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DldPpd.jpeg: 640x480 1 anthracnose, 7.3ms
image 106/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DorYRG.jpg: 640x480 2 anthracnoses, 7.5ms
image 107/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Dt9R4S.jpg: 640x480 1 healthy, 7.3ms
image 108/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DtvCD1.jpeg: 640x480 1 healthy, 6.9ms
image 109/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Dw2paJ.jpg: 640x480 1 cssvd, 8.3ms
image 110/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DxuEWw.jpg: 640x640 2 healthys, 7.8ms
image 111/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DyHG2r.jpg: 480x640 1 cssvd, 7.7ms
image 112/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Dz7nGM.jpeg: 640x480 1 healthy, 7.8ms
image 113/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DzdeNP.jpg: 640x640 1 healthy, 7.7ms
image 114/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_E1lv1B.jpg: 640x480 2 cssvds, 7.8ms
image 115/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_E27ZzV.jpg: 640x480 3 anthracnoses, 7.0ms
image 116/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_E5U3se.jpeg: 640x480 2 healthys, 7.0ms
image 117/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_E5kGYT.jpeg: 480x640 1 healthy, 1 anthracnose, 9.3ms
image 118/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_E7haV4.jpeg: 640x480 1 cssvd, 10.9ms
image 119/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_E9zHw7.jpg: 640x640 3 healthys, 8.0ms
image 120/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EBhZzJ.jpeg: 640x640 1 anthracnose, 6.8ms
image 121/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EDbrKH.jpg: 640x480 1 healthy, 1 cssvd, 7.4ms
image 122/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EFetFh.jpg: 480x640 1 healthy, 1 cssvd, 7.3ms
image 123/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EG9Mkf.jpg: 640x480 1 healthy, 7.4ms
image 124/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EGzXyJ.jpg: 640x480 1 anthracnose, 7.5ms
image 125/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EJgRE4.jpg: 640x640 2 healthys, 7.2ms
image 126/1626 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EOFmpE.jpeg: 640x288 1 anthracnose, 7.5ms

KeyboardInterrupt:

In [39]:
from ultralytics import YOLO
from tqdm.notebook import tqdm
model_path = os.path.join(os.getcwd(), 'yolov11_plant_detection', 'yolov11s_map50_focused', 'weights', 'best.pt') 

# Load the trained YOLO model
model = YOLO(model_path)

# Path to the test images directory
test_dir_path = TEST_IMAGES_DIR

# Get a list of all image files in the test directory
image_files = os.listdir(test_dir_path)

# Initialize an empty list to store the results for all images
all_data = []

# Initialize an empty list to store the results for all images
all_data = []

# Iterate through each image in the directory
for image_file in tqdm(image_files):
    # Full path to the image
    img_path = os.path.join(test_dir_path, image_file)

    # Make predictions on the image
    results = model(img_path)

    # Extract bounding boxes, confidence scores, and class labels
    boxes = results[0].boxes.xyxy.tolist() if results[0].boxes else []  # Bounding boxes in xyxy format
    classes = results[0].boxes.cls.tolist() if results[0].boxes else []  # Class indices
    confidences = results[0].boxes.conf.tolist() if results[0].boxes else []  # Confidence scores
    names = results[0].names  # Class names dictionary

    if boxes:  # If detections are found
        for box, cls, conf in zip(boxes, classes, confidences):
            x1, y1, x2, y2 = box
            detected_class = names[int(cls)]  # Get the class name from the names dictionary

            # Add the result to the all_data list
            all_data.append({
                'Image_ID': str(image_file),
                'class': detected_class,
                'confidence': conf,
                'ymin': y1,
                'xmin': x1,
                'ymax': y2,
                'xmax': x2
            })
    else:  # If no objects are detected
        all_data.append({
            'Image_ID': str(image_file),
            'class': "None",
            'confidence': None,
            'ymin': None,
            'xmin': None,
            'ymax': None,
            'xmax': None
        })

# Convert the list to a DataFrame for all images
sub = pd.DataFrame(all_data)

# Create submission file to be uploaded to Zindi for scoring
sub.to_csv(f'{INPUT_DATA_DIR / "YOLO_100epochs_BenchmarkSubmission_run14.csv"}', index = False)

  0%|          | 0/1626 [00:00<?, ?it/s]

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_zSiC0w.jpg: 640x480 1 healthy, 1 anthracnose, 7.6ms
Speed: 2.6ms preprocess, 7.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_kvMeX2.JPG: 640x480 (no detections), 7.0ms
Speed: 2.5ms preprocess, 7.0ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EBhZzJ.jpeg: 640x640 1 anthracnose, 7.1ms
Speed: 3.2ms preprocess, 7.1ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_p4aJv5.jpg: 640x480 1 cssvd, 7.6ms
Speed: 1.8ms preprocess, 7.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Vq59xO.jpg: 640x480 2 anthracnoses, 6.7ms
Speed: 2.8ms preprocess, 6.7ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_lJqimA.jpg: 640x480 1 cssvd, 6.8ms
Speed: 1.5ms preprocess, 6.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_IQXVr3.jpg: 640x640 3 healthys, 7.3ms
Speed: 1.9ms preprocess, 7.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_W4b7ZX.jpg: 640x480 (no detections), 7.7ms
Speed: 2.6ms preprocess, 7.7ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_xXWJsa.jpg: 640x480 1 healthy, 1 cssvd, 6.7ms
Speed: 2.8ms preprocess, 6.7ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_rMv7Zl.jpg: 640x480 1 cssvd, 8.0ms
Speed: 1.6ms preprocess, 8.0ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_vSr6vC.jpg: 640x480 5 anthracnoses, 7.6ms
Speed: 2.9ms preprocess, 7.6ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_tBKR7L.jpeg: 640x288 2 healthys, 7.2ms
Speed: 2.6ms preprocess, 7.2ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 288)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_iXRhGf.jpeg: 640x480 (no detections), 7.2ms
Speed: 2.6ms preprocess, 7.2ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_TNiZUE.jpg: 640x480 1 cssvd, 7.2ms
Speed: 1.6ms preprocess, 7.2ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_yZYd0h.jpg: 640x480 1 cssvd, 7.1ms
Speed: 1.6ms preprocess, 7.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_rduPKu.jpg: 640x480 1 healthy, 1 anthracnose, 6.7ms
Speed: 2.3ms preprocess, 6.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_RirekC.jpg: 640x384 3 cssvds, 7.6ms
Speed: 1.8ms preprocess, 7.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 384)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_vqs2Dt.jpeg: 640x480 1 healthy, 7.5ms
Speed: 2.6ms preprocess, 7.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BhKgBW.jpg: 640x480 2 cssvds, 6.9ms
Speed: 1.7ms preprocess, 6.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_tuijN0.jpg: 480x640 2 healthys, 7.6ms
Speed: 2.6ms preprocess, 7.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_eKtHoY.jpeg: 640x480 2 healthys, 7.2ms
Speed: 2.6ms preprocess, 7.2ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_kWKsnF.jpg: 640x480 2 cssvds, 6.9ms
Speed: 2.8ms preprocess, 6.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ZYbA7d.jpg: 640x480 1 anthracnose, 7.2ms
Speed: 2.3ms preprocess, 7.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Suoisd.JPG: 640x480 2 healthys, 7.0ms
Speed: 2.5ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_zbueIx.jpeg: 640x480 2 healthys, 1 anthracnose, 7.0ms
Speed: 2.5ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Az60r3.jpg: 640x480 1 cssvd, 7.2ms
Speed: 1.7ms preprocess, 7.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_kOvqJh.jpeg: 640x640 1 anthracnose, 7.1ms
Speed: 3.2ms preprocess, 7.1ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_CiaBXB.jpg: 640x640 1 healthy, 6.3ms
Speed: 2.0ms preprocess, 6.3ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_YGGSTX.jpg: 480x640 2 healthys, 9.3ms
Speed: 2.8ms preprocess, 9.3ms inference, 1.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_SXgYVp.jpg: 640x480 1 healthy, 7.8ms
Speed: 2.6ms preprocess, 7.8ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_NOFmdO.jpg: 640x480 1 anthracnose, 7.0ms
Speed: 2.3ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_a0srv9.jpg: 480x640 (no detections), 7.3ms
Speed: 2.5ms preprocess, 7.3ms inference, 0.6ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_nSawWh.jpg: 640x480 1 anthracnose, 7.5ms
Speed: 2.6ms preprocess, 7.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_aatE8l.jpeg: 640x480 1 healthy, 14.7ms
Speed: 2.7ms preprocess, 14.7ms inference, 1.7ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_gvnAED.jpg: 640x480 1 cssvd, 7.3ms
Speed: 1.8ms preprocess, 7.3ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_uxGyKi.jpg: 640x480 1 healthy, 1 cssvd, 7.0ms
Speed: 2.6ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_YATAta.jpeg: 640x480 2 healthys, 6.9ms
Speed: 2.7ms preprocess, 6.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_p6OqyL.jpg: 640x480 1 cssvd, 7.0ms
Speed: 1.6ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BWoPJE.jpg: 640x480 1 anthracnose, 7.6ms
Speed: 4.4ms preprocess, 7.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_BbUwow.jpg: 640x480 2 cssvds, 6.6ms
Speed: 2.5ms preprocess, 6.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_tvu9FP.jpg: 640x480 1 cssvd, 6.9ms
Speed: 1.6ms preprocess, 6.9ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_XEbuST.jpg: 640x480 1 anthracnose, 7.1ms
Speed: 2.7ms preprocess, 7.1ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_rO21Rv.jpg: 640x480 1 cssvd, 7.1ms
Speed: 1.8ms preprocess, 7.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_wB12vR.jpg: 640x480 1 cssvd, 7.2ms
Speed: 1.5ms preprocess, 7.2ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_NbJj7a.jpg: 480x640 1 cssvd, 7.9ms
Speed: 2.6ms preprocess, 7.9ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_t0kbuH.jpg: 640x480 2 healthys, 7.9ms
Speed: 1.8ms preprocess, 7.9ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_iafMXS.jpg: 640x480 1 cssvd, 7.2ms
Speed: 2.6ms preprocess, 7.2ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_deS0wq.jpg: 640x480 2 cssvds, 7.1ms
Speed: 2.7ms preprocess, 7.1ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_L9vR9c.jpeg: 480x640 4 healthys, 7.4ms
Speed: 2.7ms preprocess, 7.4ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_dlFmzD.jpeg: 640x288 2 healthys, 7.7ms
Speed: 2.2ms preprocess, 7.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 288)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_XlQcW0.JPG: 640x480 1 healthy, 8.1ms
Speed: 2.5ms preprocess, 8.1ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ExXVO1.jpg: 640x480 2 cssvds, 7.0ms
Speed: 3.3ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_PDuPIE.jpeg: 640x480 4 healthys, 7.6ms
Speed: 2.6ms preprocess, 7.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_rry4FO.JPG: 640x480 7 healthys, 6.9ms
Speed: 2.6ms preprocess, 6.9ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ZGTOCS.jpg: 640x640 8 healthys, 8.1ms
Speed: 1.9ms preprocess, 8.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_rSmGHZ.jpg: 640x480 (no detections), 12.8ms
Speed: 2.6ms preprocess, 12.8ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_rANrt1.jpeg: 640x480 1 healthy, 7.1ms
Speed: 2.7ms preprocess, 7.1ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_eKexBX.JPG: 640x480 2 healthys, 6.7ms
Speed: 2.6ms preprocess, 6.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_wKhaSp.jpg: 640x480 4 healthys, 7.0ms
Speed: 2.1ms preprocess, 7.0ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Vbc7tX.JPG: 640x480 (no detections), 7.5ms
Speed: 2.5ms preprocess, 7.5ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Tm3kkv.jpeg: 640x480 1 healthy, 7.8ms
Speed: 2.6ms preprocess, 7.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_EdzwdN.jpg: 640x480 3 anthracnoses, 7.7ms
Speed: 2.7ms preprocess, 7.7ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_NnZXiB.jpg: 640x480 1 cssvd, 7.5ms
Speed: 1.5ms preprocess, 7.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_XxYDsU.jpg: 480x640 1 cssvd, 7.8ms
Speed: 1.7ms preprocess, 7.8ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DldPpd.jpeg: 640x480 2 anthracnoses, 7.4ms
Speed: 2.7ms preprocess, 7.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_TAZIJ7.jpeg: 480x640 4 healthys, 7.5ms
Speed: 2.6ms preprocess, 7.5ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_bWrGAE.JPG: 640x480 1 healthy, 1 cssvd, 7.5ms
Speed: 2.4ms preprocess, 7.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_Gbv0j3.jpg: 640x480 1 cssvd, 7.2ms
Speed: 2.7ms preprocess, 7.2ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_kjTAmo.jpg: 640x480 3 cssvds, 7.3ms
Speed: 2.3ms preprocess, 7.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_OKnByL.jpg: 640x480 2 anthracnoses, 6.8ms
Speed: 2.7ms preprocess, 6.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_jc8o9w.jpg: 640x480 1 cssvd, 7.1ms
Speed: 1.8ms preprocess, 7.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_p9vAO2.jpg: 480x640 1 cssvd, 7.6ms
Speed: 1.7ms preprocess, 7.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_DFyyru.jpg: 640x480 1 cssvd, 7.7ms
Speed: 2.6ms preprocess, 7.7ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_d6gpj1.jpg: 640x480 1 cssvd, 7.1ms
Speed: 1.9ms preprocess, 7.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_tTFNac.jpg: 640x480 2 anthracnoses, 7.7ms
Speed: 1.6ms preprocess, 7.7ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_VzT72C.jpeg: 640x640 1 cssvd, 7.2ms
Speed: 3.2ms preprocess, 7.2ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_C8BlN8.jpg: 640x480 1 cssvd, 7.6ms
Speed: 2.5ms preprocess, 7.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_ORZ9Bi.jpg: 640x640 3 healthys, 7.0ms
Speed: 1.9ms preprocess, 7.0ms inference, 1.5ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_nnRffu.jpg: 640x480 2 anthracnoses, 8.3ms
Speed: 2.3ms preprocess, 8.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_db9KWW.jpg: 640x480 1 anthracnose, 7.2ms
Speed: 1.6ms preprocess, 7.2ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_s9aN3f.jpg: 480x640 3 cssvds, 7.6ms
Speed: 2.8ms preprocess, 7.6ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_P8IJWT.jpg: 640x480 1 cssvd, 7.7ms
Speed: 1.7ms preprocess, 7.7ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_h2CK7l.jpeg: 480x640 1 healthy, 7.7ms
Speed: 2.8ms preprocess, 7.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_VHvV8H.jpg: 640x480 2 cssvds, 7.8ms
Speed: 2.4ms preprocess, 7.8ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_nu8inE.jpg: 640x480 1 cssvd, 7.3ms
Speed: 1.6ms preprocess, 7.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_bwH4Zt.jpg: 640x480 2 anthracnoses, 7.0ms
Speed: 2.3ms preprocess, 7.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_MdOA7y.jpg: 640x480 1 cssvd, 7.1ms
Speed: 2.3ms preprocess, 7.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_cb1Wwh.jpg: 640x480 1 cssvd, 6.8ms
Speed: 2.5ms preprocess, 6.8ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/amini_cocoa_contamination/dataset/images/test/ID_OyJQFx.jpg: 640x480 1 cssvd, 7.2ms
Speed: 1.7ms preprocess, 7.2ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)


In [40]:
sub

,Image_ID,class,confidence,ymin,xmin,ymax,xmax
0,ID_zSiC0w.jpg,healthy,0.738884,985.388550,541.326965,2929.503906,1659.822388
1,ID_zSiC0w.jpg,anthracnose,0.487250,949.585510,1356.254761,1730.766357,2448.000000
2,ID_kvMeX2.JPG,None,NaN,NaN,NaN,NaN,NaN
3,ID_EBhZzJ.jpeg,anthracnose,0.765557,33.015591,325.651093,3013.001953,2218.636963
4,ID_p4aJv5.jpg,cssvd,0.904809,235.863342,0.352043,1052.319336,434.581512
...,...,...,...,...,...,...,...
2857,ID_GeExO3.jpeg,None,NaN,NaN,NaN,NaN,NaN
2858,ID_xjnuvj.jpg,healthy,0.798862,45.639420,103.159744,356.133820,316.373352
2859,ID_xjnuvj.jpg,healthy,0.698474,0.046417,180.462189,102.207100,413.475525
2860,ID_xjnuvj.jpg,healthy,0.257210,42.518841,1.888914,169.696335,101.950920
2861,ID_MISf6G.jpeg,anthracnose,0.291918,287.031128,638.265137,1796.280273,3193.061768

# Adding normalization

In [1]:
def train_yolov11_full_dataset(output_dir='yolo_dataset', model_name_path='yolov11s.pt',
                         model_size='s', epochs=100, batch_size=16, image_size=640, cls_gain=0.5,
                         warmup_epochs=3.0, initial_lr=0.01, pretrained=True,
                         train_val_split=0.8, random_state=42, normalize_boxes=True):
    """
    Train a YOLOv11 model on the full dataset with a single train/val split and normalized bounding boxes.
    
    Args:
        output_dir: directory containing the YOLO format dataset
        model_name_path: path to the base model
        model_size: YOLOv11 model size ('n', 's', 'm', 'l', 'x')
        epochs: number of training epochs
        batch_size: batch size
        image_size: input image size
        cls_gain: classification loss weight
        warmup_epochs: number of warmup epochs
        initial_lr: initial learning rate
        pretrained: whether to use pretrained weights
        train_val_split: ratio of data to use for training (1 - train_val_split for validation)
        random_state: random seed for reproducibility
        normalize_boxes: whether to normalize bounding boxes (0-1 scale)
        
    Returns:
        Dictionary containing training results
    """
    import os
    import shutil
    import yaml
    import json
    import numpy as np
    from datetime import datetime
    from sklearn.model_selection import train_test_split
    from ultralytics import YOLO
    
    print(f"\n{'='*50}")
    print(f"Training YOLOv11 on full dataset with normalized bounding boxes")
    print(f"{'='*50}")
    
    # Create directories for train/val split
    for split in ['train', 'val']:
        for subdir in ['images', 'labels']:
            fold_dir = os.path.join(output_dir, 'full_dataset', split, subdir)
            os.makedirs(fold_dir, exist_ok=True)
    
    # Get all image filenames
    image_dir = os.path.join(output_dir, 'images')
    all_images = [f for f in os.listdir(image_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    # Split data
    train_images, val_images = train_test_split(
        all_images, 
        train_size=train_val_split, 
        random_state=random_state
    )
    
    print(f"Dataset split: {len(train_images)} training images, {len(val_images)} validation images")
    
    # Process and copy data
    for split, images in [('train', train_images), ('val', val_images)]:
        for img_file in images:
            # Get corresponding label file
            label_file = os.path.splitext(img_file)[0] + '.txt'
            
            # Copy image
            src_img = os.path.join(output_dir, 'images', img_file)
            dst_img = os.path.join(output_dir, 'full_dataset', split, 'images', img_file)
            shutil.copy(src_img, dst_img)
            
            # Process and copy label
            src_label = os.path.join(output_dir, 'labels', label_file)
            dst_label = os.path.join(output_dir, 'full_dataset', split, 'labels', label_file)
            
            if os.path.exists(src_label):
                if normalize_boxes:
                    # Read and normalize bounding boxes if needed
                    with open(src_label, 'r') as f:
                        lines = f.readlines()
                    
                    # Load corresponding image to get dimensions
                    from PIL import Image
                    img = Image.open(src_img)
                    img_width, img_height = img.size
                    
                    normalized_lines = []
                    for line in lines:
                        parts = line.strip().split()
                        if len(parts) >= 5:
                            # YOLO format: class_id center_x center_y width height
                            class_id = parts[0]
                            x_center, y_center, width, height = map(float, parts[1:5])
                            
                            # Check if already normalized (0-1)
                            if max(x_center, y_center, width, height) > 1.0:
                                # Convert absolute coordinates to normalized (0-1)
                                x_center /= img_width
                                y_center /= img_height
                                width /= img_width
                                height /= img_height
                            
                            normalized_line = f"{class_id} {x_center} {y_center} {width} {height}"
                            if len(parts) > 5:  # Preserve additional attributes if any
                                normalized_line += " " + " ".join(parts[5:])
                            normalized_lines.append(normalized_line + "\n")
                    
                    # Write normalized labels
                    with open(dst_label, 'w') as f:
                        f.writelines(normalized_lines)
                else:
                    # Just copy the label file as is
                    shutil.copy(src_label, dst_label)
    
    # Get class names
    classes_path = os.path.join(output_dir, 'classes.txt')
    if os.path.exists(classes_path):
        with open(classes_path, 'r') as f:
            classes = [line.strip() for line in f.readlines()]
    else:
        # Try to infer class count from labels
        class_ids = set()
        labels_dir = os.path.join(output_dir, 'labels')
        for label_file in os.listdir(labels_dir):
            if label_file.endswith('.txt'):
                with open(os.path.join(labels_dir, label_file), 'r') as f:
                    for line in f:
                        parts = line.strip().split()
                        if parts:
                            class_ids.add(int(parts[0]))
        
        # Create generic class names
        classes = [f"class_{i}" for i in range(max(class_ids) + 1)] if class_ids else ["object"]
    
    # Create YAML configuration
    config = {
        'path': os.path.abspath(os.path.join(output_dir, 'full_dataset')),
        'train': 'train/images',
        'val': 'val/images',
        'nc': len(classes),
        'names': classes
    }
    
    yaml_path = os.path.join(output_dir, 'dataset_full.yaml')
    with open(yaml_path, 'w') as f:
        yaml.dump(config, f, default_flow_style=False)
    
    print(f"Created YAML configuration file: {yaml_path}")
    
    # Train model
    model = YOLO(model_name_path)
    
    # Create project name
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    project_name = f'yolov11_full_{model_size}'
    run_name = f'normalized_boxes_{timestamp}' if normalize_boxes else f'standard_{timestamp}'
    
    # Train model
    results = model.train(
        data=yaml_path,
        epochs=epochs,
        batch=batch_size,
        imgsz=image_size,
        patience=epochs // 2,  # Early stopping patience
        cache=True,
        project=project_name,
        name=run_name,
        save=True,
        pretrained=pretrained,
        verbose=True,
        val=True,
        save_period=10,
        lr0=initial_lr,
        lrf=0.01,
        warmup_epochs=warmup_epochs,
        box=7.5,
        cls=cls_gain,
        cos_lr=True,
        close_mosaic=10,
        amp=True,
        plots=True
    )
    
    # Extract metrics
    metrics = model.metrics.results_dict
    map50 = metrics.get('metrics/mAP50(B)', 0.0)
    
    # Store training results
    train_results = {
        'timestamp': timestamp,
        'model_size': model_size,
        'epochs': epochs,
        'batch_size': batch_size,
        'map50': float(map50),
        'train_images': len(train_images),
        'val_images': len(val_images),
        'normalized_boxes': normalize_boxes,
        'yaml_path': yaml_path,
        'model_path': os.path.join(project_name, run_name, 'weights', 'best.pt')
    }
    
    # Save training results
    results_path = os.path.join(output_dir, f'train_results_{timestamp}.json')
    with open(results_path, 'w') as f:
        json.dump(train_results, f, indent=2)
    
    print(f"\n{'='*50}")
    print(f"Training Results")
    print(f"{'='*50}")
    print(f"mAP50: {map50:.4f}")
    print(f"Trained with normalized bounding boxes: {normalize_boxes}")
    print(f"Model saved to: {train_results['model_path']}")
    print(f"Results saved to: {results_path}")
    
    return train_results

In [ ]:
# Train with normalized bounding boxes
results = train_yolov11_full_dataset(
    output_dir='my_dataset',
    model_name_path='yolov11s.pt',
    model_size='s',
    epochs=100,
    batch_size=16,
    normalize_boxes=True,
    train_val_split=0.8
)

# Or train with original bounding boxes
results = train_yolov11_full_dataset(
    output_dir='my_dataset',
    model_name_path='yolov11s.pt',
    normalize_boxes=False
)

# Adding k fold validation, normalization of bounding boxes and less epochs

In [41]:
import os
import pandas as pd
import numpy as np
import yaml
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split, KFold
from PIL import Image
import shutil
import yaml
import torch
import json
from datetime import datetime

def k_fold_cross_validation(output_dir='yolo_dataset', n_splits=5, random_state=42):
    """
    Create k-fold cross-validation splits for YOLO training.
    
    Args:
        output_dir: directory containing the YOLO format dataset
        n_splits: number of folds
        random_state: random seed for reproducibility
        
    Returns:
        List of dictionaries containing train and validation indices for each fold
    """
    print(f"Creating {n_splits}-fold cross-validation splits...")
    
    # Get all image filenames
    image_dir = os.path.join(output_dir, 'images')
    all_images = [f for f in os.listdir(image_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    # Initialize KFold
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    
    # Create fold directories
    for fold_idx in range(n_splits):
        for split in ['train', 'val']:
            for subdir in ['images', 'labels']:
                fold_dir = os.path.join(output_dir, f'fold{fold_idx+1}', split, subdir)
                os.makedirs(fold_dir, exist_ok=True)
    
    # Generate folds
    fold_info = []
    for fold_idx, (train_idx, val_idx) in enumerate(kf.split(all_images)):
        train_images = [all_images[i] for i in train_idx]
        val_images = [all_images[i] for i in val_idx]
        
        fold_info.append({
            'fold': fold_idx + 1,
            'train_images': len(train_images),
            'val_images': len(val_images)
        })
        
        # Create train and val splits for this fold
        for split, images in [('train', train_images), ('val', val_images)]:
            for img_file in images:
                # Get corresponding label file
                label_file = os.path.splitext(img_file)[0] + '.txt'
                
                # Copy image
                src_img = os.path.join(output_dir, 'images', img_file)
                dst_img = os.path.join(output_dir, f'fold{fold_idx+1}', split, 'images', img_file)
                shutil.copy(src_img, dst_img)
                
                # Copy label
                src_label = os.path.join(output_dir, 'labels', label_file)
                dst_label = os.path.join(output_dir, f'fold{fold_idx+1}', split, 'labels', label_file)
                if os.path.exists(src_label):  # Some images might not have annotations
                    shutil.copy(src_label, dst_label)
    
    # Print fold information
    print(f"K-fold splits created:")
    for fold in fold_info:
        print(f"  Fold {fold['fold']}: {fold['train_images']} train, {fold['val_images']} validation images")
    
    return fold_info

def create_fold_yaml_configs(output_dir='yolo_dataset', classes=None, n_splits=5):
    """
    Create YAML configuration files for each fold.
    
    Args:
        output_dir: directory containing the YOLO format dataset
        classes: list of class names
        n_splits: number of folds
        
    Returns:
        List of paths to the YAML configuration files
    """
    # If classes not provided, load from classes.txt
    if classes is None:
        classes_path = os.path.join(output_dir, 'classes.txt')
        if os.path.exists(classes_path):
            with open(classes_path, 'r') as f:
                classes = [line.strip() for line in f.readlines()]
        else:
            raise ValueError("Classes not provided and classes.txt not found.")
    
    yaml_paths = []
    
    for fold_idx in range(1, n_splits + 1):
        config = {
            'path': os.path.abspath(os.path.join(output_dir, f'fold{fold_idx}')),
            'train': 'train/images',
            'val': 'val/images',
            'nc': len(classes),
            'names': classes
        }
        
        yaml_path = os.path.join(output_dir, f'dataset_fold{fold_idx}.yaml')
        with open(yaml_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False)
        
        yaml_paths.append(yaml_path)
    
    print(f"Created {n_splits} YAML configuration files for cross-validation")
    return yaml_paths

def train_kfold_yolov11(output_dir='yolo_dataset', model_name_path='yolov11s.pt', n_splits=5, 
                        model_size='s', epochs=100, batch_size=16, image_size=640, cls_gain=0.5, 
                        warmup_epochs=3.0, initial_lr=0.01, pretrained=True):
    """
    Train a YOLOv11 model with k-fold cross-validation.
    
    Args:
        output_dir: directory containing the YOLO format dataset
        model_name_path: path to the base model
        n_splits: number of folds
        model_size: YOLOv11 model size ('n', 's', 'm', 'l', 'x')
        epochs: number of training epochs
        batch_size: batch size
        image_size: input image size
        cls_gain: classification loss weight
        warmup_epochs: number of warmup epochs
        initial_lr: initial learning rate
        pretrained: whether to use pretrained weights
        
    Returns:
        Dictionary containing cross-validation results
    """
    # Import YOLO
    from ultralytics import YOLO
    
    # Create k-fold splits
    fold_info = k_fold_cross_validation(output_dir=output_dir, n_splits=n_splits)
    
    # Create YAML configs for each fold
    yaml_paths = create_fold_yaml_configs(output_dir=output_dir, n_splits=n_splits)
    
    # Train model for each fold
    cv_results = {
        'folds': [],
        'mean_map50': 0.0,
        'std_map50': 0.0,
        'best_fold': 0,
        'best_map50': 0.0,
        'model_size': model_size,
        'epochs': epochs,
        'batch_size': batch_size,
        'timestamp': datetime.now().strftime("%Y%m%d_%H%M%S")
    }
    
    map50_scores = []
    
    for fold_idx, yaml_path in enumerate(yaml_paths):
        print(f"\n{'='*50}")
        print(f"Training fold {fold_idx+1}/{n_splits}")
        print(f"{'='*50}")
        
        # Load model for this fold
        model = YOLO(model_name_path)
        
        # Create project name for this fold
        project_name = f'yolov11_cv_{model_size}'
        run_name = f'fold{fold_idx+1}_of_{n_splits}'
        
        # Train model
        results = model.train(
            data=yaml_path,
            epochs=epochs,
            batch=batch_size,
            imgsz=image_size,
            patience=epochs // 2,  # Early stopping patience
            cache=True,
            project=project_name,
            name=run_name,
            save=True,
            pretrained=pretrained,
            verbose=True,
            val=True,
            save_period=10,
            lr0=initial_lr,
            lrf=0.01,
            warmup_epochs=warmup_epochs,
            box=7.5,
            cls=cls_gain,
            cos_lr=True,
            close_mosaic=10,
            amp=True,
            plots=True
        )
        
        # Extract metrics
        metrics = model.metrics.results_dict
        map50 = metrics.get('metrics/mAP50(B)', 0.0)
        map50_scores.append(map50)
        
        # Store fold results
        fold_result = {
            'fold': fold_idx + 1,
            'map50': map50,
            'yaml_path': yaml_path,
            'model_path': os.path.join(project_name, run_name, 'weights', 'best.pt')
        }
        cv_results['folds'].append(fold_result)
        
        print(f"Fold {fold_idx+1} mAP50: {map50:.4f}")
    
    # Calculate cross-validation statistics
    mean_map50 = np.mean(map50_scores)
    std_map50 = np.std(map50_scores)
    best_fold_idx = np.argmax(map50_scores)
    best_map50 = map50_scores[best_fold_idx]
    
    cv_results['mean_map50'] = float(mean_map50)
    cv_results['std_map50'] = float(std_map50)
    cv_results['best_fold'] = int(best_fold_idx + 1)
    cv_results['best_map50'] = float(best_map50)
    
    # Save cross-validation results
    results_path = os.path.join(output_dir, f'cv_results_{cv_results["timestamp"]}.json')
    with open(results_path, 'w') as f:
        json.dump(cv_results, f, indent=2)
    
    print(f"\n{'='*50}")
    print(f"Cross-Validation Results")
    print(f"{'='*50}")
    print(f"Mean mAP50: {mean_map50:.4f}")
    print(f"Standard Deviation: {std_map50:.4f}")
    print(f"Best Fold: {best_fold_idx + 1} (mAP50: {best_map50:.4f})")
    print(f"Results saved to: {results_path}")
    
    return cv_results

def ensemble_kfold_models(cv_results, output_dir='yolo_dataset', test_images_dir=None, 
                          conf_threshold=0.25, iou_threshold=0.45):
    """
    Create an ensemble of k-fold models for inference.
    
    Args:
        cv_results: cross-validation results from train_kfold_yolov11
        output_dir: directory containing the YOLO format dataset
        test_images_dir: directory containing test images (if None, uses validation set from best fold)
        conf_threshold: confidence threshold for detections
        iou_threshold: IoU threshold for NMS
        
    Returns:
        Ensemble prediction results
    """
    from ultralytics import YOLO
    
    print(f"\n{'='*50}")
    print(f"Creating Model Ensemble from K-Fold Models")
    print(f"{'='*50}")
    
    # Load all models
    models = []
    for fold_info in cv_results['folds']:
        model_path = fold_info['model_path']
        if os.path.exists(model_path):
            print(f"Loading model from fold {fold_info['fold']}: {model_path}")
            model = YOLO(model_path)
            models.append(model)
        else:
            print(f"WARNING: Model not found for fold {fold_info['fold']}: {model_path}")
    
    if len(models) == 0:
        raise ValueError("No models found for ensemble.")
    
    # Determine test images directory
    if test_images_dir is None:
        best_fold = cv_results['best_fold']
        best_fold_yaml = cv_results['folds'][best_fold - 1]['yaml_path']
        
        # Load YAML config to get validation data path
        with open(best_fold_yaml, 'r') as f:
            config = yaml.safe_load(f)
            base_path = config['path']
            val_path = os.path.join(base_path, config['val'])
            test_images_dir = val_path
    
    print(f"Running ensemble inference on: {test_images_dir}")
    
    # Create output directory for ensemble predictions
    ensemble_dir = os.path.join(output_dir, f'ensemble_{cv_results["timestamp"]}')
    os.makedirs(ensemble_dir, exist_ok=True)
    
    # Run predictions with each model
    all_predictions = []
    
    for i, model in enumerate(models):
        print(f"Running predictions with model {i+1}/{len(models)}")
        results = model.predict(
            source=test_images_dir,
            conf=conf_threshold,
            iou=iou_threshold,
            save=False,
            save_txt=False,
            verbose=False
        )
        all_predictions.append(results)
    
    # Combine predictions
    ensemble_predictions = []
    processed_images = set()
    
    print("Combining predictions from all models...")
    for model_idx, model_results in enumerate(all_predictions):
        for result in model_results:
            img_name = os.path.basename(result.path)
            
            # Extract predictions
            if len(result.boxes) > 0:
                for box in result.boxes:
                    x1, y1, x2, y2 = box.xyxy[0].tolist()
                    conf = box.conf.item()
                    cls = int(box.cls.item())
                    class_name = models[model_idx].names[cls]
                    
                    ensemble_predictions.append({
                        'image_name': img_name,
                        'class': class_name,
                        'confidence': conf,
                        'xmin': x1,
                        'ymin': y1,
                        'xmax': x2,
                        'ymax': y2,
                        'model': model_idx + 1
                    })
                    
                    processed_images.add(img_name)
    
    # Create DataFrame and save
    if ensemble_predictions:
        pred_df = pd.DataFrame(ensemble_predictions)
        predictions_path = os.path.join(ensemble_dir, 'ensemble_predictions.csv')
        pred_df.to_csv(predictions_path, index=False)
        
        # Also save summarized predictions
        image_count = len(processed_images)
        prediction_count = len(ensemble_predictions)
        model_count = len(models)
        
        summary = {
            'timestamp': cv_results['timestamp'],
            'models_used': model_count,
            'images_processed': image_count,
            'total_predictions': prediction_count,
            'average_predictions_per_image': prediction_count / max(1, image_count),
            'conf_threshold': conf_threshold,
            'iou_threshold': iou_threshold
        }
        
        summary_path = os.path.join(ensemble_dir, 'ensemble_summary.json')
        with open(summary_path, 'w') as f:
            json.dump(summary, f, indent=2)
        
        print(f"Ensemble predictions saved to: {predictions_path}")
        print(f"Processed {image_count} images with {prediction_count} total detections")
    else:
        print("No predictions generated by the ensemble.")
    
    return ensemble_predictions

In [43]:
output_dir_to_use = "yolo_dataset_kfold_normed"
# Step 1: Process your dataset (your existing code)
classes = process_dataset(train_df, output_dir=output_dir_to_use)

# Step 2: Instead of splitting the dataset, run k-fold cross-validation
k_fold_cross_validation(output_dir=output_dir_to_use, n_splits=5)

Processed 5529 images with 9792 annotations.
Creating 5-fold cross-validation splits...
K-fold splits created:
  Fold 1: 4197 train, 1050 validation images
  Fold 2: 4197 train, 1050 validation images
  Fold 3: 4198 train, 1049 validation images
  Fold 4: 4198 train, 1049 validation images
  Fold 5: 4198 train, 1049 validation images

[{'fold': 1, 'train_images': 4197, 'val_images': 1050},
 {'fold': 2, 'train_images': 4197, 'val_images': 1050},
 {'fold': 3, 'train_images': 4198, 'val_images': 1049},
 {'fold': 4, 'train_images': 4198, 'val_images': 1049},
 {'fold': 5, 'train_images': 4198, 'val_images': 1049}]

In [44]:

# Step 3: Train models for all folds
cv_results = train_kfold_yolov11(
    output_dir=output_dir_to_use,
    model_name_path=pretrained_yolo_path,  # or your pretrained model path
    n_splits=5,
    epochs=20,
    batch_size=64,
    cls_gain=0.5,
    pretrained=True  # This allows backpropagation on all weights
)

Creating 5-fold cross-validation splits...
K-fold splits created:
  Fold 1: 4197 train, 1050 validation images
  Fold 2: 4197 train, 1050 validation images
  Fold 3: 4198 train, 1049 validation images
  Fold 4: 4198 train, 1049 validation images
  Fold 5: 4198 train, 1049 validation images
Created 5 YAML configuration files for cross-validation

==================================================
Training fold 1/5
==================================================
New https://pypi.org/project/ultralytics/8.3.96 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=plant-leaf-detection-and-classification/best.pt, data=yolo_dataset_kfold_normed/dataset_fold1.yaml, epochs=20, time=None, patience=10, batch=64, imgsz=640, save=True, save_period=10, cache=True, device=None, workers=8, project=yolov11_cv_s, name=fold1_of_5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_cv_s/fold1_of_5
Overriding model.yaml nc=46 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
Model summary: 129 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/labels... 4197 images, 0 backgrounds, 686 corrupt: 100%|██████████| 4197/4197 [00:11<00:00, 379.42it/s]

train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AJD939.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_CxIwDu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_E1fISS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]

train: New cache created: /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/train/labels.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (3.1GB RAM): 100%|██████████| 3511/3511 [00:19<00:00, 181.17it/s]
val: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/labels... 1050 images, 0 backgrounds, 195 corrupt: 100%|██████████| 1050/1050 [00:03<00:00, 276.53it/s]

val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_AclybJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0985      1.2153]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_BsWVWD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1969      2.0294]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_FWv6k7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_GA4ocU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1171]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_GONPQx.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0785]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_GWhiLp.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_GZeZQ7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1696]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_GkZMVQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.8572]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_HIFZij.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1217]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_HQpL3y.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0294]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_HS970U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.4939      1.0742]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_IRVs9J.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_IRWSPd.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_IUz3r9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2824]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_IjpumM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_IwPsnt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2923]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_JHsmyN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1121      1.6861]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_JltOLk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2834      1.1822]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KDq13B.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2144      2.0156]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KTP6kp.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2061]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KZwJAM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2612]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KbaWjL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1322        2.18]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KkyQ36.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1244      2.1956]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KoUDAP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0119      1.2586]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KqcXSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1134      1.1291]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_KxHwli.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_L0K6CF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0976]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_LA1RfJ.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_LFYoyL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_LLSZyI.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2784]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_LkJ8Zz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0245]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_MIeJvr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1101      1.0147      1.1377]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_MhuKki.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Mmotno.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1119]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_N9A9JN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1496]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_NGvzWH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0832]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_NPQOoz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.089]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_NRkeOG.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0589]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Na6hR0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_NbU1Pn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1591]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_NfmKR2.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.228]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Ng5Pt8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3006      1.1004]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Nk9IfK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1862]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_NuyEeD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0397      1.2612]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_OIGzbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2004]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_OZ1lc7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0673      1.1413]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_OtEC7c.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_OwFJgN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_P2qCLW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2576]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_PDbzh1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.167]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_PIg9if.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2163       1.042]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_POD5HU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_POyDGg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_PQm2Ft.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0428]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_PVckAY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1088]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_PqV4gW.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Q938mO.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2161]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_QZGiws.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1227]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_QopCWu.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1433      1.8344]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Rfm919.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.289]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_S3A64w.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0642]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_SJKaao.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2408      1.4717]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_SSGiW2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.9108]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_SVzl5X.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Sb77iH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2477]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_SnC6Z6.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_SuY5t1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2561]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_T7RQCl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.155      2.1344]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_T9Sifn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2356      1.9733]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_T9n3Yk.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_TLVeAC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0949]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_ULx8cJ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2339]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_UjMeQ0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.254]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_Uoy7f2.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_UrKjY8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3075       1.525]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_VwIYf0.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_WILdJN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3317      1.0202]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_WIuXLH.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_WKcQeb.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0126]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold1/val/images/ID_WR3TUM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2209      1.0165]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.7GB RAM): 100%|██████████| 855/855 [00:04<00:00, 182.52it/s]

Plotting labels to yolov11_cv_s/fold1_of_5/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_cv_s/fold1_of_5
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/20      13.3G      1.327      2.184      1.736        232        640: 100%|██████████| 55/55 [00:17<00:00,  3.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.52it/s]

                   all        855       1509      0.571      0.436      0.433       0.24

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/20      17.7G      1.267      1.434      1.604        234        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        855       1509      0.535       0.46      0.433      0.241

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/20      17.7G      1.287      1.407      1.606        224        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.52it/s]

                   all        855       1509      0.346      0.363       0.27      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/20      17.7G      1.284      1.382      1.595        222        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.46it/s]

                   all        855       1509      0.504      0.449      0.402      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/20      17.8G      1.231      1.274      1.545        238        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.51it/s]

                   all        855       1509      0.477      0.478      0.437      0.251

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/20      17.8G      1.165      1.196      1.499        230        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.55it/s]

                   all        855       1509      0.525      0.501      0.448      0.253

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/20      17.8G      1.117      1.101      1.468        208        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.56it/s]

                   all        855       1509      0.591      0.521      0.501      0.292

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/20      17.9G      1.047       1.02       1.41        209        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.58it/s]

                   all        855       1509      0.605      0.491      0.528      0.307

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/20      17.9G      1.008     0.9695       1.38        263        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.57it/s]

                   all        855       1509      0.696      0.569      0.615      0.369

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/20      17.9G     0.9684     0.9032      1.348        223        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.62it/s]

                   all        855       1509      0.654      0.577        0.6      0.368

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/20        18G      1.283      1.281      1.695         89        640: 100%|██████████| 55/55 [00:18<00:00,  3.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.52it/s]

                   all        855       1509      0.672      0.571      0.626      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/20        18G      1.229      1.163       1.64         88        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.55it/s]

                   all        855       1509      0.668        0.6      0.638      0.401

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/20      18.1G      1.181      1.108      1.607        106        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.55it/s]

                   all        855       1509      0.698      0.629      0.685      0.431

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/20      18.1G      1.154      1.044      1.569         91        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.53it/s]

                   all        855       1509      0.706      0.644      0.696       0.45

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/20      18.1G      1.111     0.9882      1.537         88        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.28it/s]

                   all        855       1509      0.755      0.622      0.702      0.461

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/20      18.2G       1.07     0.9339        1.5         92        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.54it/s]

                   all        855       1509      0.715      0.641        0.7       0.46

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/20      18.2G       1.04     0.8929      1.471        100        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.55it/s]

                   all        855       1509       0.73      0.657       0.71      0.464

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/20      18.2G      1.009     0.8757      1.453        101        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.49it/s]

                   all        855       1509      0.705      0.676      0.713      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/20      18.3G     0.9965     0.8486      1.444         95        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.48it/s]

                   all        855       1509      0.725      0.655      0.709      0.465

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/20      18.3G     0.9862     0.8336      1.421        100        640: 100%|██████████| 55/55 [00:17<00:00,  3.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.54it/s]

                   all        855       1509       0.77      0.628       0.71      0.467

20 epochs completed in 0.113 hours.
Optimizer stripped from yolov11_cv_s/fold1_of_5/weights/last.pt, 22.5MB
Optimizer stripped from yolov11_cv_s/fold1_of_5/weights/best.pt, 22.5MB

Validating yolov11_cv_s/fold1_of_5/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
Model summary (fused): 72 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.65it/s]

                   all        855       1509       0.77      0.628       0.71      0.467
               healthy        246        619      0.745      0.601      0.676      0.431
           anthracnose        205        319      0.711      0.624      0.678      0.429
                 cssvd        405        571      0.853      0.661      0.776      0.542
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to yolov11_cv_s/fold1_of_5
Fold 1 mAP50: 0.7097

==================================================
Training fold 2/5
==================================================
New https://pypi.org/project/ultralytics/8.3.96 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=plant-leaf-detection-and-classification/best.pt, data=yolo_dataset_kfold_normed/dataset_fold2.yaml, epochs=20, time=None, patience=10, batch=64, imgsz=640, save=True, save_period=10, cache=True, device=None, workers=8, project=yolov11_cv_s, name=fold2_of_5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_cv_s/fold2_of_5
Overriding model.yaml nc=46 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
Model summary: 129 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/labels... 4197 images, 0 backgrounds, 704 corrupt: 100%|██████████| 4197/4197 [00:11<00:00, 372.11it/s]

train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AJD939.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AclybJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0985      1.2153]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BsWVWD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1969      2.0294]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FTVHZk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/train/images/ID_FViv94.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1895]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (3.0GB RAM): 100%|██████████| 3493/3493 [00:16<00:00, 207.81it/s]
val: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/labels... 1050 images, 0 backgrounds, 177 corrupt: 100%|██████████| 1050/1050 [00:04<00:00, 217.71it/s]

val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_CxIwDu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_E1fISS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_G3zqaj.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2778]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_G9zF3H.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_GGQ1De.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0536]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_GHbB3b.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3317      1.2841]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_GWJUCD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_GmNfRI.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_H3hHVq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0364]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_H7QQ2I.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0672]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_H9qAYr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2946]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_HIPul1.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_HidqdL.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_IGIR4B.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_IvmqsJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1948]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_J0cjqu.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3353      1.7739]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_J4jaP8.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3169]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_J5mTAL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1432      1.0896]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_J7hL2Y.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2668      1.1844]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_JRjOWi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1203      2.2039]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_KcdUV1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.003]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_LWXokA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1548]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_LXBv1Y.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2679]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_LwJYsy.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_M1CmZf.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1022      1.2097      1.2515]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_M3NBS2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2065       1.322]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_MPIvc5.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2351]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_MQt7CR.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_MbZhzx.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2946]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Mik03p.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2956]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Mio4o3.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0364]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_MmvaQa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2197      1.8661]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Mw77BB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2163      1.2288]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_N5qA2k.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2034]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_N6uNo7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0098      1.0694]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_NGiOVN.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0539]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_NbftLH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1064      1.2339]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_NcA2qf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0083]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_NlJLXQ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_NmYqu6.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Np7dI9.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_OE83eN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1432]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_OFTTvl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1203      1.9539]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_OFhcZk.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_OLSPvm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Og3HI8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.004]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_OkoEnN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2841]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Ot9lnj.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2057]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_PR1tKH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1465       1.289]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_PlSJ3I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.247]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_QYyaBC.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Qd9ukH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.207]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_QitFhY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1974]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Qx92as.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1591]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_R0gFs3.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1736      2.0972]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_R7AGWM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3234]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_RDpYbj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1225      2.1806]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_S5OpiT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2695]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_S7q92y.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0084]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Spq7s1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1006      2.1478]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_TAILbh.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0119]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_TB2QQA.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_TOxurW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1448]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_TdWq9r.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0767]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_TrS7AO.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1192      2.2061]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_TsKBBh.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1465]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_U4m06T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0013]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_U8HUUd.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.206]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_UGwTfF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_UJyo7C.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_Ui8E1j.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0872]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_UlmVRq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_V42JvR.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_VDHD6M.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2513      1.0496]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_VYmWg8.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056      1.2251]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_W2eGlr.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_W31F1e.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.42      1.5069      1.4306]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_WB25bW.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold2/val/images/ID_X0tkQE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.8GB RAM): 100%|██████████| 873/873 [00:04<00:00, 207.07it/s]

Plotting labels to yolov11_cv_s/fold2_of_5/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_cv_s/fold2_of_5
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/20      13.4G       1.33      2.152       1.74        146        640: 100%|██████████| 55/55 [00:17<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        873       1491      0.616      0.477      0.507      0.301

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/20      17.8G       1.26      1.444      1.597        148        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        873       1491      0.559      0.494      0.479      0.262

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/20      17.8G      1.287      1.357        1.6        140        640: 100%|██████████| 55/55 [00:16<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.45it/s]

                   all        873       1491      0.239       0.39      0.181      0.073

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/20      17.8G      1.264      1.351       1.58        167        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        873       1491      0.456      0.488       0.38      0.207

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/20      17.8G      1.207      1.235      1.531        155        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.48it/s]

                   all        873       1491      0.507      0.455      0.423       0.23

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/20      17.8G      1.151      1.144      1.491        147        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.49it/s]

                   all        873       1491      0.548      0.529      0.468      0.255

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/20      17.8G      1.106      1.072      1.452        182        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.50it/s]

                   all        873       1491      0.613       0.54       0.53      0.311

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/20      17.8G      1.061      1.018      1.422        156        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.45it/s]

                   all        873       1491      0.621      0.545      0.563      0.327

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/20      17.8G      1.003     0.9351      1.376        156        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.51it/s]

                   all        873       1491      0.596      0.584       0.57      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/20      17.8G     0.9647     0.8873      1.348        181        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.42it/s]

                   all        873       1491      0.625      0.569      0.583      0.349

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/20      17.8G      1.289      1.279      1.705         65        640: 100%|██████████| 55/55 [00:17<00:00,  3.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        873       1491      0.683      0.595      0.637      0.396

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/20      17.9G      1.233      1.169      1.644         62        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.42it/s]

                   all        873       1491      0.706       0.59      0.638      0.402

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/20      17.9G      1.177      1.102      1.601         64        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.44it/s]

                   all        873       1491      0.728      0.587      0.665      0.426

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/20      17.9G      1.139      1.031      1.562         77        640: 100%|██████████| 55/55 [00:17<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.34it/s]

                   all        873       1491      0.726      0.633      0.682      0.446

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/20        18G      1.119          1       1.54         72        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.47it/s]

                   all        873       1491      0.732      0.622      0.681      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/20        18G      1.077     0.9429      1.516         59        640: 100%|██████████| 55/55 [00:16<00:00,  3.30it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.37it/s]

                   all        873       1491      0.755      0.614      0.689      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/20        18G      1.036     0.9049      1.469         63        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.49it/s]

                   all        873       1491      0.748      0.632      0.701      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/20      18.1G      1.023     0.8731      1.469         64        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.45it/s]

                   all        873       1491      0.727      0.645      0.698      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/20      18.1G      1.017     0.8561      1.461         59        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.45it/s]

                   all        873       1491      0.749      0.633      0.701      0.462

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/20      18.1G     0.9898     0.8393      1.439         57        640: 100%|██████████| 55/55 [00:16<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.48it/s]

                   all        873       1491      0.749      0.631      0.698      0.459

20 epochs completed in 0.114 hours.
Optimizer stripped from yolov11_cv_s/fold2_of_5/weights/last.pt, 22.5MB
Optimizer stripped from yolov11_cv_s/fold2_of_5/weights/best.pt, 22.5MB

Validating yolov11_cv_s/fold2_of_5/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
Model summary (fused): 72 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.65it/s]

                   all        873       1491      0.748      0.633      0.701      0.463
               healthy        219        546      0.766      0.606      0.703      0.447
           anthracnose        239        342        0.7      0.621      0.658      0.432
                 cssvd        415        603      0.777      0.671      0.744      0.512
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to yolov11_cv_s/fold2_of_5
Fold 2 mAP50: 0.7014

==================================================
Training fold 3/5
==================================================
New https://pypi.org/project/ultralytics/8.3.96 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=plant-leaf-detection-and-classification/best.pt, data=yolo_dataset_kfold_normed/dataset_fold3.yaml, epochs=20, time=None, patience=10, batch=64, imgsz=640, save=True, save_period=10, cache=True, device=None, workers=8, project=yolov11_cv_s, name=fold3_of_5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_cv_s/fold3_of_5
Overriding model.yaml nc=46 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
Model summary: 129 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/labels... 4198 images, 0 backgrounds, 723 corrupt: 100%|██████████| 4198/4198 [00:11<00:00, 367.99it/s]

train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AJD939.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AclybJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0985      1.2153]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BsWVWD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1969      2.0294]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_CxIwDu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_E1fISS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FTVHZk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FViv94.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1895]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FVssBB.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FWv6k7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_Fk8aG8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1905      1.0218]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/train/images/ID_FliLbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2589      1.6944]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (3.0GB RAM): 100%|██████████| 3475/3475 [00:16<00:00, 208.98it/s]
val: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/labels... 1049 images, 0 backgrounds, 158 corrupt: 100%|██████████| 1049/1049 [00:04<00:00, 221.34it/s]

val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Fm1oY7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_FqB8FS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_FtYRqz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      2.1906]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_GFYqTL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1111      1.6944]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_GQ4JN6.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_GXkRNZ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0476]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Gm71wX.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2975]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_HVD3N5.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.121]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_HkFV9J.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_IbbaXY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1486]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_IqkCAv.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0478      1.0189      1.2931      1.6361]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Itd6eF.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_IuBkcQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.5528      1.3389]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_IwyjUK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1538]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_JRTUsh.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1878      1.8156]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_K8wlr4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2583]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_KOQFDz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0939]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Ko4fL3.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_LCHPqv.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1392]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_LYQ46X.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2907]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Lfy3xZ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3105]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_LkW652.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_MF34U1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.4072        1.63]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_MIlKDj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2751]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_MQkZBH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_MztPy0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1297       2.185]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_NiMPVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0685]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Nj8GQr.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2956]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_NnsZPe.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0053]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_NrUpnW.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_OGuNyK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2606]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_ONdWcH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.289]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_OkkNua.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1273       1.289]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_OuG7Zm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.001]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_PYm4ri.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2427]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_PaWUQ0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2196]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_PawdsQ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0568      1.2134      1.2471      1.1844]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Q0PXyQ.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Q4mjHS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2351]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_QVEUhP.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_QZyOk7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2083      1.1311]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Qa0DYk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Qinkut.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Qk55yz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2259      1.2163]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Qrb5an.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.123       1.265]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_R1TTBO.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237      1.0514]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_R4BBdy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1151      1.0078]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_R6QBuf.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_RWPGUG.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_SIBD4X.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_SSPUE6.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.239]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_SnIRkY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1448]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_TaRNtN.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1093      1.2697]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_U3ry9E.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.1088]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_UC4VBv.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1888      1.0347]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_USBlAz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2393]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_UY44L0.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_UYftKa.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_UjkxXW.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_Uy6rwR.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2808]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_V6suLj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022       1.043]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_VX3dMQ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0927]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_W3tZGh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0554]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_WInGFr.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0556]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_WULBQy.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_WhWbbp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0089]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_X0udgZ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.4461]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_X9IstM.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1011]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_XDfx9S.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113      1.2946]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_XUodax.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2543      1.2001]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_XXNoaV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2698]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold3/val/images/ID_XifZNH.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2167]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.8GB RAM): 100%|██████████| 891/891 [00:04<00:00, 190.64it/s]

Plotting labels to yolov11_cv_s/fold3_of_5/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_cv_s/fold3_of_5
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/20      13.3G      1.336      2.145      1.747         76        640: 100%|██████████| 55/55 [00:17<00:00,  3.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.36it/s]

                   all        891       1553      0.507      0.453       0.43      0.246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/20      17.8G      1.277      1.427      1.598         76        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.33it/s]

                   all        891       1553      0.401      0.404       0.32      0.167

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/20      17.8G      1.307      1.379       1.61         78        640: 100%|██████████| 55/55 [00:16<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.30it/s]

                   all        891       1553       0.38      0.395       0.29      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/20      17.8G      1.294      1.353      1.597         79        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.14it/s]

                   all        891       1553      0.431        0.5       0.38      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/20      17.8G       1.23      1.268      1.547         72        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.17it/s]

                   all        891       1553      0.584      0.491      0.482      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/20      17.8G      1.196      1.197      1.519        107        640: 100%|██████████| 55/55 [00:16<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.38it/s]

                   all        891       1553      0.541      0.533      0.467      0.272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/20      17.8G      1.135      1.116      1.479         87        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.42it/s]

                   all        891       1553      0.635      0.483      0.524      0.312

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/20      17.8G      1.075       1.03      1.428         76        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.36it/s]

                   all        891       1553      0.574       0.55      0.541      0.305

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/20      17.8G      1.035     0.9674      1.391         87        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.42it/s]

                   all        891       1553      0.549      0.538      0.468      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/20      17.8G     0.9774     0.9125       1.36         94        640: 100%|██████████| 55/55 [00:16<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.42it/s]

                   all        891       1553      0.639      0.567      0.579      0.342

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/20      17.8G      1.305      1.299       1.72         34        640: 100%|██████████| 55/55 [00:17<00:00,  3.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.32it/s]

                   all        891       1553      0.649      0.532      0.575       0.36

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/20      17.8G      1.227      1.179      1.647         31        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.09it/s]

                   all        891       1553      0.724      0.558      0.643      0.408

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/20      17.9G      1.195      1.077      1.604         33        640: 100%|██████████| 55/55 [00:17<00:00,  3.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        891       1553      0.704      0.614      0.656      0.419

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/20      17.9G      1.156       1.03      1.576         33        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.40it/s]

                   all        891       1553      0.719      0.592       0.66      0.428

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/20        18G      1.119      1.005      1.549         36        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.13it/s]

                   all        891       1553      0.695      0.616      0.668      0.435

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/20        18G      1.076     0.9383      1.496         31        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        891       1553      0.727      0.629       0.69      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/20        18G      1.049     0.9096      1.484         30        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.13it/s]

                   all        891       1553      0.734      0.612      0.678      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/20      18.1G      1.039     0.8801      1.476         40        640: 100%|██████████| 55/55 [00:16<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.25it/s]

                   all        891       1553      0.745      0.613      0.682      0.453

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/20      18.1G      1.008     0.8606      1.451         37        640: 100%|██████████| 55/55 [00:16<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        891       1553      0.725      0.627      0.683      0.454

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/20      18.1G      1.003     0.8379      1.449         33        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.40it/s]

                   all        891       1553      0.735      0.619      0.687      0.455

20 epochs completed in 0.115 hours.
Optimizer stripped from yolov11_cv_s/fold3_of_5/weights/last.pt, 22.5MB
Optimizer stripped from yolov11_cv_s/fold3_of_5/weights/best.pt, 22.5MB

Validating yolov11_cv_s/fold3_of_5/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
Model summary (fused): 72 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.67it/s]

                   all        891       1553      0.736      0.618      0.687      0.455
               healthy        239        585      0.676      0.646      0.675      0.433
           anthracnose        229        356      0.744      0.587      0.677      0.443
                 cssvd        423        612      0.788      0.621      0.708       0.49
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to yolov11_cv_s/fold3_of_5
Fold 3 mAP50: 0.6866

==================================================
Training fold 4/5
==================================================
New https://pypi.org/project/ultralytics/8.3.96 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=plant-leaf-detection-and-classification/best.pt, data=yolo_dataset_kfold_normed/dataset_fold4.yaml, epochs=20, time=None, patience=10, batch=64, imgsz=640, save=True, save_period=10, cache=True, device=None, workers=8, project=yolov11_cv_s, name=fold4_of_5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_cv_s/fold4_of_5
Overriding model.yaml nc=46 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
Model summary: 129 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/labels... 4198 images, 0 backgrounds, 701 corrupt: 100%|██████████| 4198/4198 [00:11<00:00, 356.04it/s]

train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AJD939.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AclybJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0985      1.2153]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BsWVWD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1969      2.0294]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_CxIwDu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_E1fISS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FWv6k7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Fk8aG8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1905      1.0218]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_Fm1oY7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FqB8FS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_FtYRqz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      2.1906]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_G3zqaj.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2778]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_G9zF3H.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GA4ocU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1171]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GFYqTL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1111      1.6944]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GGQ1De.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0536]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GHbB3b.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3317      1.2841]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GONPQx.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0785]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GQ4JN6.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GWJUCD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/images/ID_GWhiLp.jpeg: corrupt JPEG restored and saved

train: New cache created: /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/train/labels.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (3.0GB RAM): 100%|██████████| 3497/3497 [00:18<00:00, 191.46it/s]
val: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/labels... 1049 images, 0 backgrounds, 180 corrupt: 100%|██████████| 1049/1049 [00:04<00:00, 214.15it/s]

val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_FTVHZk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_FViv94.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1895]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_FVssBB.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_FliLbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2589      1.6944]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_G4peHX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_GK394N.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_GSfilU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3082]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_GmeOgs.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Gz1PBm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_HE0Kqf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2751]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_HEKWRi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528      1.0403]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_HIGKr5.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_HLwqQJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1531      1.0073]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_HUdyGp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3112]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Hmxdwo.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_HuMwmi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1893]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_JBltx6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1362]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_JMesqN.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_JbPfXi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0122]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_K5rVxL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.8072      1.1111      2.2222]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_KbRv7T.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2642]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_LCbo1m.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0036      1.2161       1.212]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_LL6Nhk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_M9a8zh.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2364]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_MBg7Wu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0927]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_MCZcC1.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_NSHiVv.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2881      1.6572]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_NSzLqF.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2306]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_NpoqaB.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_OX2QwK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1366      1.1546]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_P5xQZW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0689]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_POaPiR.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2983]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_PzqDPT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1576]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Q6bjVM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_QEtXWS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Qrlnom.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2752]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Qu5Gdd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.11]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_RA4964.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_RHNJV0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3112      1.0493      1.0686]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_RNsIwo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_SWwaf9.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0701]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_SwqkAT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0137      1.0152]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_TgWLRl.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_ThOlqa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2444]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_TmV8Jj.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2807]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_ToNqcZ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_U2iecI.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_U7Gzyg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2583]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_UFGaPv.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2226]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Umc0P2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1894      1.7511]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_VGRSR0.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0313]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_VHuZVH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_W0g4l8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.064]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_WIvFKs.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2774]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_WKIhj1.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2639      1.1863      1.2293      1.2097]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Wa1IXp.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_WzxXRK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_XF1b8f.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3486      1.7472]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_XXs09M.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Xp56ze.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3175]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_Y5sfOy.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0317]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_YAdFuI.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/images/ID_YCJTkf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2808]

val: New cache created: /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold4/val/labels.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.8GB RAM): 100%|██████████| 869/869 [00:04<00:00, 198.17it/s]

Plotting labels to yolov11_cv_s/fold4_of_5/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_cv_s/fold4_of_5
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/20      13.4G      1.336      2.173      1.752        153        640: 100%|██████████| 55/55 [00:17<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        869       1551      0.564      0.454      0.416      0.233

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/20      17.9G      1.263       1.42      1.589        179        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        869       1551      0.395      0.443      0.357      0.179

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/20      17.9G      1.276      1.366      1.592        156        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        869       1551      0.464      0.425      0.372      0.178

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/20      17.9G      1.262      1.343      1.578        163        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        869       1551      0.412      0.499      0.363      0.176

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/20      17.9G      1.229      1.269      1.552        168        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        869       1551      0.428      0.369      0.322      0.158

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/20      17.9G      1.162       1.16        1.5        178        640: 100%|██████████| 55/55 [00:16<00:00,  3.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.50it/s]

                   all        869       1551      0.537      0.499      0.468      0.262

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/20      17.9G      1.106      1.091      1.464        171        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.54it/s]

                   all        869       1551      0.606       0.51      0.538      0.291

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/20      17.9G      1.052      1.026      1.416        165        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.52it/s]

                   all        869       1551      0.597      0.519      0.514      0.292

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/20      17.9G     0.9856     0.9442      1.373        178        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.53it/s]

                   all        869       1551      0.648      0.545      0.565      0.326

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/20      17.9G     0.9568     0.8952      1.348        172        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.42it/s]

                   all        869       1551      0.681      0.538      0.583      0.344

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/20      17.9G      1.284      1.291      1.699         81        640: 100%|██████████| 55/55 [00:17<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.45it/s]

                   all        869       1551      0.619      0.574      0.616      0.372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/20        18G      1.232      1.189      1.645         72        640: 100%|██████████| 55/55 [00:17<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.31it/s]

                   all        869       1551      0.661      0.604      0.638      0.388

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/20        18G       1.18      1.107      1.606         59        640: 100%|██████████| 55/55 [00:17<00:00,  3.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.17it/s]

                   all        869       1551      0.703      0.645      0.691      0.437

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/20      18.1G      1.145       1.06      1.571         68        640: 100%|██████████| 55/55 [00:16<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.30it/s]

                   all        869       1551      0.715      0.643      0.694      0.437

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/20      18.1G      1.109      1.008      1.546         67        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.40it/s]

                   all        869       1551      0.715      0.624      0.695      0.442

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/20      18.1G      1.071     0.9444      1.502         81        640: 100%|██████████| 55/55 [00:16<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.37it/s]

                   all        869       1551       0.72      0.639      0.704       0.45

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/20      18.2G       1.05     0.9129      1.488         73        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.35it/s]

                   all        869       1551      0.755      0.623      0.706      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/20      18.2G       1.02     0.8776      1.466         86        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.37it/s]

                   all        869       1551      0.728       0.64      0.708      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/20      18.2G     0.9976     0.8555      1.447         85        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.31it/s]

                   all        869       1551      0.739      0.637      0.708       0.46

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/20      18.3G     0.9894     0.8355      1.433         75        640: 100%|██████████| 55/55 [00:16<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.33it/s]

                   all        869       1551      0.751      0.631      0.709      0.462

20 epochs completed in 0.115 hours.
Optimizer stripped from yolov11_cv_s/fold4_of_5/weights/last.pt, 22.5MB
Optimizer stripped from yolov11_cv_s/fold4_of_5/weights/best.pt, 22.5MB

Validating yolov11_cv_s/fold4_of_5/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
Model summary (fused): 72 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.60it/s]

                   all        869       1551      0.748      0.635      0.709      0.462
               healthy        255        646      0.708      0.638      0.704       0.43
           anthracnose        209        328      0.756      0.598      0.683      0.436
                 cssvd        405        577       0.78      0.669      0.741      0.519
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to yolov11_cv_s/fold4_of_5
Fold 4 mAP50: 0.7091

==================================================
Training fold 5/5
==================================================
New https://pypi.org/project/ultralytics/8.3.96 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=plant-leaf-detection-and-classification/best.pt, data=yolo_dataset_kfold_normed/dataset_fold5.yaml, epochs=20, time=None, patience=10, batch=64, imgsz=640, save=True, save_period=10, cache=True, device=None, workers=8, project=yolov11_cv_s, name=fold5_of_5, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=True, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_cv_s/fold5_of_5
Overriding model.yaml nc=46 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2117209  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
Model summary: 129 layers, 11,136,761 parameters, 11,136,745 gradients, 28.7 GFLOPs

Transferred 349/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/labels... 4198 images, 0 backgrounds, 710 corrupt: 100%|██████████| 4198/4198 [00:12<00:00, 338.31it/s]

train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AclybJ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0985      1.2153]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BsWVWD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1969      2.0294]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_CxIwDu.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0116]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_E1fISS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FTVHZk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FViv94.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1895]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FVssBB.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FWv6k7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.203]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FliLbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2589      1.6944]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_Fm1oY7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FqB8FS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_FtYRqz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      2.1906]
train: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/images/ID_G3zqaj.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2778]

train: New cache created: /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/train/labels.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (3.0GB RAM): 100%|██████████| 3488/3488 [00:17<00:00, 202.32it/s]
val: Scanning /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/labels... 1049 images, 0 backgrounds, 171 corrupt: 100%|██████████| 1049/1049 [00:04<00:00, 251.99it/s]

val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_AJD939.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Fk8aG8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1905      1.0218]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_H4OXlj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2447]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_HE0i5e.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0238      1.1726]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_HO3AY6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0693       1.107]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Hu5bbx.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_I6l3Un.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0893]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_IZi4V7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1392]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_IoJVUQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.121]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_J26p8u.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.311]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_J2r81g.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0314]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_J7tnt4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0231        1.13]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_JSqzdw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0372      1.1386]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_JgmF2n.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Jwrg8k.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_K7sW7v.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1082]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_KJ3Eoi.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_KRiWgS.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_KUHQ33.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2143]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Ka3eqp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2953]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Kc4tOK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.09      1.6478      1.0517]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_LHcSBa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3026]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_LS0Z3w.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1518]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_LZumGY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1118]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_LgBbkC.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2571]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_LloE1t.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2008      1.8417]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_M7eiBX.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_MF6HuC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33      1.2728]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_MI053H.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1464]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_MteM6m.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2972]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_NR0lmz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0737      1.2564       1.187      1.1562]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_NeGEym.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333      1.1921]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_O8Ii5s.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_ONksfR.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0513]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_OP42MI.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3353      1.7739]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_OSL1rX.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3085]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_OXuUNh.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_OjZmZ6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_OsqbyN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_PHLxKY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3194]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_PNIAem.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237      1.0959]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Q0OwpE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2445]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_QvzGVf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3194]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_R8cIaK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_RJlWB1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1991       1.084]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_RoWnbg.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3224]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_RqYOYV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1918]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_SKn5NV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_SN7JMf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0463      1.1217]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_SP2AnQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1531]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Sl2Cxf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1971]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_SttpR2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237      1.1624]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_T3xeiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2477]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_T65cSF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.6828]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_TVfwF3.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_TXuZKp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.12]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Toahmq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0825      1.0354]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_U5jOiU.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_UG2EuT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1062]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_UHZrX6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2226]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_UTr8xI.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0661]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_UhR2o3.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_UlIb07.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0175]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_VTnQu1.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_VcsT8o.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2923      1.1022]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_WmaGX7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.051]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_WwcVSZ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2034]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Xt5H4P.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0923]
val: WARNING ⚠️ /home/jason-server/Documents/amini_cocoa_contamination/yolo_dataset_kfold_normed/fold5/val/images/ID_Yk0ckr.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.045]

WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.8GB RAM): 100%|██████████| 878/878 [00:04<00:00, 210.36it/s]

Plotting labels to yolov11_cv_s/fold5_of_5/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_cv_s/fold5_of_5
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/20      13.3G      1.313      2.162      1.724        141        640: 100%|██████████| 55/55 [00:17<00:00,  3.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.20it/s]

                   all        878       1592      0.587      0.457      0.467      0.261

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/20      17.8G      1.277      1.426      1.591        124        640: 100%|██████████| 55/55 [00:17<00:00,  3.22it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.27it/s]

                   all        878       1592      0.393       0.44       0.37      0.171

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/20      17.8G      1.275      1.382      1.589        128        640: 100%|██████████| 55/55 [00:17<00:00,  3.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.30it/s]

                   all        878       1592      0.513      0.435      0.412      0.226

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/20      17.8G      1.265      1.347      1.576        136        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.29it/s]

                   all        878       1592      0.381      0.449      0.361      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/20      17.8G      1.226      1.277       1.55        135        640: 100%|██████████| 55/55 [00:16<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.38it/s]

                   all        878       1592      0.417      0.442      0.323      0.142

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/20      17.8G      1.158      1.171      1.498        146        640: 100%|██████████| 55/55 [00:17<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.29it/s]

                   all        878       1592       0.54      0.506      0.465      0.238

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/20      17.8G      1.113      1.089      1.462        145        640: 100%|██████████| 55/55 [00:16<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.31it/s]

                   all        878       1592      0.579      0.542      0.528        0.3

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/20      17.8G      1.054      1.007      1.419        130        640: 100%|██████████| 55/55 [00:17<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.21it/s]

                   all        878       1592      0.618      0.514      0.508      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/20      17.8G       1.02      0.974      1.389        135        640: 100%|██████████| 55/55 [00:17<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.04it/s]

                   all        878       1592      0.616      0.549      0.558      0.333

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/20      17.8G     0.9607     0.9013      1.346        153        640: 100%|██████████| 55/55 [00:17<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.34it/s]

                   all        878       1592      0.629      0.536      0.542      0.319

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/20      17.8G      1.297      1.274      1.709         50        640: 100%|██████████| 55/55 [00:18<00:00,  3.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.28it/s]

                   all        878       1592      0.648      0.513      0.578      0.352

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/20      17.9G      1.222      1.178      1.638         64        640: 100%|██████████| 55/55 [00:16<00:00,  3.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.38it/s]

                   all        878       1592      0.709      0.584      0.658      0.416

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/20      17.9G      1.188      1.108      1.608         66        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        878       1592      0.687      0.613      0.663      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/20      17.9G       1.15      1.044      1.578         68        640: 100%|██████████| 55/55 [00:16<00:00,  3.26it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.45it/s]

                   all        878       1592      0.757      0.611      0.703       0.46

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/20        18G      1.108     0.9939      1.536         49        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.43it/s]

                   all        878       1592       0.74      0.589      0.692      0.444

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/20        18G       1.08     0.9477      1.509         65        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.44it/s]

                   all        878       1592      0.739      0.607      0.698      0.462

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/20        18G      1.044     0.9152      1.483         55        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.38it/s]

                   all        878       1592      0.701      0.654      0.711      0.471

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/20      18.1G      1.022     0.8783      1.466         58        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.43it/s]

                   all        878       1592      0.754      0.611      0.706      0.466

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/20      18.1G     0.9991     0.8545      1.443         43        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.43it/s]

                   all        878       1592      0.723      0.628      0.703      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/20      18.1G     0.9877     0.8369      1.442         54        640: 100%|██████████| 55/55 [00:16<00:00,  3.27it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.40it/s]

                   all        878       1592      0.711      0.633      0.706      0.467

20 epochs completed in 0.116 hours.
Optimizer stripped from yolov11_cv_s/fold5_of_5/weights/last.pt, 22.5MB
Optimizer stripped from yolov11_cv_s/fold5_of_5/weights/best.pt, 22.5MB

Validating yolov11_cv_s/fold5_of_5/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
Model summary (fused): 72 layers, 11,126,745 parameters, 0 gradients, 28.4 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.70it/s]

                   all        878       1592        0.7      0.655      0.711      0.471
               healthy        243        634      0.633      0.632      0.665       0.42
           anthracnose        208        335      0.742      0.661      0.744      0.497
                 cssvd        427        623      0.724      0.673      0.723      0.496
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 0.9ms postprocess per image
Results saved to yolov11_cv_s/fold5_of_5
Fold 5 mAP50: 0.7108

==================================================
Cross-Validation Results
==================================================
Mean mAP50: 0.7035
Standard Deviation: 0.0091
Best Fold: 5 (mAP50: 0.7108)
Results saved to: yolo_dataset_kfold_normed/cv_results_20250327_004046.json

In [45]:
cv_results

{'folds': [{'fold': 1,
   'map50': 0.7097250065108804,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold1.yaml',
   'model_path': 'yolov11_cv_s/fold1_of_5/weights/best.pt'},
  {'fold': 2,
   'map50': 0.7014380407234279,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold2.yaml',
   'model_path': 'yolov11_cv_s/fold2_of_5/weights/best.pt'},
  {'fold': 3,
   'map50': 0.6866092215552629,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold3.yaml',
   'model_path': 'yolov11_cv_s/fold3_of_5/weights/best.pt'},
  {'fold': 4,
   'map50': 0.7090942802995972,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold4.yaml',
   'model_path': 'yolov11_cv_s/fold4_of_5/weights/best.pt'},
  {'fold': 5,
   'map50': 0.7107842119610798,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold5.yaml',
   'model_path': 'yolov11_cv_s/fold5_of_5/weights/best.pt'}],
 'mean_map50': 0.7035301522100496,
 'std_map50': 0.009084623809200736,
 'best_fold': 5,
 'best_map50': 0.7107842119610798,
 'model_size': 's',
 'epochs': 20,
 'batch_size': 64,
 'timestamp': '20250327_004046'}

In [6]:
cv_results = {'folds': [{'fold': 1,
   'map50': 0.7097250065108804,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold1.yaml',
   'model_path': 'yolov11_cv_s/fold1_of_5/weights/best.pt'},
  {'fold': 2,
   'map50': 0.7014380407234279,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold2.yaml',
   'model_path': 'yolov11_cv_s/fold2_of_5/weights/best.pt'},
  {'fold': 3,
   'map50': 0.6866092215552629,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold3.yaml',
   'model_path': 'yolov11_cv_s/fold3_of_5/weights/best.pt'},
  {'fold': 4,
   'map50': 0.7090942802995972,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold4.yaml',
   'model_path': 'yolov11_cv_s/fold4_of_5/weights/best.pt'},
  {'fold': 5,
   'map50': 0.7107842119610798,
   'yaml_path': 'yolo_dataset_kfold_normed/dataset_fold5.yaml',
   'model_path': 'yolov11_cv_s/fold5_of_5/weights/best.pt'}],
 'mean_map50': 0.7035301522100496,
 'std_map50': 0.009084623809200736,
 'best_fold': 5,
 'best_map50': 0.7107842119610798,
 'model_size': 's',
 'epochs': 20,
 'batch_size': 64,
 'timestamp': '20250327_004046'}

In [7]:
TEST_IMAGES_DIR

PosixPath('dataset/images/test')

# Ensemble the predictions of the 5 seperate yolo models

In [25]:
def ensemble_kfold_models_optimized(cv_results, output_dir='yolo_dataset', test_images_dir=None, 
                               conf_threshold=0.25, iou_threshold=0.45):
    """
    Create an ensemble of k-fold models for inference, loading only one model at a time to save memory.
    
    Args:
        cv_results: cross-validation results from train_kfold_yolov11
        output_dir: directory containing the YOLO format dataset
        test_images_dir: directory containing test images (if None, uses validation set from best fold)
        conf_threshold: confidence threshold for detections
        iou_threshold: IoU threshold for NMS
        
    Returns:
        Ensemble prediction results
    """
    from ultralytics import YOLO
    import os
    import pandas as pd
    import json
    from datetime import datetime
    import gc
    import torch
    
    print(f"\n{'='*50}")
    print(f"Creating Memory-Optimized Model Ensemble from K-Fold Models")
    print(f"{'='*50}")
    
    # Get model paths
    model_paths = []
    for fold_info in cv_results['folds']:
        model_path = fold_info['model_path']
        if os.path.exists(model_path):
            print(f"Found model from fold {fold_info['fold']}: {model_path}")
            model_paths.append((fold_info['fold'], model_path))
        else:
            print(f"WARNING: Model not found for fold {fold_info['fold']}: {model_path}")
    
    if len(model_paths) == 0:
        raise ValueError("No models found for ensemble.")
    
    # Determine test images directory
    if test_images_dir is None:
        best_fold = cv_results['best_fold']
        best_fold_yaml = cv_results['folds'][best_fold - 1]['yaml_path']
        
        # Load YAML config to get validation data path
        with open(best_fold_yaml, 'r') as f:
            import yaml
            config = yaml.safe_load(f)
            base_path = config['path']
            val_path = os.path.join(base_path, config['val'])
            test_images_dir = val_path
    
    print(f"Running ensemble inference on: {test_images_dir}")
    
    # Create output directory for ensemble predictions
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S") if "timestamp" not in cv_results else cv_results["timestamp"]
    ensemble_dir = os.path.join(output_dir, f'ensemble_{timestamp}')
    os.makedirs(ensemble_dir, exist_ok=True)
    
    # Get list of all test images to ensure we process each image once
    import glob
    test_image_paths = glob.glob(os.path.join(test_images_dir, '*.jpg')) + \
                        glob.glob(os.path.join(test_images_dir, '*.jpeg')) + \
                        glob.glob(os.path.join(test_images_dir, '*.png'))
    
    # Extract base filenames to track which images have been processed
    all_image_names = [os.path.basename(path) for path in test_image_paths]
    print(f"Found {len(all_image_names)} images in test directory")
    
    # Prepare storage for all predictions
    ensemble_predictions = []
    processed_images = set()
    
    # Process each model individually
    for fold_idx, model_path in model_paths:
        print(f"\nRunning predictions with model from fold {fold_idx}")
        
        # Load model
        model = YOLO(model_path)
        
        # Run predictions with current model
        results = model.predict(
            source=test_images_dir,
            conf=conf_threshold,
            iou=iou_threshold,
            save=False,
            save_txt=False,
            verbose=False
        )
        
        # Extract predictions from current model results
        print(f"Processing predictions from fold {fold_idx}...")
        class_names = model.names  # Get class names from the model
        
        for result in results:
            img_name = os.path.basename(result.path)
            
            # Extract predictions
            if len(result.boxes) > 0:
                for box in result.boxes:
                    x1, y1, x2, y2 = box.xyxy[0].tolist()
                    conf = box.conf.item()
                    cls = int(box.cls.item())
                    class_name = class_names[cls]
                    
                    ensemble_predictions.append({
                        'image_name': img_name,
                        'class': class_name,
                        'confidence': conf,
                        'xmin': x1,
                        'ymin': y1,
                        'xmax': x2,
                        'ymax': y2,
                        'model_fold': fold_idx
                    })
                    
                    processed_images.add(img_name)
        
        # Clear GPU memory for the current model
        del model
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()
        print(f"Completed processing model from fold {fold_idx}")
    
    # Create DataFrame and save results
    if ensemble_predictions:
        pred_df = pd.DataFrame(ensemble_predictions)
        
        # Create a DataFrame with all images (including those without predictions)
        all_images_df = pd.DataFrame({'image_name': all_image_names})
        
        # Check which images have no predictions
        images_with_predictions = set(pred_df['image_name'].unique())
        missing_images = set(all_image_names) - images_with_predictions
        
        # If there are images without predictions, add placeholder rows with NaN values
        if missing_images:
            print(f"Adding {len(missing_images)} images with no predictions to the results")
            missing_rows = []
            for img_name in missing_images:
                # Add a row with NaN values for each missing image
                missing_row = {
                    'image_name': img_name,
                    'class': None,
                    'confidence': np.nan,
                    'xmin': np.nan,
                    'ymin': np.nan,
                    'xmax': np.nan,
                    'ymax': np.nan,
                    'model_fold': np.nan
                }
                missing_rows.append(missing_row)
            
            # Combine with existing predictions
            if missing_rows:
                missing_df = pd.DataFrame(missing_rows)
                pred_df = pd.concat([pred_df, missing_df], ignore_index=True)
        
        # Save the complete prediction results
        predictions_path = os.path.join(ensemble_dir, 'ensemble_predictions.csv')
        pred_df.to_csv(predictions_path, index=False)
        
        # Generate summary statistics and save
        image_count = len(all_image_names)
        images_with_detections = len(images_with_predictions)
        prediction_count = len(ensemble_predictions)
        model_count = len(model_paths)
        
        # Group by image and class for ensemble consensus
        pred_df['detection_count'] = 1
        ensemble_summary = pred_df.groupby(['image_name', 'class']).agg({
            'confidence': ['mean', 'max', 'count'],
            'detection_count': 'sum'
        }).reset_index()
        
        # Flatten the column hierarchy
        ensemble_summary.columns = ['_'.join(col).strip('_') for col in ensemble_summary.columns.values]
        
        # Save ensemble summary
        ensemble_summary_path = os.path.join(ensemble_dir, 'ensemble_detection_summary.csv')
        ensemble_summary.to_csv(ensemble_summary_path, index=False)
        
        # Overall summary
        summary = {
            'timestamp': timestamp,
            'models_used': model_count,
            'images_processed': image_count,
            'images_with_detections': images_with_detections,
            'images_without_detections': len(missing_images),
            'total_predictions': prediction_count,
            'average_predictions_per_detected_image': prediction_count / max(1, images_with_detections),
            'average_predictions_per_all_images': prediction_count / max(1, image_count),
            'conf_threshold': conf_threshold,
            'iou_threshold': iou_threshold,
            'memory_optimized': True
        }
        
        summary_path = os.path.join(ensemble_dir, 'ensemble_summary.json')
        with open(summary_path, 'w') as f:
            json.dump(summary, f, indent=2)
        
        print(f"\n{'='*50}")
        print(f"Ensemble Results")
        print(f"{'='*50}")
        print(f"Ensemble predictions saved to: {predictions_path}")
        print(f"Detection summary saved to: {ensemble_summary_path}")
        print(f"Processed {image_count} total images:")
        print(f"  - {images_with_detections} images with detections")
        print(f"  - {len(missing_images)} images with no detections (included in results with NaN values)")
        print(f"Total of {prediction_count} detections across all images and models")
        print(f"Used {model_count} models in the ensemble")
    else:
        print("No predictions generated by the ensemble.")
    
    return ensemble_predictions


def perform_ensemble_post_processing(predictions_path, output_dir=None, 
                                    confidence_threshold=0.5, 
                                    model_agreement_threshold=0.5,
                                    nms_iou_threshold=0.5):
    """
    Perform post-processing on ensemble predictions to combine overlapping detections.
    
    Args:
        predictions_path: path to the ensemble_predictions.csv file
        output_dir: directory to save post-processed results (defaults to same directory as predictions)
        confidence_threshold: minimum confidence threshold for final detections
        model_agreement_threshold: minimum fraction of models that must agree on a detection
        nms_iou_threshold: IoU threshold for non-maximum suppression
        
    Returns:
        DataFrame of post-processed predictions
    """
    import pandas as pd
    import numpy as np
    import os
    from datetime import datetime
    import json
    
    print(f"\n{'='*50}")
    print(f"Performing Ensemble Post-Processing")
    print(f"{'='*50}")
    
    # Load predictions
    pred_df = pd.read_csv(predictions_path)
    
    if len(pred_df) == 0:
        print("No predictions to process.")
        return pd.DataFrame()
    
    # Create output directory if not provided
    if output_dir is None:
        output_dir = os.path.dirname(predictions_path)
    
    # Count total number of models
    total_models = pred_df['model_fold'].nunique()
    
    # Group by image
    image_names = pred_df['image_name'].unique()
    
    # Prepare storage for post-processed results
    final_predictions = []
    
    # Define NMS function (Non-Maximum Suppression)
    def non_max_suppression(boxes, scores, iou_threshold):
        """
        Apply non-maximum suppression to boxes with scores.
        
        Args:
            boxes: list of [xmin, ymin, xmax, ymax]
            scores: confidence scores
            iou_threshold: IoU threshold for suppression
            
        Returns:
            Indices of boxes to keep
        """
        if len(boxes) == 0:
            return []
            
        # Convert to numpy arrays
        boxes = np.array(boxes)
        scores = np.array(scores)
        
        # Get indices of boxes sorted by score in descending order
        indices = np.argsort(scores)[::-1]
        
        keep = []
        while indices.size > 0:
            # Get index of highest scoring box
            i = indices[0]
            keep.append(i)
            
            # Calculate IoU of the highest scoring box with all other boxes
            ious = []
            for j in indices[1:]:
                # Calculate intersection area
                xx1 = max(boxes[i][0], boxes[j][0])
                yy1 = max(boxes[i][1], boxes[j][1])
                xx2 = min(boxes[i][2], boxes[j][2])
                yy2 = min(boxes[i][3], boxes[j][3])
                
                w = max(0, xx2 - xx1)
                h = max(0, yy2 - yy1)
                intersection = w * h
                
                # Calculate union area
                box1_area = (boxes[i][2] - boxes[i][0]) * (boxes[i][3] - boxes[i][1])
                box2_area = (boxes[j][2] - boxes[j][0]) * (boxes[j][3] - boxes[j][1])
                union = box1_area + box2_area - intersection
                
                iou = intersection / union if union > 0 else 0
                ious.append(iou)
            
            # Keep boxes with IoU less than threshold
            indices = indices[1:][np.array(ious) < iou_threshold]
            
        return keep
    
    # Process each image
    for img_name in image_names:
        img_preds = pred_df[pred_df['image_name'] == img_name]
        
        # Process each class separately
        for class_name in img_preds['class'].unique():
            class_preds = img_preds[img_preds['class'] == class_name]
            
            # Get boxes and scores
            boxes = class_preds[['xmin', 'ymin', 'xmax', 'ymax']].values.tolist()
            scores = class_preds['confidence'].values.tolist()
            model_ids = class_preds['model_fold'].values.tolist()
            
            # Apply NMS
            keep_indices = non_max_suppression(boxes, scores, nms_iou_threshold)
            
            # Process each cluster of detections
            for idx in keep_indices:
                box = boxes[idx]
                score = scores[idx]
                model_id = model_ids[idx]
                
                # Find overlapping detections from other models
                overlapping_models = set([model_id])
                overlapping_scores = [score]
                
                for i, other_box in enumerate(boxes):
                    if i != idx:
                        # Calculate IoU
                        xx1 = max(box[0], other_box[0])
                        yy1 = max(box[1], other_box[1])
                        xx2 = min(box[2], other_box[2])
                        yy2 = min(box[3], other_box[3])
                        
                        w = max(0, xx2 - xx1)
                        h = max(0, yy2 - yy1)
                        intersection = w * h
                        
                        box1_area = (box[2] - box[0]) * (box[3] - box[1])
                        box2_area = (other_box[2] - other_box[0]) * (other_box[3] - other_box[1])
                        union = box1_area + box2_area - intersection
                        
                        iou = intersection / union if union > 0 else 0
                        
                        if iou > nms_iou_threshold:
                            overlapping_models.add(model_ids[i])
                            overlapping_scores.append(scores[i])
                
                # Calculate model agreement
                model_agreement = len(overlapping_models) / total_models
                
                # Calculate weighted box coordinates
                if len(overlapping_scores) > 1:
                    # First collect all indices of overlapping boxes
                    overlapping_indices = [idx]
                    for j in range(len(boxes)):
                        if j != idx and model_ids[j] in overlapping_models:
                            overlapping_indices.append(j)
                    
                    # Now weights and indices have matching sizes
                    weights = np.array(overlapping_scores) / sum(overlapping_scores)
                    weighted_box = np.zeros(4)
                    
                    # Make sure we don't go out of bounds
                    for i in range(min(len(weights), len(overlapping_indices))):
                        other_idx = overlapping_indices[i]
                        weighted_box += weights[i] * np.array(boxes[other_idx])
                    
                    final_box = weighted_box.tolist()
                else:
                    final_box = box
                
                # Calculate average confidence
                avg_confidence = sum(overlapping_scores) / len(overlapping_scores)
                
                # Add to final predictions if meets thresholds
                if avg_confidence >= confidence_threshold and model_agreement >= model_agreement_threshold:
                    final_predictions.append({
                        'image_name': img_name,
                        'class': class_name,
                        'confidence': avg_confidence,
                        'xmin': final_box[0],
                        'ymin': final_box[1],
                        'xmax': final_box[2],
                        'ymax': final_box[3],
                        'model_agreement': model_agreement,
                        'models_detected': len(overlapping_models),
                        'total_models': total_models
                    })
    
    # Create DataFrame of final predictions
    final_df = pd.DataFrame(final_predictions)
    
    if len(final_df) > 0:
        # Save post-processed results
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = os.path.join(output_dir, f'ensemble_postprocessed_{timestamp}.csv')
        final_df.to_csv(output_path, index=False)
        
        # Save summary
        summary = {
            'timestamp': timestamp,
            'original_predictions': len(pred_df),
            'final_predictions': len(final_df),
            'images_processed': len(image_names),
            'confidence_threshold': confidence_threshold,
            'model_agreement_threshold': model_agreement_threshold,
            'nms_iou_threshold': nms_iou_threshold
        }
        
        summary_path = os.path.join(output_dir, f'postprocessing_summary_{timestamp}.json')
        with open(summary_path, 'w') as f:
            json.dump(summary, f, indent=2)
        
        print(f"Post-processing complete:")
        print(f"  - Original predictions: {len(pred_df)}")
        print(f"  - Final predictions: {len(final_df)}")
        print(f"  - Reduction: {(1 - len(final_df) / len(pred_df)) * 100:.1f}%")
        print(f"Post-processed results saved to: {output_path}")
    else:
        print("No predictions met the threshold criteria after post-processing.")
    
    return final_df

In [29]:
import numpy as np
# Run memory-optimized ensemble predictions
predictions = ensemble_kfold_models_optimized(
    test_images_dir=TEST_IMAGES_DIR,
    cv_results=cv_results,
    conf_threshold=0.3,
    iou_threshold=0.5
)

==================================================
Creating Memory-Optimized Model Ensemble from K-Fold Models
==================================================
Found model from fold 1: yolov11_cv_s/fold1_of_5/weights/best.pt
Found model from fold 2: yolov11_cv_s/fold2_of_5/weights/best.pt
Found model from fold 3: yolov11_cv_s/fold3_of_5/weights/best.pt
Found model from fold 4: yolov11_cv_s/fold4_of_5/weights/best.pt
Found model from fold 5: yolov11_cv_s/fold5_of_5/weights/best.pt
Running ensemble inference on: dataset/images/test
Found 1545 images in test directory

Running predictions with model from fold 1

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

Processing predictions from fold 1...
Completed processing model from fold 1

Running predictions with model from fold 2

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

Processing predictions from fold 2...
Completed processing model from fold 2

Running predictions with model from fold 3

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

Processing predictions from fold 3...
Completed processing model from fold 3

Running predictions with model from fold 4

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

Processing predictions from fold 4...
Completed processing model from fold 4

Running predictions with model from fold 5

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

Processing predictions from fold 5...
Completed processing model from fold 5
Adding 22 images with no predictions to the results

==================================================
Ensemble Results
==================================================
Ensemble predictions saved to: yolo_dataset/ensemble_20250327_004046/ensemble_predictions.csv
Detection summary saved to: yolo_dataset/ensemble_20250327_004046/ensemble_detection_summary.csv
Processed 1545 total images:
  - 1600 images with detections
  - 22 images with no detections (included in results with NaN values)
Total of 12280 detections across all images and models
Used 5 models in the ensemble

In [30]:
all_preds = pd.DataFrame(predictions)
all_preds

,image_name,class,confidence,xmin,ymin,xmax,ymax,model_fold
0,ID_A16nzu.jpg,healthy,0.566845,36.285217,1.956055,950.594543,1273.466553,1
1,ID_A1Euyz.jpg,anthracnose,0.578857,202.237793,96.265869,960.000000,1177.578125,1
2,ID_A1HcV0.jpeg,anthracnose,0.428156,0.000000,119.089760,1483.036377,2576.906738,1
3,ID_A1HcV0.jpeg,anthracnose,0.381752,920.264099,702.710693,2737.285156,3646.960693,1
4,ID_A4ZdJC.jpeg,healthy,0.817828,190.853378,506.534729,2102.094482,4032.000000,1
...,...,...,...,...,...,...,...,...
12275,ID_zyGKPp.jpg,healthy,0.759476,150.393234,103.659218,407.861206,395.058594,5
12276,ID_zyGKPp.jpg,healthy,0.598116,61.712185,163.236160,193.795959,278.837616,5
12277,ID_zyGKPp.jpg,healthy,0.451195,170.110748,266.946594,346.539490,416.000000,5
12278,ID_zyGKPp.jpg,healthy,0.433990,0.000000,42.175117,186.289658,119.743858,5
12279,ID_zzaEcN.jpg,cssvd,0.830887,462.525970,434.114960,989.716980,1036.803589,5

In [31]:
all_preds.to_csv('ensemble_predictions_full.csv', index=False)

In [32]:

# Optionally perform post-processing
final_predictions = perform_ensemble_post_processing(
    predictions_path='ensemble_predictions_full.csv',
    confidence_threshold=0.5,
    model_agreement_threshold=0.6
)

==================================================
Performing Ensemble Post-Processing
==================================================
Post-processing complete:
  - Original predictions: 12280
  - Final predictions: 1866
  - Reduction: 84.8%
Post-processed results saved to: ensemble_postprocessed_20250327_021323.csv

In [33]:
final_predictions

,image_name,class,confidence,xmin,ymin,xmax,ymax,model_agreement,models_detected,total_models
0,ID_A1Euyz.jpg,anthracnose,0.558646,229.457665,143.588281,954.824534,1127.295466,1.0,5,5
1,ID_A4ZdJC.jpeg,healthy,0.797487,247.039530,544.262788,2123.140444,4022.334657,1.0,5,5
2,ID_A5SFUW.jpeg,healthy,0.792499,2.588243,0.967714,2958.226951,3920.471061,1.0,5,5
3,ID_A6Fogi.jpeg,anthracnose,0.644492,98.525042,695.970105,1799.773773,3758.698279,1.0,5,5
4,ID_ABDCyn.jpeg,healthy,0.551010,1092.177790,513.686408,2754.097126,3330.295801,0.8,4,5
...,...,...,...,...,...,...,...,...,...,...
1861,ID_aY2yXb.jpg,anthracnose,0.720392,922.502131,16.979998,3061.476089,4125.783156,0.8,4,5
1862,ID_ewBCM4.jpg,cssvd,0.558495,61.168331,1.512597,725.799264,1079.847279,0.6,3,5
1863,ID_hcfuoO.JPG,anthracnose,0.540795,747.013720,725.660290,1843.741420,2750.976499,0.6,3,5
1864,ID_mHoDGw.JPG,healthy,0.578414,1.084853,1341.693102,1713.892420,3262.127072,0.6,3,5
1865,ID_wSnNtD.JPG,healthy,0.522623,223.664584,2.700621,1702.557678,3263.736867,0.6,3,5