In [1]:
import os
import sys
sys.path.append("../") # go to parent dir
%load_ext autoreload
%autoreload 2

In [24]:
from functions.loading_functions import *
train_df = get_dataset("train")
train_df

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath
0,ID_nBgcAR.jpg,healthy,1.0,75.0,15.0,162.0,195.0,2,dataset/images/train/ID_nBgcAR.jpg
1,ID_nBgcAR.jpg,healthy,1.0,58.0,1.0,133.0,171.0,2,dataset/images/train/ID_nBgcAR.jpg
2,ID_nBgcAR.jpg,healthy,1.0,42.0,29.0,377.0,349.0,2,dataset/images/train/ID_nBgcAR.jpg
3,ID_Kw2v8A.jpg,healthy,1.0,112.0,124.0,404.0,341.0,2,dataset/images/train/ID_Kw2v8A.jpg
4,ID_Kw2v8A.jpg,healthy,1.0,148.0,259.0,413.0,412.0,2,dataset/images/train/ID_Kw2v8A.jpg
...,...,...,...,...,...,...,...,...,...
9787,ID_WULBQy.jpeg,anthracnose,1.0,136.0,1440.0,1593.0,4000.0,0,dataset/images/train/ID_WULBQy.jpeg
9788,ID_WULBQy.jpeg,anthracnose,1.0,89.0,0.0,1174.0,1139.0,0,dataset/images/train/ID_WULBQy.jpeg
9789,ID_SVzl5X.jpeg,anthracnose,1.0,18.0,360.0,1800.0,2330.0,0,dataset/images/train/ID_SVzl5X.jpeg
9790,ID_xDTIEp.jpeg,anthracnose,1.0,736.0,174.0,2691.0,4032.0,0,dataset/images/train/ID_xDTIEp.jpeg
9791,ID_VyjCJQ.jpeg,anthracnose,1.0,57.0,1248.0,2735.0,2323.0,0,dataset/images/train/ID_VyjCJQ.jpeg

In [46]:
train_df

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath
0,ID_nBgcAR.jpg,healthy,1.0,75.0,15.0,162.0,195.0,2,dataset/images/train/ID_nBgcAR.jpg
1,ID_nBgcAR.jpg,healthy,1.0,58.0,1.0,133.0,171.0,2,dataset/images/train/ID_nBgcAR.jpg
2,ID_nBgcAR.jpg,healthy,1.0,42.0,29.0,377.0,349.0,2,dataset/images/train/ID_nBgcAR.jpg
3,ID_Kw2v8A.jpg,healthy,1.0,112.0,124.0,404.0,341.0,2,dataset/images/train/ID_Kw2v8A.jpg
4,ID_Kw2v8A.jpg,healthy,1.0,148.0,259.0,413.0,412.0,2,dataset/images/train/ID_Kw2v8A.jpg
...,...,...,...,...,...,...,...,...,...
9787,ID_WULBQy.jpeg,anthracnose,1.0,136.0,1440.0,1593.0,4000.0,0,dataset/images/train/ID_WULBQy.jpeg
9788,ID_WULBQy.jpeg,anthracnose,1.0,89.0,0.0,1174.0,1139.0,0,dataset/images/train/ID_WULBQy.jpeg
9789,ID_SVzl5X.jpeg,anthracnose,1.0,18.0,360.0,1800.0,2330.0,0,dataset/images/train/ID_SVzl5X.jpeg
9790,ID_xDTIEp.jpeg,anthracnose,1.0,736.0,174.0,2691.0,4032.0,0,dataset/images/train/ID_xDTIEp.jpeg
9791,ID_VyjCJQ.jpeg,anthracnose,1.0,57.0,1248.0,2735.0,2323.0,0,dataset/images/train/ID_VyjCJQ.jpeg

In [29]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from PIL import Image
import shutil
import yaml
import torch

# Step 1: Process the original dataset and convert to YOLO format
def process_dataset(df, output_dir='yolo_dataset'):
    """
    Convert the original dataset format to YOLO format.
    
    Args:
        df: pandas DataFrame with columns ['Image_ID', 'class', 'confidence', 'ymin', 'xmin', 'ymax', 'xmax', 'class_id', 'ImagePath']
        output_dir: directory to save the YOLO format dataset
    """
    # Create necessary directories
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, 'images'), exist_ok=True)
    os.makedirs(os.path.join(output_dir, 'labels'), exist_ok=True)
    
    # Get unique classes and create class mapping
    classes = df['class'].unique().tolist()
    class_to_id = {class_name: i for i, class_name in enumerate(classes)}
    
    # Save the class mapping to a file
    with open(os.path.join(output_dir, 'classes.txt'), 'w') as f:
        for class_name in classes:
            f.write(f"{class_name}\n")
    
    # Process each image
    processed_images = set()
    for _, row in df.iterrows():
        img_path = row['ImagePath']
        img_id = row['Image_ID']
        
        # Skip if we've already processed this image
        if img_id in processed_images:
            continue
        
        # Copy the image to the YOLO dataset
        dst_img_path = os.path.join(output_dir, 'images', img_id)
        shutil.copy(img_path, dst_img_path)
        
        # Create a label file for this image
        label_filename = img_id.split(".")[0]+".txt"
        label_path = os.path.join(output_dir, 'labels', label_filename)
        
        # Get all annotations for this image
        img_annotations = df[df['Image_ID'] == img_id].copy()
        
        # Open the image to get dimensions
        with Image.open(img_path) as img:
            img_width, img_height = img.size
        
        # Write annotations in YOLO format
        with open(label_path, 'w') as f:
            for _, ann in img_annotations.iterrows():
                # Convert bbox coordinates to YOLO format (normalized center x, center y, width, height)
                x_min, y_min = ann['xmin'], ann['ymin']
                x_max, y_max = ann['xmax'], ann['ymax']
                
                # Normalize coordinates
                x_center = ((x_min + x_max) / 2) / img_width
                y_center = ((y_min + y_max) / 2) / img_height
                width = (x_max - x_min) / img_width
                height = (y_max - y_min) / img_height
                
                # Get class ID
                class_id = class_to_id[ann['class']]
                
                # In case they are none
                # Write in YOLO format: class_id x_center y_center width height
                f.write(f"{class_id} {x_center} {y_center} {width} {height}\n")
        
        processed_images.add(img_id)
    
    print(f"Processed {len(processed_images)} images with {len(df)} annotations.")
    return classes

def split_dataset(output_dir='yolo_dataset', train_ratio=0.7, val_ratio=0.2, test_ratio=0.1):
    """
    Split the dataset into train, validation, and test sets.
    
    Args:
        output_dir: directory containing the YOLO format dataset
        train_ratio: ratio of training data
        val_ratio: ratio of validation data
        test_ratio: ratio of test data
    """
    # Get all image filenames
    image_dir = os.path.join(output_dir, 'images')
    all_images = [f for f in os.listdir(image_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    # Create train, val, test directories
    for split in ['train', 'val', 'test']:
        for subdir in ['images', 'labels']:
            os.makedirs(os.path.join(output_dir, split, subdir), exist_ok=True)
    
    # Split the dataset
    train_images, temp_images = train_test_split(all_images, train_size=train_ratio, random_state=42)
    val_size = val_ratio / (val_ratio + test_ratio)
    val_images, test_images = train_test_split(temp_images, train_size=val_size, random_state=42)
    
    # Move files to respective directories
    for split, images in [('train', train_images), ('val', val_images), ('test', test_images)]:
        for img_file in images:
            # Get corresponding label file
            label_file = os.path.splitext(img_file)[0] + '.txt'
            
            # Move image
            src_img = os.path.join(output_dir, 'images', img_file)
            dst_img = os.path.join(output_dir, split, 'images', img_file)
            shutil.copy(src_img, dst_img)
            
            # Move label
            src_label = os.path.join(output_dir, 'labels', label_file)
            dst_label = os.path.join(output_dir, split, 'labels', label_file)
            if os.path.exists(src_label):  # Some images might not have annotations
                shutil.copy(src_label, dst_label)
    
    print(f"Dataset split: {len(train_images)} train, {len(val_images)} validation, {len(test_images)} test images.")

def create_yaml_config(classes, output_dir='yolo_dataset'):
    """
    Create a YAML configuration file for YOLOv5.
    
    Args:
        classes: list of class names
        output_dir: directory containing the YOLO format dataset
    """
    config = {
        'path': os.path.abspath(output_dir),
        'train': 'train/images',
        'val': 'val/images',
        'test': 'test/images',
        'nc': len(classes),
        'names': classes
    }
    
    with open(os.path.join(output_dir, 'dataset.yaml'), 'w') as f:
        yaml.dump(config, f, default_flow_style=False)
    
    print(f"Created YAML configuration file at {os.path.join(output_dir, 'dataset.yaml')}")

# Step 2: Set up and train the YOLO model (YOLOv11)
def train_yolov11(dataset_yaml, model_name_path: str,  model_size='s', epochs=100, batch_size=16, image_size=640):
    """
    Train a YOLOv11 model.
    
    Args:
        dataset_yaml: path to the YAML configuration file
        model_size: YOLOv11 model size ('n', 's', 'm', 'l', 'x')
        epochs: number of training epochs
        batch_size: batch size
        image_size: input image size
    """
    # Install Ultralytics package (which includes YOLOv11)
    os.system('pip install ultralytics')
    
    # Start training with YOLOv11
    import ultralytics
    from ultralytics import YOLO
    
    # Print Ultralytics version for reference
    print(f"Ultralytics version: {ultralytics.__version__}")
    
    # Load the base model
    model = YOLO(model_name_path)
    
    # Train the model using the dataset YAML config
    model.train(
        data=dataset_yaml,
        epochs=epochs,
        batch=batch_size,
        device=[0],  # List all GPU indices to use
        imgsz=image_size,
        patience=50,  # Early stopping patience
        cache=True,
        project='yolov11_plant_detection',
        name=f'yolov11{model_size}_run1',
        save=True,    # Save best model
        pretrained=True,
        verbose=True
    )

# Step 3: Run inference on test images without bounding boxes
def run_inference(model_path, test_image_dir, output_dir='predictions', conf_threshold=0.25):
    """
    Run inference on test images using YOLOv11.
    
    Args:
        model_path: path to the trained YOLOv11 model
        test_image_dir: directory containing test images
        output_dir: directory to save prediction results
        conf_threshold: confidence threshold for detections
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Load model using Ultralytics YOLO
    from ultralytics import YOLO
    model = YOLO(model_path)
    
    # Set confidence threshold
    # Note: In YOLOv11, this is done at prediction time
    
    # Run inference
    results = model.predict(
        source=test_image_dir,
        conf=conf_threshold,
        save=True,
        save_txt=True,
        save_conf=True,
        project=output_dir,
        name='detect',
        verbose=True
    )
    
    # Export results to a CSV file
    predictions = []
    
    for result in results:
        img_name = os.path.basename(result.path)
        boxes = result.boxes
        
        if len(boxes) > 0:
            # Extract coordinates, confidence, and class
            for box in boxes:
                x1, y1, x2, y2 = box.xyxy[0].tolist()  # xyxy format (top-left, bottom-right)
                conf = box.conf.item()
                cls = int(box.cls.item())
                class_name = model.names[cls]
                
                predictions.append({
                    'image_name': img_name,
                    'class': class_name,
                    'confidence': conf,
                    'xmin': x1,
                    'ymin': y1,
                    'xmax': x2,
                    'ymax': y2
                })
    
    # Create DataFrame and save
    if predictions:
        pred_df = pd.DataFrame(predictions)
        pred_df.to_csv(os.path.join(output_dir, 'predictions.csv'), index=False)
    
    print(f"Inference complete. Results saved to {output_dir}")

# Step 4: Aggregate image-level predictions for multi-label evaluation
def aggregate_predictions(predictions_csv, output_csv='image_level_predictions.csv'):
    """
    Aggregate bounding box predictions to image-level class predictions.
    
    Args:
        predictions_csv: path to CSV file with bounding box predictions
        output_csv: path to save image-level predictions
    """
    # Load predictions
    pred_df = pd.read_csv(predictions_csv)
    
    # Group by image and aggregate classes
    image_level = pred_df.groupby('image_name')['class'].apply(lambda x: list(set(x))).reset_index()
    image_level.rename(columns={'class': 'predicted_classes'}, inplace=True)
    
    # Save to CSV
    image_level.to_csv(output_csv, index=False)
    
    print(f"Aggregated predictions saved to {output_csv}")

In [30]:
# Process dataset
classes = process_dataset(train_df)

Processed 5529 images with 9792 annotations.

In [32]:
split_dataset()

Dataset split: 3672 train, 1050 validation, 525 test images.

In [33]:
create_yaml_config(classes)

Created YAML configuration file at yolo_dataset/dataset.yaml

In [34]:
# Train model using YOLOv11
train_yolov11(dataset_yaml='yolo_dataset/dataset.yaml', model_name_path='yolo11s.pt', model_size='s', epochs=20, batch_size=64)

Requirement already satisfied: ultralytics in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (8.3.94)
Requirement already satisfied: numpy<=2.1.1,>=1.23.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (1.26.4)
Requirement already satisfied: matplotlib>=3.3.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (3.10.1)
Requirement already satisfied: opencv-python>=4.6.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (11.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.32.3)
Requirement already satisfied: scipy>=1.4.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (1.15.2)
Requirement already satisfied: torch>=1.8.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.6.0+cu118)
Requirement already satisfied: torchvision>=0.9.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (0.21.0+cu118)
Requirement already satisfied: tqdm>=4.64.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (4.67.1)
Requirement already satisfied: psutil in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (7.0.0)
Requirement already satisfied: py-cpuinfo in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.2.3)
Requirement already satisfied: seaborn>=0.11.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (0.13.2)
Requirement already satisfied: ultralytics-thop>=2.0.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from ultralytics) (2.0.14)
Requirement already satisfied: contourpy>=1.0.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from pandas>=1.1.4->ultralytics) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from requests>=2.23.0->ultralytics) (2025.1.31)
Requirement already satisfied: filelock in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (4.12.2)
Requirement already satisfied: networkx in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.3)
Requirement already satisfied: jinja2 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.1.4)
Requirement already satisfied: fsspec in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (11.8.86)
Requirement already satisfied: triton==3.2.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jason-server/Documents/deep_learning_aueb/.venv/lib/python3.10/site-packages (from jinja2->torch>=1.8.0->ultralytics) (2.1.5)
Ultralytics version: 8.3.94
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
engine/trainer: task=detect, mode=train, model=yolo11s.pt, data=yolo_dataset/dataset.yaml, epochs=20, time=None, patience=50, batch=64, imgsz=640, save=True, save_period=-1, cache=True, device=[0], workers=8, project=yolov11_plant_detection, name=yolov11s_run12, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=True, opset=None, workspace=None, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, copy_paste_mode=flip, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=yolov11_plant_detection/yolov11s_run12
Overriding model.yaml nc=80 with nc=3

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  3                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  4                  -1  1    103360  ultralytics.nn.modules.block.C3k2            [128, 256, 1, False, 0.25]
  5                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  6                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    443776  ultralytics.nn.modules.block.C3k2            [768, 256, 1, False]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    127680  ultralytics.nn.modules.block.C3k2            [512, 128, 1, False]
 17                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1    345472  ultralytics.nn.modules.block.C3k2            [384, 256, 1, False]
 20                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 23        [16, 19, 22]  1    820569  ultralytics.nn.modules.head.Detect           [3, [128, 256, 512]]
YOLO11s summary: 181 layers, 9,428,953 parameters, 9,428,937 gradients, 21.6 GFLOPs

Transferred 493/499 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅

train: Scanning /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/labels... 3672 images, 0 backgrounds, 599 corrupt: 100%|██████████| 3672/3672 [00:09<00:00, 379.41it/s]

train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AC3jGA.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2288      1.0926]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AIHFIo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AJD939.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AK7dFo.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3218      1.2725]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AMshRT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      1.4172]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AOtnot.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2302]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AWV6yV.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0357      1.2953]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AWYI8j.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2503]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AYKor4.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AbHMqL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AhmyiY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1158      2.2128]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AueB13.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3081]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Auh1dw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_AzJAHH.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_B9Cxd6.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BBZMEE.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1702]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BC1LIj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0274]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BFveJq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.7511]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BM1xwq.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3022]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BNWZ3w.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BOxTJS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2973]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BPKSU9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0136]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BQih4N.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917      1.1366]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BXIM9U.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0881      1.9361]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BerVLr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1305]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BiTMni.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3221]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BuRQDQ.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2136]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_BxCnJ3.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3001]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_C3ko9I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CAic9T.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2917]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CBsPdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2794]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CFmEKi.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3249]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CGTYfy.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CLsW8F.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3168]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CMh7eW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1716]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CYa4x1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.33]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CZ8gq9.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3251]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CZ9NxR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CaSTr4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2269]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Ce21GK.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2563]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cli5xi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0956]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CpGE6D.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3029]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cs62jn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2586]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Ct9Mtq.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2694]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_CtPzDh.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cxxlvg.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2494      1.9456]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Cy14fB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2234]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_D3pndw.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.248      1.2252]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_D8r1TO.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DEVBif.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2862]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DNHsfS.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.009]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DSclWF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2113]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DTKIsY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3138]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DUTjoc.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2381]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DUz0EB.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2262]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DYJbt2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2573]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DaIYdt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2103]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Dcoa03.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DlpzFE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2054]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_DvHXoM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.251]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Dvliuk.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1421]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EC1rSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EGdAT4.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1877]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EJWqGf.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EKiBSU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.328]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_ES2kxP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1528]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_ET34jY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3578      1.7289      1.2011         1.6]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EUJ6CX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0031]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EZslfU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EaLNks.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2669]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EkR0Yj.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1561]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EmMnKL.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EmWPmE.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_EpTEDW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3267]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_F0CtpD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3307]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_F0uO9z.jpeg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_F3BooT.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FBviFm.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FH5WPo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FMaedR.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FNLeWz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.032]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FQ67gN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2335]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FQh3F2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3208]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FTVHZk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FViv94.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1895]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FVssBB.jpg: corrupt JPEG restored and saved
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Fk8aG8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1905      1.0218]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FliLbi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2589      1.6944]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_Fm1oY7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FqB8FS.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_FtYRqz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1269      2.1906]
train: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/images/ID_G4peHX.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3237]

train: New cache created: /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/train/labels.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

train: Caching images (2.7GB RAM): 100%|██████████| 3073/3073 [00:14<00:00, 216.71it/s]
val: Scanning /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/labels... 1050 images, 0 backgrounds, 197 corrupt: 100%|██████████| 1050/1050 [00:05<00:00, 196.53it/s]

val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_AOGygM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3961]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_AhwlUp.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2867      1.8067]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_AyLOZm.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3201      1.0989]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_AzvfYH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.076]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_BTK2Bl.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1753]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_BdTmQk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2186]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_By57N4.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [       1.34]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_CSnvqV.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0246]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_D4JXep.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2718]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_DLUzP8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2649]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_DOTVrd.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3114]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_DhtQeo.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3278]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_EMyTir.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.292]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_ESQAmP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1067      2.0744]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_EVApJI.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2467]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_EqJVm9.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_F2ktyi.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1454]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_FFEXVC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3277]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_FHK3pa.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3283      1.3444]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_GA4ocU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1171]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_GWJUCD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2087]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_GWhiLp.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_GZeZQ7.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1696]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_H7QQ2I.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0672]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_HIFZij.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1217]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_IRWSPd.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3056]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_IwPsnt.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2923]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_J7hL2Y.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2668      1.1844]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_JltOLk.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2834      1.1822]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_KDq13B.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2144      2.0156]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_KTP6kp.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2061]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_KbaWjL.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1322        2.18]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_KkyQ36.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1244      2.1956]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_KoUDAP.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0119      1.2586]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_KqcXSY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1134      1.1291]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_L0K6CF.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0976]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_LLSZyI.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2784]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_LXBv1Y.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2679]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_LkJ8Zz.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0245]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_M1CmZf.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1022      1.2097      1.2515]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_M3NBS2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2065       1.322]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_MIeJvr.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1101      1.0147      1.1377]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_MPIvc5.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2351]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_MbZhzx.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2946]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Mio4o3.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0364]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Mmotno.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1119]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_N6uNo7.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0098      1.0694]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_N9A9JN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1496]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NGvzWH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0832]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NPQOoz.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.089]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NRkeOG.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0589]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Na6hR0.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0982]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NbU1Pn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1591]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NbftLH.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1064      1.2339]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NcA2qf.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0083]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NfmKR2.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.228]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Ng5Pt8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3006      1.1004]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NlJLXQ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.314]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_NuyEeD.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0397      1.2612]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_OkoEnN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2841]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Ot9lnj.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2057]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_OtEC7c.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3016]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_OwFJgN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3333]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_P2qCLW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2576]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_PDbzh1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.167]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_PIg9if.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2163       1.042]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_POD5HU.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3271]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_PQm2Ft.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0428]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_PlSJ3I.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.247]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_PqV4gW.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Q938mO.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2161]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_QitFhY.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1974]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Rfm919.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.289]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_S3A64w.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0642]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_SSGiW2.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.9108]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_SVzl5X.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_SnC6Z6.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_SuY5t1.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2561]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_T9Sifn.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2356      1.9733]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_T9n3Yk.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_TLVeAC.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0949]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_TOxurW.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1448]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_U8HUUd.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [      1.206]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_ULx8cJ.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2339]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_Uoy7f2.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.1481]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_UrKjY8.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3075       1.525]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_V42JvR.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_VwIYf0.jpg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_WB25bW.jpeg: corrupt JPEG restored and saved
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_WILdJN.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.3317      1.0202]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_WKcQeb.jpg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.0126]
val: WARNING ⚠️ /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/images/ID_WR3TUM.jpeg: ignoring corrupt image/label: non-normalized or out of bounds coordinates [     1.2209      1.0165]

val: New cache created: /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolo_dataset/val/labels.cache
WARNING ⚠️ cache='ram' may produce non-deterministic training results. Consider cache='disk' as a deterministic alternative if your disk space allows.

val: Caching images (0.7GB RAM): 100%|██████████| 853/853 [00:04<00:00, 208.44it/s]

Plotting labels to yolov11_plant_detection/yolov11s_run12/labels.jpg...
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.001429, momentum=0.9) with parameter groups 81 weight(decay=0.0), 88 weight(decay=0.0005), 87 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to yolov11_plant_detection/yolov11s_run12
Starting training for 20 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/20      18.1G      1.391      2.314      1.736          2        640: 100%|██████████| 49/49 [00:17<00:00,  2.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  1.95it/s]

                   all        853       1447      0.247      0.343      0.198     0.0856

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/20      18.2G      1.423       1.64      1.717          4        640: 100%|██████████| 49/49 [00:15<00:00,  3.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  1.91it/s]

                   all        853       1447     0.0264      0.168     0.0144    0.00491

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/20      18.2G      1.451       1.69      1.747          2        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:05<00:00,  1.36it/s]

                   all        853       1447     0.0617      0.138     0.0224    0.00712

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/20      18.2G      1.433      1.668      1.736          3        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  1.92it/s]

                   all        853       1447      0.224      0.251      0.137     0.0495

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/20      18.3G      1.391       1.57       1.69          8        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:03<00:00,  2.14it/s]

                   all        853       1447       0.43      0.411      0.306      0.133

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/20      18.3G       1.34       1.45      1.658          2        640: 100%|██████████| 49/49 [00:15<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.35it/s]

                   all        853       1447      0.541      0.473       0.47      0.258

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/20      18.4G      1.289      1.413      1.611          4        640: 100%|██████████| 49/49 [00:15<00:00,  3.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        853       1447      0.558      0.506      0.473      0.267

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/20      18.4G      1.257      1.325       1.59          3        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.37it/s]

                   all        853       1447      0.563      0.508      0.473       0.26

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/20      18.4G       1.21      1.255      1.532          3        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.34it/s]

                   all        853       1447       0.62      0.507      0.532      0.302

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/20      18.5G      1.167      1.173       1.51          6        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.36it/s]

                   all        853       1447      0.667      0.522      0.559      0.335

Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/20      18.5G       1.42      1.443      1.829          1        640: 100%|██████████| 49/49 [00:16<00:00,  2.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.38it/s]

                   all        853       1447      0.544      0.553      0.525      0.299

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/20      18.6G      1.338      1.316      1.755          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.47it/s]

                   all        853       1447      0.611      0.554       0.56       0.32

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/20      18.6G      1.267      1.223      1.679          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.35it/s]

                   all        853       1447      0.649      0.581      0.614      0.379

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/20      18.6G      1.226      1.251      1.654          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.38it/s]

                   all        853       1447      0.667      0.599      0.638      0.406

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/20      18.7G      1.204      1.151      1.626          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.16it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.40it/s]

                   all        853       1447      0.705      0.618      0.669       0.43

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/20      18.7G      1.176       1.13      1.607          2        640: 100%|██████████| 49/49 [00:15<00:00,  3.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.41it/s]

                   all        853       1447      0.692      0.638      0.675      0.436

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/20      18.8G      1.189      1.115      1.628          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.36it/s]

                   all        853       1447      0.722      0.649      0.685      0.449

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/20      18.8G      1.148      1.093      1.586          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.39it/s]

                   all        853       1447      0.745      0.628      0.705      0.459

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/20      18.8G      1.113      1.009      1.545          1        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.37it/s]

                   all        853       1447      0.727      0.638      0.691      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/20      18.9G      1.107     0.9789      1.524          3        640: 100%|██████████| 49/49 [00:15<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:02<00:00,  2.44it/s]

                   all        853       1447      0.737      0.646      0.698       0.47

20 epochs completed in 0.108 hours.
Optimizer stripped from yolov11_plant_detection/yolov11s_run12/weights/last.pt, 19.2MB
Optimizer stripped from yolov11_plant_detection/yolov11s_run12/weights/best.pt, 19.2MB

Validating yolov11_plant_detection/yolov11s_run12/weights/best.pt...
Ultralytics 8.3.94 🚀 Python-3.10.12 torch-2.6.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3090, 24253MiB)
YOLO11s summary (fused): 100 layers, 9,413,961 parameters, 0 gradients, 21.3 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 7/7 [00:04<00:00,  1.69it/s]

                   all        853       1447      0.737      0.646      0.698      0.469
               healthy        223        545      0.689      0.594      0.656      0.421
           anthracnose        219        330      0.713       0.63      0.663      0.433
                 cssvd        412        572      0.809      0.713      0.775      0.554
Speed: 0.1ms preprocess, 1.0ms inference, 0.0ms loss, 1.3ms postprocess per image
Results saved to yolov11_plant_detection/yolov11s_run12

In [35]:
import os
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import MaxNLocator
from pathlib import Path

def plot_yolo_performance(results_dir, output_dir='performance_plots'):
    """
    Generate comprehensive performance plots for YOLOv11 training results.
    
    Args:
        results_dir: Directory containing YOLO training results
        output_dir: Directory to save performance plots
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Check if it's Ultralytics format (YOLOv8/YOLOv11) or older YOLOv5 format
    results_csv = os.path.join(results_dir, 'results.csv')
    
    if os.path.exists(results_csv):
        # Newer Ultralytics format
        df = pd.read_csv(results_csv)
        
        # Check if we have precision-recall data
        if all(col in df.columns for col in ['precision', 'recall', 'mAP50', 'mAP50-95']):
            # Create figure with multiple subplots
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            fig.suptitle('YOLO Training Performance Metrics', fontsize=16)
            
            # Plot Loss curves
            ax = axes[0, 0]
            if 'box_loss' in df.columns and 'cls_loss' in df.columns:
                ax.plot(df['epoch'], df['box_loss'], label='Box Loss')
                ax.plot(df['epoch'], df['cls_loss'], label='Class Loss')
                if 'dfl_loss' in df.columns:  # YOLOv8/v11 specific
                    ax.plot(df['epoch'], df['dfl_loss'], label='DFL Loss')
            else:
                ax.plot(df['epoch'], df['train_loss'], label='Train Loss')
                if 'val_loss' in df.columns:
                    ax.plot(df['epoch'], df['val_loss'], label='Val Loss')
            
            ax.set_title('Training Losses')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Loss')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot Precision, Recall
            ax = axes[0, 1]
            ax.plot(df['epoch'], df['precision'], label='Precision')
            ax.plot(df['epoch'], df['recall'], label='Recall')
            ax.set_title('Precision and Recall')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Value')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot mAP values
            ax = axes[1, 0]
            ax.plot(df['epoch'], df['mAP50'], label='mAP@0.5')
            ax.plot(df['epoch'], df['mAP50-95'], label='mAP@0.5:0.95')
            ax.set_title('Mean Average Precision (mAP)')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('mAP')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot learning rate if available
            ax = axes[1, 1]
            if 'lr0' in df.columns:
                ax.plot(df['epoch'], df['lr0'], label='Learning Rate')
                ax.set_title('Learning Rate Schedule')
                ax.set_xlabel('Epoch')
                ax.set_ylabel('Learning Rate')
                ax.legend()
                ax.grid(True, linestyle='--', alpha=0.6)
            else:
                # If learning rate is not available, plot a confusion matrix if available
                confusion_matrix_file = Path(results_dir) / 'confusion_matrix.png'
                if confusion_matrix_file.exists():
                    confusion_img = plt.imread(confusion_matrix_file)
                    ax.imshow(confusion_img)
                    ax.set_title('Confusion Matrix')
                    ax.axis('off')
                else:
                    # If no confusion matrix, show fitness
                    if 'fitness' in df.columns:
                        ax.plot(df['epoch'], df['fitness'], 'g-', label='Fitness')
                        ax.set_title('Model Fitness')
                        ax.set_xlabel('Epoch')
                        ax.set_ylabel('Fitness Value')
                        ax.legend()
                        ax.grid(True, linestyle='--', alpha=0.6)
            
            # Adjust layout and save
            plt.tight_layout(rect=[0, 0, 1, 0.95])  # Adjust for main title
            plt.savefig(os.path.join(output_dir, 'training_metrics.png'), dpi=300)
            plt.close()
            
            # Create PR curve plot if we have confidence data
            pr_curve_file = Path(results_dir) / 'PR_curve.png'
            if pr_curve_file.exists():
                pr_img = plt.imread(pr_curve_file)
                plt.figure(figsize=(10, 8))
                plt.imshow(pr_img)
                plt.axis('off')
                plt.title('Precision-Recall Curve')
                plt.tight_layout()
                plt.savefig(os.path.join(output_dir, 'pr_curve.png'), dpi=300)
                plt.close()
            
            # Create F1 score vs confidence threshold plot if available
            f1_curve_file = Path(results_dir) / 'F1_curve.png'
            if f1_curve_file.exists():
                f1_img = plt.imread(f1_curve_file)
                plt.figure(figsize=(10, 8))
                plt.imshow(f1_img)
                plt.axis('off')
                plt.title('F1 Score vs Confidence Threshold')
                plt.tight_layout()
                plt.savefig(os.path.join(output_dir, 'f1_curve.png'), dpi=300)
                plt.close()
            
            # Print final metrics
            final_epoch = df.iloc[-1]
            print("\nFinal Training Metrics:")
            print(f"Precision: {final_epoch['precision']:.4f}")
            print(f"Recall: {final_epoch['recall']:.4f}")
            print(f"mAP@0.5: {final_epoch['mAP50']:.4f}")
            print(f"mAP@0.5:0.95: {final_epoch['mAP50-95']:.4f}")
            
            return {
                'precision': final_epoch['precision'],
                'recall': final_epoch['recall'],
                'mAP50': final_epoch['mAP50'],
                'mAP50-95': final_epoch['mAP50-95']
            }
        else:
            print("Warning: CSV file does not contain expected metrics columns.")
    
    # Check for older YOLOv5 format results.txt
    results_txt = os.path.join(results_dir, 'results.txt')
    if os.path.exists(results_txt):
        # Parse results.txt in YOLOv5 format
        epochs, box_loss, obj_loss, cls_loss = [], [], [], []
        precision, recall, map50, map = [], [], [], []
        
        with open(results_txt, 'r') as f:
            for line in f:
                if line.startswith('  Epoch'):
                    continue  # Skip header line
                try:
                    # Extract metrics (format may vary)
                    parts = line.strip().split()
                    if len(parts) >= 12:
                        epoch = int(parts[0])
                        epochs.append(epoch)
                        
                        # Extract losses
                        box_loss.append(float(parts[2]))
                        obj_loss.append(float(parts[3]))
                        cls_loss.append(float(parts[4]))
                        
                        # Extract precision, recall, mAP
                        precision.append(float(parts[8]))
                        recall.append(float(parts[9]))
                        map50.append(float(parts[10]))
                        map.append(float(parts[11]))
                except Exception as e:
                    print(f"Error parsing line: {line}")
                    print(f"Exception: {e}")
        
        if epochs:
            # Create figure with multiple subplots
            fig, axes = plt.subplots(2, 2, figsize=(16, 12))
            fig.suptitle('YOLO Training Performance Metrics', fontsize=16)
            
            # Plot Loss curves
            ax = axes[0, 0]
            ax.plot(epochs, box_loss, label='Box Loss')
            ax.plot(epochs, obj_loss, label='Objectness Loss')
            ax.plot(epochs, cls_loss, label='Class Loss')
            ax.set_title('Training Losses')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Loss')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot Precision, Recall
            ax = axes[0, 1]
            ax.plot(epochs, precision, label='Precision')
            ax.plot(epochs, recall, label='Recall')
            ax.set_title('Precision and Recall')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Value')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot mAP values
            ax = axes[1, 0]
            ax.plot(epochs, map50, label='mAP@0.5')
            ax.plot(epochs, map, label='mAP@0.5:0.95')
            ax.set_title('Mean Average Precision (mAP)')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('mAP')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Plot combined loss
            ax = axes[1, 1]
            total_loss = [b + o + c for b, o, c in zip(box_loss, obj_loss, cls_loss)]
            ax.plot(epochs, total_loss, label='Total Loss')
            ax.set_title('Total Training Loss')
            ax.set_xlabel('Epoch')
            ax.set_ylabel('Loss')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.6)
            
            # Adjust layout and save
            plt.tight_layout(rect=[0, 0, 1, 0.95])  # Adjust for main title
            plt.savefig(os.path.join(output_dir, 'training_metrics.png'), dpi=300)
            plt.close()
            
            # Print final metrics
            print("\nFinal Training Metrics:")
            print(f"Precision: {precision[-1]:.4f}")
            print(f"Recall: {recall[-1]:.4f}")
            print(f"mAP@0.5: {map50[-1]:.4f}")
            print(f"mAP@0.5:0.95: {map[-1]:.4f}")
            
            return {
                'precision': precision[-1],
                'recall': recall[-1],
                'mAP50': map50[-1],
                'mAP50-95': map[-1]
            }

In [37]:
plot_yolo_performance('/home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolov11_plant_detection/yolov11s_run12', output_dir='performance_plots')

Warning: CSV file does not contain expected metrics columns.

In [39]:
test_image_dir = '/home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test'  # Your test images directory
model_path = '/home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/yolov11_plant_detection/yolov11s_run12/weights/best.pt'
# Run inference on test images
run_inference(model_path, test_image_dir)

WARNING ⚠️ inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

image 1/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_A16nzu.jpg: 640x480 1 healthy, 70.8ms
image 2/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_A1Euyz.jpg: 640x480 1 anthracnose, 11.1ms
image 3/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_A1HcV0.jpeg: 640x480 1 healthy, 1 anthracnose, 15.4ms
image 4/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_A4ZdJC.jpeg: 640x480 2 healthys, 9.2ms
image 5/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_A5SFUW.jpeg: 640x480 1 healthy, 10.6ms
image 6/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_A6Fogi.jpeg: 640x288 1 anthracnose, 75.0ms
image 7/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ABDCyn.jpeg: 640x480 3 healthys, 10.0ms
image 8/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ACg6Qf.jpeg: 640x288 1 anthracnose, 10.6ms
image 9/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AFi8A1.jpg: 640x480 4 healthys, 10.2ms
image 10/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AHlc9P.jpg: 640x480 1 healthy, 9.7ms
image 11/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AKu1Rh.jpeg: 480x640 1 cssvd, 70.4ms
image 12/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AQc6Fa.jpeg: 640x480 1 healthy, 9.4ms
image 13/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ARfduS.jpg: 640x480 4 healthys, 9.6ms
image 14/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AUiVHv.jpeg: 640x480 3 anthracnoses, 9.8ms
image 15/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AVXfJI.jpg: 640x480 1 cssvd, 10.1ms
image 16/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AWsPwc.jpg: 640x480 1 healthy, 9.6ms
image 17/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AX61Qc.jpg: 480x640 1 cssvd, 9.3ms
image 18/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AXba1J.jpg: 640x480 1 anthracnose, 10.6ms
image 19/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AZMNHM.jpeg: 640x480 1 healthy, 9.5ms
image 20/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AaL0uh.jpeg: 640x480 1 healthy, 9.3ms
image 21/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AcCl43.jpg: 640x480 2 cssvds, 9.4ms
image 22/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AhZ64h.jpeg: 480x640 (no detections), 9.3ms
image 23/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AopVga.jpg: 640x640 2 healthys, 10.1ms
image 24/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AqSCmf.jpeg: 640x480 1 anthracnose, 10.0ms
image 25/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AuxMUi.jpeg: 640x480 1 healthy, 9.7ms
image 26/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AvhFY7.jpg: 640x480 1 anthracnose, 9.9ms
image 27/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AwZkd2.jpg: 640x480 3 anthracnoses, 9.7ms
image 28/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AweW1B.jpg: 640x480 2 anthracnoses, 9.5ms
image 29/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_AypcIr.jpeg: 640x288 1 healthy, 1 cssvd, 10.9ms
image 30/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Az60r3.jpg: 640x480 1 cssvd, 10.5ms
image 31/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_B4zGjd.jpg: 640x480 1 cssvd, 9.8ms
image 32/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_B6Bi68.jpg: 640x640 6 healthys, 10.0ms
image 33/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_B9DYFf.jpg: 640x480 2 cssvds, 10.2ms
image 34/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BAszkB.jpeg: 640x480 4 healthys, 10.1ms
image 35/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BB69K4.jpg: 640x480 2 anthracnoses, 9.0ms
image 36/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BBmctK.jpeg: 480x640 2 healthys, 9.9ms
image 37/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BKGaS6.jpeg: 640x480 4 healthys, 10.4ms
image 38/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BMHFpr.jpeg: 640x480 1 healthy, 9.8ms
image 39/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BMR78x.jpg: 640x480 2 healthys, 11.2ms
image 40/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BPRGb0.jpg: 640x480 1 cssvd, 10.7ms
image 41/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BWl0VT.jpg: 640x640 2 healthys, 11.4ms
image 42/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BWoPJE.jpg: 640x480 1 anthracnose, 10.5ms
image 43/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BaQafS.jpeg: 640x480 3 healthys, 10.9ms
image 44/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BbUwow.jpg: 640x480 1 cssvd, 10.8ms
image 45/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BbuHsd.jpeg: 640x480 1 anthracnose, 10.6ms
image 46/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BcNWAl.jpeg: 640x480 1 anthracnose, 12.8ms
image 47/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Be0vKo.jpg: 640x480 3 anthracnoses, 9.9ms
image 48/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BhKgBW.jpg: 640x480 2 cssvds, 10.2ms
image 49/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BhOD7h.jpg: 640x480 2 cssvds, 10.2ms
image 50/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BiL2B8.jpeg: 640x288 4 healthys, 11.7ms
image 51/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BkHj0e.jpg: 640x480 1 cssvd, 11.3ms
image 52/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ByeZGA.jpg: 640x480 1 cssvd, 9.9ms
image 53/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Byn4Lt.JPG: 640x480 3 healthys, 9.4ms
image 54/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_C0Cmx7.jpg: 640x480 2 cssvds, 15.2ms
image 55/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_C0Uehq.jpg: 640x480 1 cssvd, 10.7ms
image 56/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_C1vtA9.jpg: 640x480 2 cssvds, 9.8ms
image 57/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_C3AIRq.jpg: 640x480 1 cssvd, 9.3ms
image 58/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_C8BlN8.jpg: 640x480 1 cssvd, 9.3ms
image 59/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CBUJ2U.jpg: 640x480 2 cssvds, 9.3ms
image 60/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CBkuOC.jpg: 640x480 1 cssvd, 11.5ms
image 61/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CBsr8I.jpg: 640x480 1 cssvd, 11.3ms
image 62/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CE3bfu.jpeg: 640x480 1 anthracnose, 9.0ms
image 63/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CEnc58.jpeg: 640x480 1 cssvd, 9.3ms
image 64/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CGnAYP.jpg: 640x480 2 cssvds, 11.5ms
image 65/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CP7YI8.jpg: 640x480 1 cssvd, 10.2ms
image 66/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CRgjeZ.jpg: 640x480 1 healthy, 9.5ms
image 67/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CTHVbX.jpg: 640x480 1 cssvd, 10.7ms
image 68/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CTJaUE.jpg: 640x480 1 anthracnose, 15.8ms
image 69/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CUByHJ.jpg: 640x640 1 healthy, 1 cssvd, 10.5ms
image 70/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CWDQS2.jpeg: 288x640 1 anthracnose, 74.5ms
image 71/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Cc4hHM.jpg: 640x384 1 cssvd, 82.8ms
image 72/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CcIssk.jpg: 640x480 1 anthracnose, 11.0ms
image 73/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Ccy5YA.jpeg: 640x480 1 anthracnose, 9.6ms
image 74/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CiaBXB.jpg: 640x640 4 healthys, 10.8ms
image 75/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Cisrab.jpeg: 640x480 1 anthracnose, 10.6ms
image 76/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Cj1prl.jpg: 640x480 1 cssvd, 10.9ms
image 77/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CjxpRk.JPG: 640x480 1 anthracnose, 9.5ms
image 78/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CkzYK9.jpg: 640x480 2 anthracnoses, 9.9ms
image 79/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Cm5njC.jpg: 640x480 1 cssvd, 9.2ms
image 80/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CqDi1f.jpg: 480x640 1 cssvd, 10.7ms
image 81/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CrSUii.jpeg: 640x480 1 anthracnose, 10.1ms
image 82/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CsD8EL.jpg: 640x480 1 anthracnose, 9.8ms
image 83/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CuBkOO.jpg: 640x640 1 healthy, 10.5ms
image 84/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Cw5fwO.jpg: 480x640 1 anthracnose, 10.0ms
image 85/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Cy2zVL.jpg: 640x480 2 cssvds, 10.2ms
image 86/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CzSEcr.jpg: 640x640 3 healthys, 10.0ms
image 87/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_D1Efw8.jpg: 640x480 2 cssvds, 10.5ms
image 88/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_D2n955.jpg: 640x480 1 cssvd, 9.7ms
image 89/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_D57TlR.jpeg: 640x480 (no detections), 10.0ms
image 90/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_D7howW.jpg: 640x480 1 cssvd, 9.8ms
image 91/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_D99Mnd.jpg: 640x480 2 cssvds, 9.3ms
image 92/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DCnllR.jpg: 640x640 7 healthys, 9.7ms
image 93/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DFyyru.jpg: 640x480 1 cssvd, 9.8ms
image 94/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DHCirx.jpg: 640x480 2 anthracnoses, 9.9ms
image 95/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DJdr6B.jpg: 640x480 1 cssvd, 9.8ms
image 96/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DLYLty.jpg: 640x480 2 cssvds, 9.8ms
image 97/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DQIbC9.jpeg: 640x288 1 anthracnose, 10.4ms
image 98/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DWOFob.jpg: 640x480 2 anthracnoses, 10.0ms
image 99/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DbrLAf.jpeg: 640x480 1 cssvd, 10.9ms
image 100/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DcMUYA.jpg: 640x480 3 healthys, 9.8ms
image 101/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DdPn6R.jpg: 640x480 1 anthracnose, 10.0ms
image 102/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Dh68Pg.jpeg: 640x480 4 healthys, 9.4ms
image 103/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DitJb1.jpeg: 640x640 1 anthracnose, 10.1ms
image 104/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DjtECY.jpeg: 640x288 1 anthracnose, 10.4ms
image 105/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DldPpd.jpeg: 640x480 1 anthracnose, 9.4ms
image 106/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DorYRG.jpg: 640x480 2 anthracnoses, 9.3ms
image 107/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Dt9R4S.jpg: 640x480 1 healthy, 9.2ms
image 108/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DtvCD1.jpeg: 640x480 3 healthys, 9.4ms
image 109/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Dw2paJ.jpg: 640x480 2 cssvds, 10.7ms
image 110/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DxuEWw.jpg: 640x640 3 healthys, 10.1ms
image 111/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DyHG2r.jpg: 480x640 1 cssvd, 10.2ms
image 112/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Dz7nGM.jpeg: 640x480 1 healthy, 10.4ms
image 113/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DzdeNP.jpg: 640x640 1 healthy, 9.6ms
image 114/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_E1lv1B.jpg: 640x480 2 cssvds, 9.9ms
image 115/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_E27ZzV.jpg: 640x480 2 anthracnoses, 9.0ms
image 116/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_E5U3se.jpeg: 640x480 1 healthy, 9.4ms
image 117/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_E5kGYT.jpeg: 480x640 1 anthracnose, 9.5ms
image 118/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_E7haV4.jpeg: 640x480 (no detections), 10.2ms
image 119/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_E9zHw7.jpg: 640x640 2 healthys, 9.7ms
image 120/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EBhZzJ.jpeg: 640x640 2 anthracnoses, 8.9ms
image 121/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EDbrKH.jpg: 640x480 1 cssvd, 10.9ms
image 122/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EFetFh.jpg: 480x640 1 cssvd, 10.2ms
image 123/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EG9Mkf.jpg: 640x480 2 healthys, 10.2ms
image 124/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EGzXyJ.jpg: 640x480 2 anthracnoses, 10.1ms
image 125/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EJgRE4.jpg: 640x640 2 healthys, 9.9ms
image 126/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EOFmpE.jpeg: 640x288 1 anthracnose, 10.6ms
image 127/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EQ9YWy.jpg: 640x480 2 healthys, 11.3ms
image 128/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ERLFdx.jpg: 640x480 1 cssvd, 10.2ms
image 129/1626 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EWolCN.jpeg: 640x480 1 healthy, 11.3ms

In [41]:
# Aggregate predictions for multi-label evaluation
aggregate_predictions('/home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/predictions/predictions.csv')

Aggregated predictions saved to image_level_predictions.csv

In [ ]:
Image_ID,class,confidence,ymin,xmin,ymax,xmax
ID_Genxyu.jpg,healthy,0.5,100,100,100,100

In [ ]:

# Example usage
if __name__ == "__main__":
    # Prepare test data
    gt_csv = prepare_test_data("test_data.csv", "test_images")
    
    # Visualize predictions
    batch_visualize_predictions("test_images", "predictions/predictions.csv", "visualizations")
    
    # Prepare submission
    submission_csv = prepare_submission("predictions/predictions.csv", "test_images", "submission.csv")
    
    # Evaluate predictions
    from evaluation_script import evaluate_multilabel
    evaluate_multilabel(gt_csv, submission_csv)

In [54]:
TEST_IMAGES_DIR

PosixPath('dataset/images/test')

In [48]:
from ultralytics import YOLO
from tqdm.notebook import tqdm

# Load the trained YOLO model
model = YOLO(model_path)

# Path to the test images directory
test_dir_path = TEST_IMAGES_DIR

# Get a list of all image files in the test directory
image_files = os.listdir(test_dir_path)

# Initialize an empty list to store the results for all images
all_data = []

# Initialize an empty list to store the results for all images
all_data = []

# Iterate through each image in the directory
for image_file in tqdm(image_files):
    # Full path to the image
    img_path = os.path.join(test_dir_path, image_file)

    # Make predictions on the image
    results = model(img_path)

    # Extract bounding boxes, confidence scores, and class labels
    boxes = results[0].boxes.xyxy.tolist() if results[0].boxes else []  # Bounding boxes in xyxy format
    classes = results[0].boxes.cls.tolist() if results[0].boxes else []  # Class indices
    confidences = results[0].boxes.conf.tolist() if results[0].boxes else []  # Confidence scores
    names = results[0].names  # Class names dictionary

    if boxes:  # If detections are found
        for box, cls, conf in zip(boxes, classes, confidences):
            x1, y1, x2, y2 = box
            detected_class = names[int(cls)]  # Get the class name from the names dictionary

            # Add the result to the all_data list
            all_data.append({
                'Image_ID': str(image_file),
                'class': detected_class,
                'confidence': conf,
                'ymin': y1,
                'xmin': x1,
                'ymax': y2,
                'xmax': x2
            })
    else:  # If no objects are detected
        all_data.append({
            'Image_ID': str(image_file),
            'class': "None",
            'confidence': None,
            'ymin': None,
            'xmin': None,
            'ymax': None,
            'xmax': None
        })

  0%|          | 0/1626 [00:00<?, ?it/s]

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_zSiC0w.jpg: 640x480 1 healthy, 9.4ms
Speed: 2.9ms preprocess, 9.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_kvMeX2.JPG: 640x480 1 cssvd, 10.8ms
Speed: 2.7ms preprocess, 10.8ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EBhZzJ.jpeg: 640x640 2 anthracnoses, 8.8ms
Speed: 3.5ms preprocess, 8.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_p4aJv5.jpg: 640x480 2 cssvds, 10.0ms
Speed: 1.8ms preprocess, 10.0ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Vq59xO.jpg: 640x480 1 anthracnose, 8.6ms
Speed: 2.7ms preprocess, 8.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_lJqimA.jpg: 640x480 1 cssvd, 9.3ms
Speed: 1.6ms preprocess, 9.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_IQXVr3.jpg: 640x640 3 healthys, 9.7ms
Speed: 2.0ms preprocess, 9.7ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_W4b7ZX.jpg: 640x480 1 cssvd, 9.4ms
Speed: 2.6ms preprocess, 9.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_xXWJsa.jpg: 640x480 1 healthy, 8.8ms
Speed: 2.5ms preprocess, 8.8ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_rMv7Zl.jpg: 640x480 1 cssvd, 8.9ms
Speed: 1.8ms preprocess, 8.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_vSr6vC.jpg: 640x480 2 anthracnoses, 10.3ms
Speed: 3.1ms preprocess, 10.3ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_tBKR7L.jpeg: 640x288 2 healthys, 9.6ms
Speed: 2.1ms preprocess, 9.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 288)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_iXRhGf.jpeg: 640x480 2 healthys, 9.9ms
Speed: 2.7ms preprocess, 9.9ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_TNiZUE.jpg: 640x480 1 cssvd, 8.9ms
Speed: 1.8ms preprocess, 8.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_yZYd0h.jpg: 640x480 1 cssvd, 8.8ms
Speed: 1.5ms preprocess, 8.8ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_rduPKu.jpg: 640x480 2 anthracnoses, 8.6ms
Speed: 2.2ms preprocess, 8.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_RirekC.jpg: 640x384 3 cssvds, 9.5ms
Speed: 1.7ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 384)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_vqs2Dt.jpeg: 640x480 1 healthy, 9.6ms
Speed: 2.7ms preprocess, 9.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BhKgBW.jpg: 640x480 2 cssvds, 8.9ms
Speed: 1.5ms preprocess, 8.9ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_tuijN0.jpg: 480x640 2 healthys, 9.6ms
Speed: 2.6ms preprocess, 9.6ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_eKtHoY.jpeg: 640x480 2 healthys, 9.9ms
Speed: 2.7ms preprocess, 9.9ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_kWKsnF.jpg: 640x480 1 anthracnose, 9.5ms
Speed: 2.6ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ZYbA7d.jpg: 640x480 1 anthracnose, 9.5ms
Speed: 2.3ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Suoisd.JPG: 640x480 1 cssvd, 10.4ms
Speed: 2.7ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_zbueIx.jpeg: 640x480 2 healthys, 9.6ms
Speed: 2.7ms preprocess, 9.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Az60r3.jpg: 640x480 1 cssvd, 9.4ms
Speed: 1.8ms preprocess, 9.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_kOvqJh.jpeg: 640x640 1 anthracnose, 10.0ms
Speed: 3.0ms preprocess, 10.0ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_CiaBXB.jpg: 640x640 4 healthys, 9.7ms
Speed: 1.9ms preprocess, 9.7ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_YGGSTX.jpg: 480x640 2 healthys, 9.9ms
Speed: 2.5ms preprocess, 9.9ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_SXgYVp.jpg: 640x480 1 healthy, 9.3ms
Speed: 2.6ms preprocess, 9.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_NOFmdO.jpg: 640x480 1 anthracnose, 9.0ms
Speed: 2.2ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_a0srv9.jpg: 480x640 2 anthracnoses, 9.4ms
Speed: 2.6ms preprocess, 9.4ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_nSawWh.jpg: 640x480 1 anthracnose, 13.3ms
Speed: 2.4ms preprocess, 13.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_aatE8l.jpeg: 640x480 2 healthys, 9.2ms
Speed: 2.6ms preprocess, 9.2ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_gvnAED.jpg: 640x480 2 cssvds, 9.4ms
Speed: 1.5ms preprocess, 9.4ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_uxGyKi.jpg: 640x480 1 cssvd, 9.3ms
Speed: 2.3ms preprocess, 9.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_YATAta.jpeg: 640x480 2 healthys, 9.1ms
Speed: 2.7ms preprocess, 9.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_p6OqyL.jpg: 640x480 1 cssvd, 9.5ms
Speed: 1.5ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BWoPJE.jpg: 640x480 1 anthracnose, 9.5ms
Speed: 2.8ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_BbUwow.jpg: 640x480 1 cssvd, 9.1ms
Speed: 2.3ms preprocess, 9.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_tvu9FP.jpg: 640x480 2 cssvds, 9.0ms
Speed: 1.5ms preprocess, 9.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_XEbuST.jpg: 640x480 1 anthracnose, 9.2ms
Speed: 2.7ms preprocess, 9.2ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_rO21Rv.jpg: 640x480 1 cssvd, 9.4ms
Speed: 1.7ms preprocess, 9.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_wB12vR.jpg: 640x480 1 cssvd, 9.3ms
Speed: 1.5ms preprocess, 9.3ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_NbJj7a.jpg: 480x640 2 cssvds, 9.7ms
Speed: 2.5ms preprocess, 9.7ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_t0kbuH.jpg: 640x480 3 healthys, 11.7ms
Speed: 2.8ms preprocess, 11.7ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_iafMXS.jpg: 640x480 1 cssvd, 9.8ms
Speed: 3.2ms preprocess, 9.8ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_deS0wq.jpg: 640x480 1 cssvd, 8.7ms
Speed: 2.6ms preprocess, 8.7ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_L9vR9c.jpeg: 480x640 4 healthys, 9.7ms
Speed: 2.6ms preprocess, 9.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_dlFmzD.jpeg: 640x288 2 healthys, 12.0ms
Speed: 2.3ms preprocess, 12.0ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 288)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_XlQcW0.JPG: 640x480 2 healthys, 10.1ms
Speed: 2.6ms preprocess, 10.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ExXVO1.jpg: 640x480 2 cssvds, 8.9ms
Speed: 2.3ms preprocess, 8.9ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_PDuPIE.jpeg: 640x480 1 healthy, 9.0ms
Speed: 2.7ms preprocess, 9.0ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_rry4FO.JPG: 640x480 11 healthys, 9.9ms
Speed: 2.7ms preprocess, 9.9ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ZGTOCS.jpg: 640x640 7 healthys, 10.3ms
Speed: 2.3ms preprocess, 10.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_rSmGHZ.jpg: 640x480 1 anthracnose, 9.6ms
Speed: 2.7ms preprocess, 9.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_rANrt1.jpeg: 640x480 2 healthys, 9.5ms
Speed: 2.5ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_eKexBX.JPG: 640x480 1 healthy, 9.6ms
Speed: 2.6ms preprocess, 9.6ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_wKhaSp.jpg: 640x480 5 healthys, 9.4ms
Speed: 2.0ms preprocess, 9.4ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Vbc7tX.JPG: 640x480 1 healthy, 9.4ms
Speed: 2.9ms preprocess, 9.4ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Tm3kkv.jpeg: 640x480 3 healthys, 9.9ms
Speed: 2.8ms preprocess, 9.9ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_EdzwdN.jpg: 640x480 1 anthracnose, 9.3ms
Speed: 2.7ms preprocess, 9.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_NnZXiB.jpg: 640x480 1 cssvd, 9.4ms
Speed: 1.6ms preprocess, 9.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_XxYDsU.jpg: 480x640 1 cssvd, 11.7ms
Speed: 1.9ms preprocess, 11.7ms inference, 1.1ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DldPpd.jpeg: 640x480 1 anthracnose, 10.5ms
Speed: 3.0ms preprocess, 10.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_TAZIJ7.jpeg: 480x640 1 healthy, 10.0ms
Speed: 2.7ms preprocess, 10.0ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_bWrGAE.JPG: 640x480 1 cssvd, 10.1ms
Speed: 3.2ms preprocess, 10.1ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_Gbv0j3.jpg: 640x480 1 cssvd, 9.3ms
Speed: 2.0ms preprocess, 9.3ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_kjTAmo.jpg: 640x480 3 cssvds, 9.6ms
Speed: 2.1ms preprocess, 9.6ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_OKnByL.jpg: 640x480 2 anthracnoses, 9.5ms
Speed: 2.6ms preprocess, 9.5ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_jc8o9w.jpg: 640x480 1 cssvd, 9.4ms
Speed: 1.8ms preprocess, 9.4ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_p9vAO2.jpg: 480x640 1 cssvd, 9.5ms
Speed: 1.8ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_DFyyru.jpg: 640x480 1 cssvd, 10.3ms
Speed: 2.6ms preprocess, 10.3ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_d6gpj1.jpg: 640x480 2 cssvds, 9.4ms
Speed: 1.8ms preprocess, 9.4ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_tTFNac.jpg: 640x480 2 anthracnoses, 9.5ms
Speed: 1.5ms preprocess, 9.5ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_VzT72C.jpeg: 640x640 1 cssvd, 10.1ms
Speed: 3.0ms preprocess, 10.1ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_C8BlN8.jpg: 640x480 1 cssvd, 10.6ms
Speed: 2.6ms preprocess, 10.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_ORZ9Bi.jpg: 640x640 3 healthys, 10.1ms
Speed: 2.0ms preprocess, 10.1ms inference, 1.1ms postprocess per image at shape (1, 3, 640, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_nnRffu.jpg: 640x480 2 anthracnoses, 10.6ms
Speed: 2.4ms preprocess, 10.6ms inference, 1.2ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_db9KWW.jpg: 640x480 1 anthracnose, 10.4ms
Speed: 1.7ms preprocess, 10.4ms inference, 1.3ms postprocess per image at shape (1, 3, 640, 480)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_s9aN3f.jpg: 480x640 2 cssvds, 12.6ms
Speed: 2.6ms preprocess, 12.6ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)

image 1/1 /home/jason-server/Documents/deep_learning_aueb/amini_cocoa_contamination/dataset/images/test/ID_P8IJWT.jpg: 640x480 1 cssvd, 11.9ms
Speed: 1.9ms preprocess, 11.9ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 480)


In [50]:
# Convert the list to a DataFrame for all images
sub = pd.DataFrame(all_data)

In [53]:
sub

,Image_ID,class,confidence,ymin,xmin,ymax,xmax
0,ID_zSiC0w.jpg,healthy,0.803784,911.792542,548.785400,2914.808594,1705.729614
1,ID_kvMeX2.JPG,cssvd,0.473394,602.720154,398.513397,2853.851807,1585.934692
2,ID_EBhZzJ.jpeg,anthracnose,0.819010,3.978644,311.530884,3010.936279,2203.006348
3,ID_EBhZzJ.jpeg,anthracnose,0.264222,31.505287,0.000000,1919.579956,1121.500732
4,ID_p4aJv5.jpg,cssvd,0.845414,220.992050,0.608660,1044.002808,436.094330
...,...,...,...,...,...,...,...
2794,ID_xjnuvj.jpg,healthy,0.756919,38.240887,98.341141,355.820465,334.627960
2795,ID_xjnuvj.jpg,healthy,0.619615,0.000000,184.657120,115.048332,403.408936
2796,ID_xjnuvj.jpg,healthy,0.492850,48.768326,10.391272,272.033508,177.581467
2797,ID_xjnuvj.jpg,healthy,0.300794,0.000000,122.022362,57.127178,252.787720
2798,ID_MISf6G.jpeg,anthracnose,0.818727,46.799850,492.823792,1658.034912,4000.000000

In [49]:
INPUT_DATA_DIR

PosixPath('.')

In [52]:
# Create submission file to be uploaded to Zindi for scoring
sub.to_csv(f'{INPUT_DATA_DIR / "BenchmarkSubmission.csv"}', index = False)